### ISSUE TITLE
Add metric to get "earliest time ssl chain verification fails" through all redirects

### ISSUE THREAD

**Issue by gebi** [prometheus/blackbox_exporter#1012]
To catch certs expiring from intermediate redirection steps with a usefull time to react it would be crucial to have a metric that contains **the earliest time the last chain of each https request expires**, basically:

```
min(of probe_ssl_last_chain_expiry_timestamp_seconds of all https requests)
```

Similar to `probe_ssl_last_chain_expiry_timestamp_seconds` but over all requests.
Current blackbox exporter with defaults `follow_redirects: true` makes such problems very hard to catch and successfully hides it until it's too late and produces a hard fail when the certifiate of an intermediate redirection step is already expired with the default `tls_config.insecure_skip_verify: false` thus giving no head room for admins.

(this problems happens a lot with SAML setups and redirection to the IDP, eg.)

If `insecure_skip_verify: false` is set blackbox exporter fails the probe and aborts, but then it's already too late and user impact already happened.

### What is the blackbox.yml module config.
```yaml
  https_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      follow_redirects: true
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4"
```

### What is the prometheus.yml scrape config.
```yaml
  - job_name: 'blackbox'
    metrics_path: /probe
    scrape_interval: 15s
    file_sd_configs:
     - files:
       - "/etc/prometheus/targets/blackbox-targets.yml"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: []
        target_label: __address__
        replacement: 127.0.0.1:9115
```

### What logging output did you get from adding `&debug=true` to the probe URL?
```
ts=2022-12-29T17:30:01.45886877Z caller=main.go:181 module=https_2xx target=https://service.example.com/ level=info msg="Beginning probe" probe=http timeout_seconds=5
ts=2022-12-29T17:30:01.458984524Z caller=http.go:327 module=https_2xx target=https://service.example.com/ level=info msg="Resolving target address" target=service.example.com ip_protocol=ip4
ts=2022-12-29T17:30:01.459342799Z caller=http.go:327 module=https_2xx target=https://service.example.com/ level=info msg="Resolved target address" target=service.example.com ip=42.42.27.50
ts=2022-12-29T17:30:01.459454168Z caller=client.go:251 module=https_2xx target=https://service.example.com/ level=info msg="Making HTTP request" url=https://42.42.27.50/ host=service.example.com
ts=2022-12-29T17:30:01.519991788Z caller=client.go:497 module=https_2xx target=https://service.example.com/ level=info msg="Received redirect" location="https://idp.example.com:443/openam/SSORedirect/metaAlias/idp?SAMLRequest=XXX"
ts=2022-12-29T17:30:01.520059473Z caller=client.go:251 module=https_2xx target=https://service.example.com/ level=info msg="Making HTTP request" url="https://idp.example.com:443/openam/SSORedirect/metaAlias/idp?SAMLRequest=XXX" host=
ts=2022-12-29T17:30:01.520089824Z caller=client.go:251 module=https_2xx target=https://service.example.com/ level=info msg="Address does not match first address, not sending TLS ServerName" first=42.42.27.50 address=idp.example.com:443
ts=2022-12-29T17:30:01.53283363Z caller=handler.go:117 module=https_2xx target=https://service.example.com/ level=info msg="Received HTTP response" status_code=200
ts=2022-12-29T17:30:01.532936145Z caller=handler.go:117 module=https_2xx target=https://service.example.com/ level=info msg="Response timings for roundtrip" roundtrip=0 start=2022-12-29T18:30:01.459530491+01:00 dnsDone=2022-12-29T18:30:01.459530491+01:00 connectDone=2022-12-29T18:30:01.460748824+01:00 gotConn=2022-12-29T18:30:01.469683072+01:00 responseStart=2022-12-29T18:30:01.519915653+01:00 tlsStart=2022-12-29T18:30:01.460770376+01:00 tlsDone=2022-12-29T18:30:01.469620845+01:00 end=0001-01-01T00:00:00Z
ts=2022-12-29T17:30:01.532998045Z caller=handler.go:117 module=https_2xx target=https://service.example.com/ level=info msg="Response timings for roundtrip" roundtrip=1 start=2022-12-29T18:30:01.520169532+01:00 dnsDone=2022-12-29T18:30:01.520544333+01:00 connectDone=2022-12-29T18:30:01.521105723+01:00 gotConn=2022-12-29T18:30:01.528725557+01:00 responseStart=2022-12-29T18:30:01.53273469+01:00 tlsStart=2022-12-29T18:30:01.521142728+01:00 tlsDone=2022-12-29T18:30:01.528712893+01:00 end=2022-12-29T18:30:01.532919243+01:00
ts=2022-12-29T17:30:01.533093566Z caller=main.go:181 module=https_2xx target=https://service.example.com/ level=info msg="Probe succeeded" duration_seconds=0.074197468
```

### What did you expect to see?
some metric that give this timestamp to alert 30 days before.
```
probe_ssl_earliest_cert_expiry 1.671231231e+09

```

### What did you see instead?
expired cert from the redirect chain is not contained in this metric.
```
probe_ssl_earliest_cert_expiry 1.712312312e+09
```
