### ISSUE TITLE
Problems using the dns module

### ISSUE THREAD

**Issue by raypettersen** [prometheus/blackbox_exporter#102]
I'm having trouble using the dns module. Documentation is too unclear, for me atleast. I've been trying a simple example without any luck:

http://localhost:9115/probe?module=dns_tcp&target=www.google.com

blackbox just complains that the module doesn't exist. I've tried dns, dns_udp, dns_tcp without any luck. It is also unclear for me how I'm supposed to configure the blackbox.yaml file. Currently I have:

```
  dns_tcp:
    prober: dns
    dns:
      protocol: "tcp" # accepts "tcp/tcp4/tcp6/udp/udp4/udp6", defaults to "udp"
      preferred_ip_protocol: "ip4" # used for "udp/tcp", defaults to "ip6"
      query_name: "www.google.com"
```

With query_name hardcoded in the config, is target  supposed to be the DNS server?

The only thing I'm getting in logs, are http errors. No reference to DNS. Appreciate any tips for getting me over this frustrating threshold..

**Comment by brian-brazil** [comment]
The target is the DNS server, or whatever other system you're probing.

**Comment by raypettersen** [comment]
Thanks, that's neat. Any advice on why I'm constantly getting the "Unkown module dns_tcp" messages during simple testing?

**Comment by brian-brazil** [comment]
It's probably an indentation issue with your YAML.

**Comment by raypettersen** [comment]
I've stripped everything down to the bare minimum. Still no change.

``` modules:
  http_2xx:
    prober: http
    timeout: 5s
  dns_tcp:
    prober: dns
    dns:
      protocol: "tcp" # accepts "tcp/tcp4/tcp6/udp/udp4/udp6", defaults to "udp"
      preferred_ip_protocol: "ip4" # used for "udp/tcp", defaults to "ip6"
      query_name: "www.prometheus.io"
``` 

> http://localhost:9115/probe?module=dns_tcp&target=8.8.8.8

Unkown module dns_tcp

**Comment by brian-brazil** [comment]
Did you restart the exporter after changing the config?

**Comment by raypettersen** [comment]
ofc.

**Comment by brian-brazil** [comment]
Are your sure that it restarted, and what's listening on that port is what you think is listening on it?

**Comment by raypettersen** [comment]
```time="2017-01-14T18:21:52+01:00" level=info msg="Starting blackbox_exporter (version=0.4.0, branch=master, revision=be7a4226ed32a6407d7895ee5a0bd892f0f34692)" source="main.go:151" 
time="2017-01-14T18:21:52+01:00" level=info msg="Build context (go=go1.7.3, user=root@a5c014222c61, date=20170112-15:23:58)" source="main.go:152" 
time="2017-01-14T18:21:52+01:00" level=info msg="Listening on :9115" source="main.go:183"

**Comment by brian-brazil** [comment]
Hmm, are you sure you've got the right config file?

**Comment by raypettersen** [comment]
100% sure.

From ps aux.
> blackbox_exporter config.file=/etc/blackbox_exporter/blackbox.yml

cat /etc/blackbox_exporter/blackbox.yml

```
modules:
  http_2xx:
    prober: http
    timeout: 5s
  dns_tcp_example:
    prober: dns
    dns:
      protocol: "tcp" # accepts "tcp/tcp4/tcp6/udp/udp4/udp6", defaults to "udp"
      preferred_ip_protocol: "ip4" # used for "udp/tcp", defaults to "ip6"
      query_name: "www.prometheus.io"
```
