### ISSUE TITLE
TCP Prober occasionally delay to 1S

### ISSUE THREAD

**Issue by shaxiaozz** [prometheus/blackbox_exporter#1037]
I used a container to run BlackBox-EXPORTER, and configured TCP_Connect to complete the detection of targets.

However, after running for a while, it was found that a target was often delayed to 1S. Later, we caught the package analysis, and found that the reason for 1S was to trigger TCP re -transmission.

Our network Team feedback is because the request party uses port reuse, so I want to determine whether the Blackbox-EXPORTER is used to complete the port reuse when the TCP_CONNECT is completed. If there is any configuration, can it be closed? Intersection

The following is my environment:
### Host operating system: output of `uname -a`
```
/ # uname -a
Linux blackbox-exporter-5d5d56667d-rxf2x 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 GNU/Linux
```
### blackbox_exporter version: output of `blackbox_exporter --version`
```
/ # /bin/blackbox_exporter --version
blackbox_exporter, version 0.23.0 (branch: HEAD, revision: 26fc98b9c6db21457653ed752f34d1b7fb5bba43)
  build user:       root@f360719453e3
  build date:       20221202-12:26:32
  go version:       go1.19.3
  platform:         linux/amd64
```

### What is the blackbox.yml module config.
```
modules:
  http_2xx:
    prober: http
    http:
      valid_status_codes: [200,400,403,404,405]

  tcp_connect:
    prober: tcp
    timeout: 2s
```
### What is the prometheus.yml scrape config.
```
  - job_name: "blackbox-exporter-tcp"
    metrics_path: /probe
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
    - targets:
       - 192.168.34.20:1521
      labels:
       instance: "172.31.116.15:9115"
       env: prd
       module: "tcp_connect"
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: target
     - source_labels: [module]
       target_label: __param_module
     - source_labels: [instance]
       target_label: __address__
     - source_labels: [__address__]
       regex: (.*):(.*)
       target_label: source
```

The following is the monitoring display
![image](https://user-images.githubusercontent.com/43721571/223594292-663e6970-5096-41bd-87f4-28f0c559d290.png)
