### ISSUE TITLE
Dynamic token read facility for POST request

### ISSUE THREAD

**Issue by Manoharan-NMS** [prometheus/blackbox_exporter#1038]
Is there any facility to read access token dynamically from blackbox exporter ?

Else it's possible to access token from file. Kindly suggest.

**Comment by roidelapluie** [comment]
You can use the `authorization` configuration option in Blackbox Exporter to set the `Authorization` header with credentials from a file.

Here is how you can set up Blackbox Exporter to read the token from a file:

```yaml
http:
  # Configure the HTTP probe's settings here.
  authorization:
    # Set the authentication type. 'Bearer' is the default value and can be omitted.
    type: Bearer
    # Set the path to the file containing the token.
    credentials_file: /path/to/token/file
```

Please replace `/path/to/token/file` with the actual file path containing your token.

**Comment by Manoharan-NMS** [comment]
**Existing** working code:

```
  http_post:
    prober: http
    timeout: 10s
    http:
      #valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      #valid_status_codes: [200,301]
      #fail_if_ssl: false
      #fail_if_not_ssl: false
      method: POST
      #bearer_token:  /etc/blackbox_exporter/access_token
      tls_config:
        insecure_skip_verify: true
      headers:
              content-type: "application/json"
              #X-Frame-Options: "DENY"
              Authorization: "Basic YWRtaW46TXlCQCQhQ0F1dGhQQFMk"
              token: "CsMJAvOQOabyQvGODt8xYWdqgeI3OXYIMUpKApgfxi7rtcDJVk27XROKr3rw44WM9yDxihTdfh6JAqi0F1D48ZAX3ADULXIo1xasQgeD7fPepRnaOYEjVHiSQuPzR1lvBUUl2kbo7pAm7sCoBVWqDVfEJ163831jeG1EbxcpejqBa4qXBu32x1KqMmUUB3wDAajcs53fYZpBbCqQbGPf3XUmAqTcYqBCRrF20vpKFocZAKmgvyj1Bfky0U7lQvP8"
      body: '{"filterDimension": [],"filterDimensionValue": [],"sankeyFilterDimension": [],"sankeyFilterDimensionValue": [],"isTeamScoreCardVisible": true,"selectedTeam": null}'
```

**After** you code changes
```
Module configuration:
prober: http
timeout: 10s
http:
  ip_protocol_fallback: true
  method: POST
  headers:
    Authorization: Basic YWRtaW46TXlCQCQhQ0F1dGhQQFMk
    content-type: application/json
  body: '{"name": null}'
  authorization:
    type: Bearer
    credentials_file: access_token
  tls_config:
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
tcp:
  ip_protocol_fallback: true
icmp:
  ip_protocol_fallback: true
  ttl: 64
dns:
  ip_protocol_fallback: true
  recursion_desired: true
```
**access_token** File
```
CsMJAvOQOabyQvGODt8xYWdqgeI3OXYIMUpKApgfxi7rtcDJVk27XROKr3rw44WM9yDxihTdfh6JAqi0F1D48ZAX3ADULXIo1xasQgeD7fPepRnaOYEjVHiSQuPzR1lvBUUl2kbo7pAm7sCoBVWqDVfEJ163831jeG1EbxcpejqBa4qXBu32x1KqMmUUB3wDAajcs53fYZpBbCqQbGPf3XUmAqTcYqBCRrF20vpKFocZAKmgvyj1Bfky0U7lQvP8
```

**Expected** Result
`probe_success 1`

**Actual** Result
`probe_success 0`

```
level=info msg="Invalid HTTP response status code, wanted 2xx" status_code=40
```

**Comments**
Kindly confirm the configuration to access token file.
If possible share the sample working configuration
