### ISSUE TITLE
DNS prober timeout is not respected

### ISSUE THREAD

**Issue by zerkms** [prometheus/blackbox_exporter#1043]
### Host operating system: output of `uname -a`

```
Linux <redacted> 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### blackbox_exporter version: output of `blackbox_exporter --version`

```
blackbox_exporter, version 0.23.0 (branch: HEAD, revision: 26fc98b9c6db21457653ed752f34d1b7fb5bba43)
  build user:       root@f360719453e3
  build date:       20221202-12:26:32
  go version:       go1.19.3
  platform:         linux/amd64
```

### What logging output did you get from adding `&debug=true` to the probe URL?
```
Logs for the probe:
ts=2023-03-19T20:59:46.593442215Z caller=main.go:181 module=dns_redacted_A target=ns1.redacted level=info msg="Beginning probe" probe=dns timeout_seconds=9.5
ts=2023-03-19T20:59:46.593527928Z caller=dns.go:200 module=dns_redacted_A target=ns1.redacted level=info msg="Resolving target address" target=ns1.redacted ip_protocol=ip6
ts=2023-03-19T20:59:46.59856768Z caller=dns.go:200 module=dns_redacted_A target=ns1.redacted level=info msg="Resolved target address" target=ns1.redacted ip=redacted
ts=2023-03-19T20:59:46.59858928Z caller=handler.go:117 module=dns_redacted_A target=ns1.redacted level=info msg="Making DNS query" target=redacted:53 dial_protocol=udp4 query=redacted type=1 class=1
ts=2023-03-19T20:59:56.094248741Z caller=handler.go:117 module=dns_redacted_A target=ns1.redacted level=error msg="Error while sending a DNS query" err="read udp4 redacted:55614->redacted:53: i/o timeout"
ts=2023-03-19T20:59:56.094292173Z caller=main.go:181 module=dns_redacted_A target=ns1.redacted level=error msg="Probe failed" duration_seconds=9.500818867



Metrics that would have been returned:
# HELP probe_dns_additional_rrs Returns number of entries in the additional resource record list
# TYPE probe_dns_additional_rrs gauge
probe_dns_additional_rrs 0
# HELP probe_dns_answer_rrs Returns number of entries in the answer resource record list
# TYPE probe_dns_answer_rrs gauge
probe_dns_answer_rrs 0
# HELP probe_dns_authority_rrs Returns number of entries in the authority resource record list
# TYPE probe_dns_authority_rrs gauge
probe_dns_authority_rrs 0
# HELP probe_dns_duration_seconds Duration of DNS request by phase
# TYPE probe_dns_duration_seconds gauge
probe_dns_duration_seconds{phase="connect"} 4.5651e-05
probe_dns_duration_seconds{phase="request"} 9.495595939
probe_dns_duration_seconds{phase="resolve"} 0.005040202
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.005040202
# HELP probe_dns_query_succeeded Displays whether or not the query was executed successfully
# TYPE probe_dns_query_succeeded gauge
probe_dns_query_succeeded 0
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 9.500818867
# HELP probe_ip_addr_hash Specifies the hash of IP address. It's useful to detect if the IP address changes.
# TYPE probe_ip_addr_hash gauge
probe_ip_addr_hash 3.682327368e+09
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0



Module configuration:
prober: dns
timeout: 21s
http:
  ip_protocol_fallback: true
  follow_redirects: true
  enable_http2: true
tcp:
  ip_protocol_fallback: true
icmp:
  ip_protocol_fallback: true
  ttl: 64
dns:
  ip_protocol_fallback: true
  query_name: redacted
  query_type: A
  recursion_desired: true
  validate_answer_rrs:
    fail_if_not_matches_regexp:
    - <redacted>
```

### What did you expect to see?
See that the timeout is set to `21s` yet the prober times out after just `9.5s`
