### ISSUE TITLE
HTTPS going through TCP6

### ISSUE THREAD

**Issue by AnthonyWC** [prometheus/blackbox_exporter#105]
I see the thread here (https://github.com/prometheus/blackbox_exporter/issues/83) but still getting network not reachable, my blackbox is setup in docker-compose and I see error msg shows it is going through tcp6 which may be the issue?

Here's my setup:

```
scrape_configs:
  - job_name: 'website'
    metrics_path: /probe

    params:
      module: [http_2xx]

    static_configs:
      - targets:
        - prometheus.io

    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: https://${1}

      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}

      - target_label: __address__
        replacement: blackbox:9115
```

```
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: []
      method: GET
```

compose logs show:
```
blackbox_1             | time="2017-01-25T23:06:38Z" level=warning msg="Error for HTTP request to https://prometheus.io: Get https://prometheus.io: dial tcp6 [2400:cb00:2048:1::6818:783c
]:443: connect: network is unreachable" source="http.go:166" 
```

```
docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64
```

I can curl via https inside the blackbox exporter container:

```
/ # curl https://prometheus.io
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="An open-source monitoring system with a dimensional data model, flexible query language, efficient time series database and modern alerting approach."> 
...
```

**Comment by brian-brazil** [comment]
The blackbox exporter is preferring v6, so you either need to get your v6 working or to tell it to use v4 only.

**Comment by AnthonyWC** [comment]
Ok, so it did work after I added the tcp section to tcp4:

```
modules:
  http_2xx:
    prober: http
    timeout: 5s
    tcp:
      protocol: "tcp4"
```
But I noticed various weird behaviors:

under target, it shows state as up properly:

![image](https://cloud.githubusercontent.com/assets/6215805/22339303/7ba705a4-e3b7-11e6-8ce8-c624c6068cca.png)

But blackbox exporter page shows only 1 target:
![image](https://cloud.githubusercontent.com/assets/6215805/22339377/c5c2768c-e3b7-11e6-9d4a-0204d3e5b971.png)

If I click on it, shows it is v6 probe:

![image](https://cloud.githubusercontent.com/assets/6215805/22339580/71702b32-e3b8-11e6-8420-d9805be984b8.png)

If I modify the query and change the target to askubuntu.com it does show that it's using v4.

![image](https://cloud.githubusercontent.com/assets/6215805/22339560/611b4ef6-e3b8-11e6-87f2-8c9d457901ab.png)

Meanwhile I still see new log entries
`blackbox_1             | time="2017-01-26T16:14:29Z" level=warning msg="Error for HTTP request to https://prometheus.io: Get https://prometheus.io: dial tcp6 [2400:cb00:2048:1::6818:783c]:443: connect: network is unreachable" source="http.go:166" `

**Comment by brian-brazil** [comment]
askubuntu.com does not advertise a v6 address, so I'm guessing you didn't restart the exporter after changing the config.

**Comment by AnthonyWC** [comment]
I did the following after each changes:

```
docker-compose down
docker-compose build
docker-compose up
```

Saw that the file edit changes did get copy to the containers.

p.s. I am using named volume for my prometheus container, not sure if that'd possibly cause the issue:

    volumes:
      - prometheus_data:/prometheus

**Comment by AnthonyWC** [comment]
Other than deleting the named volume, is there anything else that I can try?  Also this behavior seems like it's a bug?

**Comment by AnthonyWC** [comment]
I just ended up deleting that target altogether, maybe it's a bug but it was for testing anyway.

**Comment by stefan2904** [comment]
"By default, the Docker server configures the container network for IPv4 only."

**Comment by luckenbach** [comment]
BTW any one else that runs into this issue make your http config look like this

```
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ipv4"
```

i had this exact issue when a site of mine went https behind a CDN; defaulted to ipv6 and had issues.
