### ISSUE TITLE
Add support for ignoring the HTTP status code or how to monitor SSL only

### ISSUE THREAD

**Issue by crisbal** [prometheus/blackbox_exporter#1064]
Hello. I have an use case in which I do not really care about the HTTP status code returned by some HTTP endpoints, but I just want to monitor that I get any reply and the value of `probe_ssl_earliest_cert_expiry`. 

I provide SSL certificates for these domains so I do not care about the content/logic of these domains. I just want to make sure they are up and running and with a valid SSL certificate.

I guess I could do something like:

```
modules:
  http_ssl_only_ignore_status_code:
    prober: http
    valid_status_codes: [100, 101, 102, 103, ..., 598, 599]
```

But I was wondering if there was a better solution that I didn't find. 

If there isn't, would there be any interest in adding a flag `ignore_status_code: boolean` to the configuration for `<http_probe>`? I could help with implementing that.

**Comment by danteu** [comment]
If the behavior of the HTTP server is irrelevant, you could use the tcp prober instead:
```yaml
modules:
  tls_connect:
    prober: tcp
    tcp:
      tls: true
```

```
$ curl 'localhost:9115/probe?target=github.com:443&module=tls_connect'
[...]
probe_ssl_earliest_cert_expiry 1.710460799e+09
[...]
```
