### ISSUE TITLE
Actual HTTP request is made after timeout is declared

### ISSUE THREAD

**Issue by sandersaares** [prometheus/blackbox_exporter#110]
I have blackbox doing a very simple HTTP check:

```
modules:
  basic_http_get:
    prober: http
    timeout: 5s
    http:
      method: GET
      preferred_ip_protocol: "ip4"
```

And Prometheus calls it using this config:

```
  - job_name: 'portus-token-api'
    metrics_path: /probe
    params:
      module: ['basic_http_get']
      target: ['https://admin-registry.axinom.com/v2/token']
    static_configs:
      - targets: ['omar:9115']
```

However, sometimes I find that blackbox indicates a timeout but actually does not even start to send out the HTTP request before the timeout happens!

In the log, I just see this:

```
time="2017-02-07T15:45:56Z" level=warning msg="Error for HTTP request to https://admin-registry.axinom.com/v2/token: Get https://admin-registry.axinom.com/v2/token: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" source="http.go:166"
```

I took a packet capture (attached below), which indicates some interesting things.

![image](https://cloud.githubusercontent.com/assets/9914262/22727400/679ac4e0-ede1-11e6-9c27-fce6eaf45ef5.png)

172.17.0.2 is blackbox_exporter. 172.17.0.1 is Prometheus (indirectly), 10.0.4.101 is the service being monitored by blackbox_exporter.

My analysis is:

* 52301 - Prometheus makes a request to blackbox.
* 5 seconds elapses with no meaningful network activity
* 52336 - blackbox says "I saw a timeout at 5s" to Prometheus
* 52348 - blackbox finally starts connecting to the service being monitored
* 52365 - TLS connection is established, yay! But instead of HTTP request, the connection is now directly closed by blackbox (presumably because a timeout occurred)

Raw data: [blackbox_capture.zip](https://github.com/prometheus/blackbox_exporter/files/759952/blackbox_capture.zip)

Blackbox is installed as a Docker container (latest image as of yesterday) on an Ubuntu 16.04 VM running on Hyper-V. I have not specified any extra command-line settings, just told it to use the configuration I pasted above.

Can you help me get it to make the requests reliably?
