### ISSUE TITLE
TLS prober?

### ISSUE THREAD

**Issue by javefang** [prometheus/blackbox_exporter#111]
Hi,

Is it possible to have a plain TLS prober? (without http)

I have a use-case where I'd like to monitor mongodb certificate expiry. Mongodb server allows TLS connection to port 27017 when SSL is enabled, but since this is not really a HTTPS endpoint, I can't use the http_2xx probe to check the endpoint. Does it make sense to have a new prober type "TLS" maybe?

(Currently I can check the certificate via "openssl s_client -connect <host>:27017")

Thanks,
Xinghong

**Comment by brian-brazil** [comment]
You can use the tcp module for this.

**Comment by javefang** [comment]
Could you provide an config example for that? I tried to use "tcp_connect" from the default config and it doesn't seem to check TLS.

**Comment by javefang** [comment]
Ah figured out

```
tcp_tls:
  prober: tcp
  timeout: 5s
  tcp:
    tls: true
    tls_config:
      insecure_skip_verify: false
```
