### ISSUE TITLE
Cannot find a way to have an alarm on expired certificates

### ISSUE THREAD

**Issue by JDA88** [prometheus/blackbox_exporter#1119]
### Host operating system: output of `uname -a`
Windows

### blackbox_exporter version: output of `blackbox_exporter --version`
0.24.0

### What is the blackbox.yml module config.
```
  http_tls_check_only_1:
    prober: http
    http:
      valid_status_codes: [200,401]
      preferred_ip_protocol: ip4
      method: GET
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: true
  http_tls_check_only_1:
    prober: http
    http:
      valid_status_codes: [200,401]
      preferred_ip_protocol: ip4
      method: GET
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
```

### What did you do that produced an error?
No matter what `insecure_skip_verify` option I use if the target certificate is expired the ssl related metrics are not present, `probe_ssl_last_chain_expiry_timestamp_seconds` etc.

### What did you expect to see?
A way to differentiate a site not responding from a site with an expired certificate.

### What did you see instead?
I have an alarm for certificate that will expire “soon” but as soon as the certificate is expired it doesn’t work anymore.

I don’t mind the probe failing on expired certificate, but when the probe is failing with `tls: failed to verify certificate: x509: certificate has expired or is not yet valid` the metrics with the time stamps should still be present. That will allow to have alerts with message like “_certificate expires x days ago_”

Another option could also be a new `probe_failed_due_to_expired_certificate` metric
