### ISSUE TITLE
Allow host header and target path to be set as query parameter for automatically probing services in Kubernetes

### ISSUE THREAD

**Issue by JorritSalverda** [prometheus/blackbox_exporter#113]
When running blackbox exporter, and using prometheus with kubernetes service discovery I cannot set the host header for each service to match the certificate I use on port 443, nor can I set the path to probe.

It would be very useful, because I can then add to following annotations to a service:

```
prometheus.io/probe: "true"
prometheus.io/host: "mysvc.domain.com"
prometheus.io/path: "/status"
```

And pass those as query params when calling the /probe endpoint by using the following Prometheus config (if I'm not mistaken):

```
relabel_configs:
- source_labels: [__address__]
  target_label: __param_target
- source_labels: [__meta_kubernetes_service_annotation_prometheus_io_host]
  target_label: __param_host
- source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
  target_label: __param_path
```

Is there an alternative to do this without resorting to a fully static config?

**Comment by brian-brazil** [comment]
We don't accept feature requests of this nature, as it's against the design philosophy of Prometheus and also not sane when you consider how many different options people want to tweak.

Generating the blackbox config is recommended.

**Comment by JorritSalverda** [comment]
Okay that's understandable. Although it makes the blackbox exporter example in https://github.com/prometheus/prometheus/blob/master/documentation/examples/prometheus-kubernetes.yml seem quite pointless :)

Do you happen to know of anyone that blogged about or has an open source example of how to generate the blackbox exporter config by using the information in Kubernetes service discovery?

**Comment by brian-brazil** [comment]
It works fine if the service on the other end doesn't mandate a specific host header.

I'm not aware of one of those.

**Comment by JorritSalverda** [comment]
For others that might experience a similar challenge, I've managed the probe any path in a service by adding the following made up annotation to the probed service:

```
annotations:
  prometheus.io/probe: "true"
  prometheus.io/probe-path: "/public/img/grafana_icon.svg"
```

And changing the prometheus config as follows:

```
- job_name: 'kubernetes-services'

  metrics_path: /probe
  params:
    module: [http_2xx]

  kubernetes_sd_configs:
  - role: service

  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_probe]
    action: keep
    regex: true
  - source_labels: [__address__]
    regex: (.*?)(:80)
    target_label: __param_target
    replacement: http://${1}
  - source_labels: [__address__]
    regex: (.*?)(:443)
    target_label: __param_target
    replacement: https://${1}
  - source_labels: [__param_target,__meta_kubernetes_service_annotation_prometheus_io_probe_path]
    separator: ';'
    regex: (.*?);(.*?)
    target_label: __param_target
    replacement: ${1}${2}
  - target_label: __address__
    replacement: blackbox-exporter
  - source_labels: [__param_target]
    target_label: instance
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_service_name]
    target_label: kubernetes_name

```

Make sure to set `replacement: blackbox-exporter` to the service name you use for your blackbox exporter. And do note this skips any other port than 80 and 443.

Prometheus then finds the following endpoints to scrape, exactly like I wanted:

```
http://blackbox-exporter:80/probe
module="http_2xx"
target="http://grafana.monitoring.svc/public/img/grafana_icon.svg"

http://blackbox-exporter:80/probe
module="http_2xx"
target="https://grafana.monitoring.svc/public/img/grafana_icon.svg"
```

For blackbox exporter itself I use the following config to skip the ssl certificate check, to avoid any issues with the host name not matching (we generate them with letsencrypt which doesn't allow internal names to be added to the certificate).

```
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: []
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      protocol: tcp
      preferred_ip_protocol: ip4
      tls_config:
        insecure_skip_verify: true
```
