### ISSUE TITLE
--web.route-prefix not functioning correctly.

### ISSUE THREAD

**Issue by csotiistvan** [prometheus/blackbox_exporter#1147]
### Host operating system: output of `uname -a`

Deployed in Azure AKS through Terraform `helm_release`

Linux blackbox-55cd4f7ff7-xrk2q 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter --version`

blackbox_exporter, version 0.24.0 (branch: HEAD, revision: 0b0467473916fd9e8526e2635c2a0b1c56011dff)
  go version:       go1.20.4
  platform:         linux/amd64

### What did you do that produced an error?

When deploying from the (official helm chart)[https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-blackbox-exporter] and specifying a web route prefix, the container goes into a crashloop and logs don't contain anything helpful, even when debug level logging is enabled. Other extra arguments (like `--log.level=debug`) work as expected. Attempted to use below configurations, with and without trailing `/`:

```
extraArgs:
  - --web.route-prefix=/blackbox

result: crashloop

extraArgs:
  - --web.route-prefix=/blackbox
  - --web.external-url=https://example.switzerlandnorth.cloudapp.azure.com/blackbox
  
result: crashloop

extraArgs:
  - --web.external-url=https://example.switzerlandnorth.cloudapp.azure.com/blackbox
  
result: crashloop

extraArgs:
  - --web.route-prefix=/
  - --web.external-url=https://example.switzerlandnorth.cloudapp.azure.com/blackbox

result: pod starts normally, but links are generated on the web GUI don't have the prefix. 
```
Changing the `path:` values in the `serviceMonitor` did not work either.

Ingress configuration:

```
ingress:
  enabled: true
  className: "nginx"
  labels: {}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: example.switzerlandnorth.cloudapp.azure.com
      paths:
        - path: /blackbox
          pathType: Prefix
  tls:
    - hosts:
        - example.switzerlandnorth.cloudapp.azure.com
      secretName: "blackbox-ingress-tls"
```
 
Tested a lot of different ingress annotations, but none affected the issue.
 
### What did you expect to see?

Specifying the`-- web.route-prefix` as anything but `/` should not cause a crashloop, should instead result in the links on the web GUI being generated with the prefix included (eg.<external-url>/blackbox/metrics instead of <external-url>/metrics, when `-- web.route-prefix=/blackbox` is specified).

### What did you see instead?

Pods can't start normally when the `--web.route-prefix` is anything but `/`. I can see in the logs (debug log level) that the arguments are set for the web route and prefix, but if anything but `/` is specified the pod is terminated with `Received SIGTERM, exiting gracefully`. No reason for the termination is visible in the logs.

Probes still work fine and all the links are correct when the service is port-forwarded out.

Anyone have an idea why this is not functioning as expected?
