### ISSUE TITLE
Feature request: add possibility to define discoveries consumed by prometheus

### ISSUE THREAD

**Issue by lufik** [prometheus/blackbox_exporter#1161]
I would like to propose the ability to blackbox_exporter to provide also list of scrapes to prometheus.
So the admin of blackbox machine can propose also scrapes and not only modules.

### What will be the blackbox.yml module config.
This could be added into blackbox.yml, where files contains only the list under configs (and can be generated).
```
discovery:
  files:
  - <fileglob>
  configs:
  - module: http_2xx
    targets:
    - <host/url>
```
### What will be the prometheus.yml scrape config.
```
- job_name: "exported-blackbox-probes"
  http_sd_configs:
  - url: http://prometheus-blackbox-exporter:9115/discovery
```

I try to create v1 implementation so we can easier discuss about it: #1160
