### ISSUE TITLE
source_ip_address option enhancement

### ISSUE THREAD

**Issue by thatsdone** [prometheus/blackbox_exporter#1196]
This is a kind of suggestion (or maybe an weak feature request).

Now we have 'source_ip_address' option for various probers.
I think it's useful to add a configration option to (at least ICMP) prober
allowing to specify interface name like '-I' option of ping.
For other applications, it's like '--interface' option of curl ,or '-B' option of ssh etc.

One of use cases is like this.
I'm working on 5G mobile networking stack, and there,
IP address(es) assigned to UE (User Equipment, simply speaking, smartphone)
change dynamically along with location of the UE.
In addition, a 5GS UE can have multiple slices. A slice is normally mapped to independent
L3(/L2) network, meaning tunnel(/tap) device.

Here, in order to monitor per slice connectivity, it's not convenient
using a predefined source_ip_address, but if we can have an option 
to specify source interface like below, we can eliminate reconfigure & restart
blackbox_exporter.

https://github.com/prometheus/blackbox_exporter/blob/master/example.yml#L144

```yaml
  icmp_example:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
      #source_ip_address: "127.0.0.1"
      source_interface: "tun0"  <== possible new option
```

I hope this makes (some?) sense.
Regards,
Masanori
