### ISSUE TITLE
Problem with getting metrics from tcp port

### ISSUE THREAD

**Issue by ildarmf** [prometheus/blackbox_exporter#125]
```
scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /api/v2/ping
    params:
      module: [tcp_7499]  
    static_configs:
      - targets:
        - af-dev.cybertonica.aws   # Target to probe
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:7499)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: xxx.xxx.aws:7499  # Blackbox exporter.
```

My app output: "pong" 
ERROR: text format parsing error in line 1: unexpected end of input stream

How I can getting status tcp port ? up/down
Is this module works with http?
