### ISSUE TITLE
http authorization header

### ISSUE THREAD

**Issue by tbouvet** [prometheus/blackbox_exporter#130]
Is it possible to receive the http authorization header from Prometheus configuration ?

I explain: I have a prometheus configuration:
```
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
        - "/etc/prometheus/blackbox/*.json"
  
    relabel_configs:
    - source_labels: [http_module]
      regex: (.*)
      target_label: __param_module
      replacement: ${1}    
    - source_labels: [__address__]
      regex: (.*)
      target_label: __param_target
      replacement: ${1}
    - source_labels: [__address__]
      regex: (.*)
      target_label: instance
      replacement: ${1}
    - source_labels: []
      regex: .*
      target_label: __address__
      replacement: blackbox:9115 # Blackbox exporter.
```

And I need to send the user/password authentication to blackbox (because it's different for each target).

So is it possible to do ?

Thanks
