### ISSUE TITLE
Possible to relabel source labels -> Header ?

### ISSUE THREAD

**Issue by dimitertodorov** [prometheus/blackbox_exporter#131]
Hi,

So I want to be able to pass in dynamic values for headers.
What is the best way to achieve this.
I know how to relabel single module params, how would I do this with headers.

Module Config
```
http_torca:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: [200]  # Defaults to 2xx
      method: GET
      headers:
        Accept-Language: en-US
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
```

Then I have a target group mapping file like this:
```
- targets:
  - https://service.local.intranet:10443/torca/api/v3/info
  labels:
    token: 946775b58bcc47ed6ed9cad0bedbc995b370dcdd75925e1d1fb8b2e522e03a22
```
