### ISSUE TITLE
Feature Request: Support Different Proxies for Individual Targets

### ISSUE THREAD

**Issue by nirmal20081028** [prometheus/blackbox_exporter#1310]
We have a requirement to use different proxy URLs for different targets. Since each target has its own proxy URL, creating multiple scrape jobs based on different proxy URLs is not feasible. We aim to create a single job where both the target and the proxy URL can be passed dynamically.

**Comment by mazzz1y** [comment]
This is not directly related to blackbox, and it can be resolved by using Prometheus relabeling.

Example:
```yaml
  - job_name: "blackbox"
    metrics_path: /probe
    labels:
    static_configs:
      - targets: [connectivitycheck.gstatic.com/generate_204]
        labels:
          module: http
      - targets: [connectivitycheck.gstatic.com/generate_204]
        labels:
          module: http_with_proxy
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: url
      - target_label: __address__
        replacement: blackbox-exporter:9115
```
