### ISSUE TITLE
blackbox_exporter failing on using client SSL cert

### ISSUE THREAD

**Issue by piersf** [prometheus/blackbox_exporter#132]
Hello there,

I've been trying (without success so far) to use the blackbox_exporter to monitor certain URL's that require a client certificate in order for them to be accessed.

I have the below job configuration in prometheus.yml file:

```
  - job_name: 'sites-client-ssl-cert'
    metrics_path: /probe
    params:
      module: [http_2xx_client]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://some-target-url
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .* 
        target_label: __address__
        replacement: 127.0.0.1:9115  # Blackbox exporter.
```

In the configuration file of blackbox_exporter i have define the below module which i am using in the above configuration:

```
http_2xx_client:
  prober: http
  timeout: 5s
  http:
    valid_status_codes: [200,302,301]  # Defaults to 2xx
    method: GET
    no_follow_redirects: false
    fail_if_ssl: false
    #fail_if_not_ssl: false
    #fail_if_matches_regexp:
    #  - "Could not connect to database"
    #fail_if_not_matches_regexp:
    #  - "Download the latest version here"
    #protocol: "tcp" # accepts "tcp/tcp4/tcp6", defaults to "tcp"
    #preferred_ip_protocol: "ip4" # used for "tcp", defaults to "ip6"
    tls: true
    tls_config:
      ca_file: /path/to/cert/certCA.pem
      cert_file: /path/to/cert/clientCert.pem
      key_file: /path/to/cert/clientKey.key
      insecure_skip_verify: true
```

After restarting both the blackbox_exporter and prometheus, i can see that in the page **http://prometheus-host:9090/targets** the endpoint of the above job reports that is UP.
But when scraping for **probe_http_status_code{job="sites-client-ssl-cert"}** in the Query page of prometheus, the value is 0.

After investigating, i can see that in the blackbox_exporter logs there is an handshake error being thrown:
`Mar 30 08:58:55 <PROMETHEUS_HOST> prometheus-blackbox-exporter[32578]: time="2017-03-30T08:58:55+02:00" level=warning msg="Error for HTTP 
request to https://some-target-url: Get https://some-target-url: remote error: handshake failure" sou
rce="http.go:97"`

When i curl the target URL with curl providing the client cert, key and the CA cert, it works fine without any issues. 
But seems like blackbox exporter is having a problem.

Is there anything wrong with my above configuration?
Is it even supported what i am trying to achieve ?

Thank you in advance!
Pier
