### ISSUE TITLE
error parsing config file: yaml: unmarshal errors:\n  line 14: field follow_redirects not found

### ISSUE THREAD

**Issue by jerome2710** [prometheus/blackbox_exporter#1348]
### Host operating system: output of `uname -a`
`Linux 5.10.0-32-cloud-amd64 #1 SMP Debian 5.10.223-1 (2024-08-10) x86_64 GNU/Linux`

### blackbox_exporter version: output of `blackbox_exporter --version`
```
blackbox_exporter, version 0.17.0 (branch: HEAD, revision: 1bc768014cf6815f7e9d694e0292e77dd10f3235)
  build user:       root@626fb3899f41
  build date:       20200619-11:54:41
  go version:       go1.14.4
```

### What is the blackbox.yml module config.
```
---
modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      valid_http_versions:
      - HTTP/1.1
      - HTTP/2.0
      valid_status_codes: []
      method: GET
      headers:
        X-Pinger: blackbox-exporter
      follow_redirects: false
      fail_if_not_ssl: true
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
```

### What logging output did you get from adding `&debug=true` to the probe URL?
```
curl: (7) Failed to connect to localhost port 9115: Connection refused
```

### What did you do that produced an error?
I just installed blackbox_exporter with a simple config. Although described, `follow_redirects` does not seem to be a valid option. When removing this setting, blackbox_exporter does start.

### What did you expect to see?
blackbox_exporter active

### What did you see instead?
blackbox_exporter failed

```
service blackbox_exporter status

blackbox_exporter[1202181]: level=info ts=2024-12-31T13:45:55.442Z caller=main.go:212 msg="Starting blackbox_exporter" version="(version=0.17.0, branch=HEAD, revision=1bc768014cf6815f7e9d694e0292e77dd10f3235)"
blackbox_exporter[1202181]: level=info ts=2024-12-31T13:45:55.442Z caller=main.go:213 msg="Build context" (gogo1.14.4,userroot@626fb3899f41,date20200619-11:54:41)=(MISSING)
blackbox_exporter[1202181]: level=error ts=2024-12-31T13:45:55.443Z caller=main.go:216 msg="Error loading config" err="error parsing config file: yaml: unmarshal errors:\n  line 14: field follow_redirects not found >
systemd[1]: blackbox_exporter.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: blackbox_exporter.service: Failed with result 'exit-code'.
```
