### ISSUE TITLE
failed to add header "Content-Length" for httpProber 

### ISSUE THREAD

**Issue by weize07** [prometheus/blackbox_exporter#137]
**blackbox.yml**

```
http_xxx:
      prober: http
      timeout: 5s
      http:
        valid_status_codes: [200]
        method: POST
        headers:
          Content-Type: application/json;charset=UTF-8
          Content-Length: 100
          Transfer-Encoding: identity
          Accept: 'application/json, text/plain, */*'
        body: "{}"
```

**headers received by testing server:**

```
'Host' => 'xxx',
  'User-Agent' => 'xxxx',
  'Transfer-Encoding' => 'chunked',
  'Content-Type' => 'application/json',
  'Accept-Encoding' => 'gzip',
  'Connection' => 'close',
```
