### ISSUE TITLE
Monitor each IP after dns resolution

### ISSUE THREAD

**Issue by pragya-nayak** [prometheus/blackbox_exporter#1378]
Hello,

I want to monitor each IPs after DNS resolution same as live environment. For example: DNS https://www.example.com will either resolves to 1.2.3.4 or 1.2.3.5. Will blackbox exporter can be configured in a way that I can monitor metrics for each IP like how much total time example.com took when it resolves to 1.2.3.4 and same for 1.2.3.5.

Can anyone please share your suggestion.

**Comment by britcey** [comment]
You'll get a probe_ip_addr_hash metric that will change depending on what you resolved to, but you may be looking for `dns_sd_config`, which will let you specify a DNS entry and resolve the individual IPs:

https://prometheus.io/docs/prometheus/latest/configuration/configuration/#dns_sd_config

e.g., something like:
```
- job_name: www.example.com
  params:
    module: [http_2xx]
  dns_sd_configs:
    - names:
      - ws.example.com
      type: 'A'
      port: 443
  relabel_configs:
    - source_labels: [__address__]
      target_label: instance
    - source_labels: [__address__]
      regex: (.*)
      target_label: __param_target
      replacement: https://${1}/
    - target_label: __address__
      replacement: 127.0.0.1:9115
```

Note this is not blackbox-specific.
