### ISSUE TITLE
Unable to verify self-signed certificate

### ISSUE THREAD

**Issue by pichouk** [prometheus/blackbox_exporter#1389]
Hi,
I run Blackbox exporter version `0.26.0` in Kubernetes (GKE) deployed with `prometheus-blackbox-exporter` Helm chart version `9.3.0`. I got a bunch of targets and one of them is to monitor the HTTPS endpoint of a server I am running in the private network, with a self-signed certificate (server is supposed to return 401.

I created this module in `/config/blackbox.yaml `

```yaml
modules:
  http_401_with_cert:
    http:
      fail_if_not_ssl: false
      fail_if_ssl: false
      method: GET
      tls_config:
        ca_file: /etc/blackbox/tls/ca.crt
        insecure_skip_verify: false
      valid_http_versions:
      - HTTP/1.1
      - HTTP/2
      valid_status_codes:
      - 401
    prober: http
    timeout: 5s
```

File `/etc/blackbox/tls/ca.crt` contains the CA certificate chain used by the server.

When I query the blackbox exporter for my endpoint with `/probe?module=http_401_with_cert&target=https://my.server.private:10214` I always have this error in the log :

```
Error for HTTP request" module=http_401_with_cert target=https://my.server.private:10214 err="Get \"https://10.123.10.4:10214\": tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match my.server.private"
```

And I don't get any metrics regarding SSL expiry.

I double-checked, the `ca.crt` file is correct, I copied it and used it with curl (in another Pod since I can't curl in busybox) :

```
$ curl --cacert ca.crt https://my.server.private:10214
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
```

Am I missing something ? `ca_file` option purpose is for this use case of  self-signed certificate right ? Maybe the Busybox-based container image for Blackbox exporter is requiring something in order to validate self-signed certificate ?
