### ISSUE TITLE
remote error: tls: handshake failure on 0.26 blackbox version

### ISSUE THREAD

**Issue by winadm87** [prometheus/blackbox_exporter#1390]
### Host operating system: output of uname -a

host
Linux prometheus-test 5.4.0-173-generic #191-Ubuntu SMP Fri Feb 2 13:55:07 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

blackbox_exporter docker image version
Linux 29fc4bce5371 5.4.0-173-generic #191-Ubuntu SMP Fri Feb 2 13:55:07 UTC 2024 x86_64 GNU/Linux

### blackbox_exporter version: output of blackbox_exporter --version

```
 blackbox_exporter --version
blackbox_exporter, version 0.26.0 (branch: HEAD, revision: 444e3d089ae1aeeed385712ef84a5fa4f0c083ec)
  build user:       root@87341586bc85
  build date:       20250226-12:29:43
  go version:       go1.23.6
  platform:         linux/amd64
  tags:             unknown
```

### What is the blackbox.yml module config.

```
modules:
    http_2xx_no_verify:
        prober: http
        http:
            valid_status_codes:
                - 200
            preferred_ip_protocol: ip4
            ip_protocol_fallback: true
            tls_config:
                insecure_skip_verify: true
            follow_redirects: true
            enable_http2: true
        tcp:
            ip_protocol_fallback: true
        icmp:
            ip_protocol_fallback: true
            ttl: 64
        dns:
            ip_protocol_fallback: true
            recursion_desired: true
    http_2xx_no_verify_tls10:
        prober: http
        http:
            valid_status_codes:
                - 200
            preferred_ip_protocol: ip4
            ip_protocol_fallback: true
            tls_config:
                insecure_skip_verify: true
                min_version: TLS10
            follow_redirects: true
            enable_http2: true
        tcp:
            ip_protocol_fallback: true
        icmp:
            ip_protocol_fallback: true
            ttl: 64
        dns:
            ip_protocol_fallback: true
            recursion_desired: true
```

### What is the prometheus.yml scrape config.

N/A

### What logging output did you get from adding &debug=true to the probe URL?

```
Logs for the probe:
time=2025-03-27T04:08:20.873Z level=ERROR source=http.go:474 msg="Error for HTTP request" module=http_2xx_no_verify target=https://rmm-server.example.com/ err="Get \"https://172.10.10.10/\": remote error: tls: handshake failure"
time=2025-03-27T04:08:20.873Z level=ERROR source=handler.go:135 msg="Probe failed" module=http_2xx_no_verify target=https://rmm-server.example.com/ duration_seconds=0.152853992
```

### What did you do that produced an error?

Request a target with custom module and debug switch

### What did you expect to see?

Probe success

### What did you see instead?

Probe failure with tls: handshake failure

### Additional info

We have a branch of servers with RMM interfaces with self-signed and internally signed certificates. We have successfully monitored these servers with v0.23 of blackbox exporter. But when we have updated the exporter version to v0.26 - the checks for servers with TLS1.2 started to fail. We have downgraded the version of exporter to v0.25 - and blackbox checks starts to work properly again.
At the same time we have a branch of checks to some another services (not RMM on servers) that uses TLS1.2 - and they are successfully scrapped on v0.23, v0.25 and v0.26.
So, at the moment, we are a little stuck in trying to understand what has changed in v0.26 that led to this error.
