### ISSUE TITLE
HTTP check and reverse proxy

### ISSUE THREAD

**Issue by nick-idnow** [prometheus/blackbox_exporter#140]
Hi all, 

I'm trying to setup a simple http check for my app application which is running behind reverse proxy (nginx), the configuration files are: 

**prometheus.yml**
```
global:
  scrape_interval:     1s 
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'site_check'
    metrics_path: /probe
    params:
      module: [http_ok]
      target: ['http://my-app-behind-nginx.com/health']
    static_configs:
      - targets:
        - 'localhost:9115' 
```

**blackbox.yml**
```
modules:
  http_ok:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_status_codes: [200]
```
So far so good, prometheus says the target is up. Then, I stop my app, nginx is still running and prometheus shows me that the app is running as well, but it's actually down. Nginx responds with 502, logs and ChromeDevTools confirm this. The question is why Prometheus still considers the target is still running?

Thanks!

Versions:
`prometheus (version=1.6.1, branch=master, revision=4666df502c0e239ed4aa1d80abbbfb54f61b23c3)`

`blackbox_exporter (version=0.4.0, branch=master, revision=be7a4226ed32a6407d7895ee5a0bd892f0f34692)`

Regards,
Nick
