### ISSUE TITLE
incorrect state

### ISSUE THREAD

**Issue by hiscal2015** [prometheus/blackbox_exporter#152]
Hi, 

I have a website actually down but still showing up in prometheus, I can't find where's the problem

Here's part of my blackbox config (version 0.5.0):
```
modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: [200,401]  # Defaults to 2xx
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true
      protocol: "tcp" # accepts "tcp/tcp4/tcp6", defaults to "tcp"
      preferred_ip_protocol: "ip4" # used for "tcp", defaults to "ip4"
```

Prometheus config:
```
  - job_name: 'blackbox'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - 'https://test.demo.com'
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: monitor.demo.com:9115  # Blackbox exporter.
```

curl metrics:
```
curl http://monitor.demo.com:9115/probe?target="https://test.demo.com"&module="http_2xx"
[1] 5114
probe_ip_protocol 4
probe_ssl_earliest_cert_expiry 1526601599.000000
probe_http_status_code 502
probe_http_content_length 173
probe_http_redirects 0
probe_http_ssl 1
probe_duration_seconds 0.006728
probe_success 0

```

my valid_status_codes: [200,401] , but got 502 by probe, and probe_success is 0, why state is still up?

![blackbox](https://cloud.githubusercontent.com/assets/15604715/26140157/b82fa9de-3b07-11e7-8d62-e47d7ca7e140.jpg)
