### ISSUE TITLE
probe_success fails with https only site

### ISSUE THREAD

**Issue by kaihendry** [prometheus/blackbox_exporter#159]
I have a test site, letterly.com that only responds on https://letterly.com

I tried updating the regex from :80 to :443. Same issue.

```
  - job_name: 'bb'
    scrape_interval: 5m
    scrape_timeout: 10s
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    file_sd_configs:
      - files:
        - /etc/prometheus/targets.yml
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:443)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: blackboxprober:9115  # Blackbox exporter.
```

So I'm incorrectly getting probe_success 0 https://prom.dabase.com/graph?g0.range_input=2h&g0.expr=probe_success&g0.tab=0

**Comment by SuperQ** [comment]
Without the contents of the targets.yml, it's not possible to debug the problem.

**Comment by kaihendry** [comment]
Here you go: https://github.com/kaihendry/pingprom/blob/master/prometheus/targets.yml

**Comment by SuperQ** [comment]
In order to use https with bare target hostnames, you need to specify the protocol as `https`.  The default assumes `http`.

Either prefix the targets like `https://natalian.org`, or adjust the replacement in the target label like this:

```
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:443)?
        target_label: __param_target
        replacement: "https://${1}"
```
