### ISSUE TITLE
How to troubleshoot downtime?

### ISSUE THREAD

**Issue by nafg** [prometheus/blackbox_exporter#172]
Hi, apologies if this is the wrong place to ask for help, if so please direct me.

I'm getting a lot of alerts of downtime, however I don't know how to interpret it or how to dig deeper.

Here is my setup:

blockbox.yml
```
        modules:
          http:
            prober: http
            timeout: 15s
```

prometheus.rules:
```
...
        ALERT service_down
        IF probe_success == 0
        FOR 5m
```

prometheus.yml:
```
...
  - job_name: 'blackbox-exporter'
    metrics_path: /probe
    scrape_interval: 1m
    params:
      module: ['http']
    static_configs:
      - targets:                             # targets to be tested by the blackbox exporter
          - https://domain1.com/
          - https://domain2.com/
    relabel_configs:
          - source_labels: [__address__]     # set param 'target' to the original target
            regex: (.*)
            target_label: __param_target
            replacement: ${1}
          - source_labels: [__param_target]  # set label 'instance' to it as well
            regex: (.*)
            target_label: instance
            replacement: ${1}
          - source_labels: []                # set __address__ to the blackbox exporter
            regex: .*
            target_label: __address__
            replacement: blackbox_exporter:9115
...
```

I keep getting alerted about "domain1.com". However I never observe an actual issue with it. Where do I go from here?

Thanks.
