### ISSUE TITLE
Label example for IPs?

### ISSUE THREAD

**Issue by kaihendry** [prometheus/blackbox_exporter#196]
Hi, I have a configuration like so that is testing my internet connectivity at various different locations.

```
  - job_name: 'blackbox-icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 217.169.1.2
        - 202.83.1.2
        - 202.83.1.2
        - 203.109.1.2
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackboxprober:9115  # Blackbox exporter.
```
These domains don't have proper reverse DNS names, so how would I go about labelling them so I know say `202.83.1.2` refers to home? Split them up into individual jobs & rely on `job_name`?
