### ISSUE TITLE
HTTPS prober started failing with 0.9.0

### ISSUE THREAD

**Issue by stapelberg** [prometheus/blackbox_exporter#234]
cc @thz @brian-brazil 

### Host operating system: output of `uname -a`

```
Linux alp 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux
```

### blackbox_exporter version: output of `blackbox_exporter -version`

```
blackbox_exporter, version 0.9.0 (branch: HEAD, revision: 97d988e82930a5f034a8e3077eee7b2151462162)
  build user:       root@fb7cad74d9b2
  build date:       20170920-13:51:08
  go version:       go1.8.3
```

### What is the blackbox.yml module config.

```
modules:                                                                                        
  ssl_expiry:                                                                                   
    prober: http                                                                                
    timeout: 5s                                                                                 
    http:                                                                                       
      valid_status_codes: [401]                                                                 
      fail_if_ssl: false                                                                        
      fail_if_not_ssl: false                                                                    
      tls_config:                                                                               
        insecure_skip_verify: false                                                             
      preferred_ip_protocol: "ip4"                                                              
```

### What is the prometheus.yml scrape config.

```
- job_name: ssl_expiry_google
  scrape_interval: 60s
  metrics_path: /probe
  params:
    module: [ssl_expiry]
    target: ['https://www.google.com']
  scheme: http
  static_configs:
  - targets:
    - blackbox-exporter:9115
```

### What logging output did you get from adding `&debug=true` to the probe URL?

```
Logs for the probe:
ts=2017-09-21T06:35:39.98606684Z caller=main.go:115 module=ssl_expiry target=https://www.google.com/ level=info msg="Beginning probe" probe=http timeout_seconds=4.5
ts=2017-09-21T06:35:39.986283746Z caller=utils.go:43 module=ssl_expiry target=https://www.google.com/ level=info msg="Resolving target address" preferred_ip_protocol=ip4
ts=2017-09-21T06:35:39.9873203Z caller=utils.go:63 module=ssl_expiry target=https://www.google.com/ level=info msg="Resolved target address" ip=172.217.16.196
ts=2017-09-21T06:35:39.987421411Z caller=http.go:186 module=ssl_expiry target=https://www.google.com/ level=info msg="Making HTTP request" url=https://[172.217.16.196]/ host=www.google.com
ts=2017-09-21T06:35:40.010237176Z caller=http.go:190 module=ssl_expiry target=https://www.google.com/ level=error msg="Error for HTTP request" err="Get https://[172.217.16.196]/: x509: cannot validate certificate for 172.217.16.196 because it doesn't contain any IP SANs"
ts=2017-09-21T06:35:40.010322932Z caller=main.go:128 module=ssl_expiry target=https://www.google.com/ level=error msg="Probe failed" duration_seconds=0.024178445



Metrics that would have been returned:
# HELP content_length Length of http content response
# TYPE content_length gauge
content_length 0
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 1.01e-07
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.024178445
# HELP probe_failed_due_to_regex Indicates if probe failed due to regex
# TYPE probe_failed_due_to_regex gauge
probe_failed_due_to_regex 0
# HELP probe_http_redirects The number of redirects
# TYPE probe_http_redirects gauge
probe_http_redirects 0
# HELP probe_http_ssl Indicates if SSL was used for the final redirect
# TYPE probe_http_ssl gauge
probe_http_ssl 0
# HELP probe_http_status_code Response HTTP status code
# TYPE probe_http_status_code gauge
probe_http_status_code 0
# HELP probe_http_version Returns the version of HTTP of the probe response
# TYPE probe_http_version gauge
probe_http_version 0
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0



Module configuration:
prober: http
timeout: 5s
http:
  valid_status_codes:
  - 401
  preferred_ip_protocol: ip4

```

### What did you do that produced an error?

Upgraded from blackbox-exporter 0.8.1 to blackbox-exporter 0.9.0.

### What did you expect to see?

No change.

### What did you see instead?

Alerts started firing.
