### ISSUE TITLE
blackbox_exporter 0.10.0 Memory Leak

### ISSUE THREAD

**Issue by edgarswed** [prometheus/blackbox_exporter#249]
### Host operating system: output of `uname -a`
`Linux exporter01-dev 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

### blackbox_exporter version: output of `blackbox_exporter -version`
```
blackbox_exporter, version 0.10.0 (branch: HEAD, revision: 75681e3c4f051e24269a132e8ec19517118e1586)
  build user:       root@0334aae810a6
  build date:       20171009-14:25:49
  go version:       go1.9.1
```

### What is the blackbox.yml module config.
```
modules:
    http_2xx:
        http:
            method: GET
            preferred_ip_protocol: ip4
        prober: http
        timeout: 5s
    https_2xx:
        http:
            fail_if_not_ssl: true
            fail_if_ssl: false
            method: GET
            preferred_ip_protocol: ip4
            tls_config:
                insecure_skip_verify: true
        prober: http
        timeout: 5s
```

### What is the prometheus.yml scrape config.
```
  - job_name: blackbox
    scrape_interval: 10s
    metrics_path: /probe
    static_configs:
      - targets:
        - http://internal.host/
    params:
      module:
      - http_2xx
    relabel_configs:
      -   source_labels:
          - __address__
          target_label: __param_target
      -   source_labels:
          - __param_target
          target_label: instance
      -   replacement: 10.10.10.10:9115
          target_label: __address__
    honor_labels: True

  - job_name: blackbox_https
    scrape_interval: 10s
    metrics_path: /probe
    static_configs:
      - targets:
        - https://internal1.host
        - https://internal2.host
        - https://internal3.host
        - https://internal4.host
    params:
      module:
      - https_2xx
    relabel_configs:
      -   source_labels:
          - __address__
          target_label: __param_target
      -   source_labels:
          - __param_target
          target_label: instance
      -   replacement: 10.10.10.10:9115
          target_label: __address__
    honor_labels: True
```
### What did you see instead?
On 15-Oct-2017 it was upgraded till version 0.10, but the memory leak still appears. Like in #236 #239
![blackbox-memory-leak](https://user-images.githubusercontent.com/6197876/31926224-eae24772-b895-11e7-9447-5f3a10b9c1f9.png)
