### ISSUE TITLE
HTTP Probes https url always returns not success (0)

### ISSUE THREAD

**Issue by iceycake** [prometheus/blackbox_exporter#258]
### Host operating system: output of `uname -a`
Tectonic 1.7

### blackbox_exporter version: output of `blackbox_exporter -version`
v0.10.0 within Docker Container

### What is the blackbox.yml module config.
```
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      headers:
        Host: vhost.example.com
        Accept-Languages: en-US
      method: GET
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: [200,302,301]
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: true
```

### What is the prometheus.yml scrape config.
```
 - job_name: 'blackbox_http_2xx'
      scrape_interval: 30s
      metrics_path: /probe
      params:
        module: [http_2xx]
      scheme: http
      static_configs:
        - targets:
          - https://www.google.com          
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: bb-exporter.default-ns.svc.cluster.local:80  # Blackbox exporter
```

### What logging output did you get from adding `&debug=true` to the probe URL?
n/a

### What did you do that produced an error?
Looks like i can't reproduce the problem by simply using `curl` from my mac. It only happens on k8s probling so far.

### What did you expect to see?
https://www.google.com should be a success (1) instead of failed (0).  Also, `probe_http_ssl` returns 0.

`probe_http_ssl{instance="https://www.google.com",job="blackbox_http_2xx"}` returns 0

### What did you see instead?
All https targets failed.
