### ISSUE TITLE
Confusing timeout behaviour

### ISSUE THREAD

**Issue by acdha** [prometheus/blackbox_exporter#259]
I was surprised by the behaviour of timeouts when troubleshooting an internal healthcheck for a very slow service with configuration like this:

```
    https_2xx:
        prober: http
        timeout: 15s
        http:
            fail_if_not_ssl: true
            preferred_ip_protocol: "ip4"
```

The first problem was that the timeout values are not applied by default:
```
$ curl 'http://localhost:9999/probe?module=https_2xx&target=https://example.org/very/slow/healthcheck'
…
probe_duration_seconds 9.500304772
```

Note that while the configuration specifies 15s the actual timeout was just under the default 10 seconds. Adding `-H X-Prometheus-Scrape-Timeout-Seconds:120` allows reaching the configured timeout:

```
probe_duration_seconds 14.500166973
```
