### ISSUE TITLE
headers: option is capitalizing custom string

### ISSUE THREAD

**Issue by wtip** [prometheus/blackbox_exporter#261]
### blackbox_exporter version: output of `blackbox_exporter -version`
```
blackbox_exporter, version 0.9.1 (branch: HEAD, revision: 2272b4e637a591168d5b24a3943e15ac15ecba80)
  build user:       root@27fc71dcd45b
  build date:       20170921-13:19:29
  go version:       go1.8.3
```

### What is the blackbox.yml module config.
```
modules:
  https_custom_2xx:
    prober: http
    http:
      headers:
        authId: demo
      preferred_ip_protocol: "ip4"
```
I expected a 200 response code from the application that I am probing but received a 400 code.
After doing a tcpdump of the traffic I discovered that the blackbox exporter is changing the case of the custom header that I need to send. It should be `authId: demo` but the exporter is transforming it to `AuthId: demo`.

`headers:` should maintain the case and not change it.
