### ISSUE TITLE
Not able to probe ipv6 services

### ISSUE THREAD

**Issue by AmrutaMohite** [prometheus/blackbox_exporter#271]
I have setup black-box exporter in the kubernetes cluster and I am trying to access the service url which is from outside the cluster, for ex: google.com.
But I am unable to get the probe metrics as it seems issue with the ipv6 protocol.
Blackbox targets are:
 {
   "targets": [ "google.com" ],
   "labels": {
       "job": "kubernetes-services",
       "namespace": "default"
   }
Prometheus Job configuration is:

```
- job_name: 'kubernetes-services'
  scheme: http
  metrics_path: /probe
  params:
    module: [http_2xx]
  file_sd_configs:
    - files:
      - /etc/prometheus/blackbox-targets.json
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
    replacement: ${1}
  - source_labels: [__param_target]
    regex: (.*)
    target_label: instance
    replacement: ${1}
  - source_labels: []
   regex: .*
   target_label: __address__
   replacement: mo-blackbox.mo-system:9115
```

Result when I curl:
Hostname was NOT found in DNS cache
Trying 100.71.72.221...
Connected to mo-blackbox.mo-system (100.71.72.221) port 9115 (#0)
GET /probe?target=google.com HTTP/1.1
User-Agent: curl/7.38.0
Host: mo-blackbox.mo-system:9115
Accept: /
< HTTP/1.1 200 OK
< Date: Thu, 07 Dec 2017 09:52:07 GMT
< Content-Length: 161
< Content-Type: text/plain; charset=utf-8
<
probe_ip_protocol 6
probe_http_status_code 0
probe_http_content_length 0
probe_http_redirects 0
probe_http_ssl 0
probe_duration_seconds 0.803343
probe_success 0

Blackbox.yml configurations are: 

```
modules:
  http_2xx:
    prober: http
    timeout: 5s
    tcp:
      protocol:tcp4
    http:
  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
```

what should be the correct way to monitor such services?
