### ISSUE TITLE
basic_auth is not working as expected

### ISSUE THREAD

**Issue by sree86** [prometheus/blackbox_exporter#274]
### Host operating system: output of `uname -a`
uname -a
Linux ip-10-75-30-178 4.4.51-40.58.amzn1.x86_64 #1 SMP Tue Feb 28 21:57:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`
Picked up from the docker image

Command used to run the container is given below:

docker run -p 9115:9115 -d -v `pwd`:/config prom/blackbox-exporter --config.file=/config/blackbox.yml

### What is the blackbox.yml module config.

```
  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [200,301]
      method: POST
      headers:
        Host: "dev.domain.com"
        Cache-Control: no-cache
        Content-Type: application/json
     basic_auth:
        username: 'username'
        password: 'password'
```

### What is the prometheus.yml scrape config.

```
  - job_name: 'blackbox_post'
    metrics_path: /probe
    params:
      module: [http_post_2xx]  
    static_configs:
      - targets:
        - https://dev.domain.com/login
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
```

### What logging output did you get from adding `&debug=true` to the probe URL?

```
ts=2017-12-14T06:10:37.824205794Z caller=main.go:174 module=http_post_2xx target=https://dev.domain.com/login level=debug msg="Beginning probe" probe=http timeout_seconds=4.5
ts=2017-12-14T06:10:37.824403306Z caller=main.go:174 module=http_post_2xx target=https://dev.domain.com/login level=debug msg="Resolving target address" preferred_ip_protocol=ip6
ts=2017-12-14T06:10:37.838208369Z caller=main.go:174 module=http_post_2xx target=https://dev.domain.com/login level=debug msg="Resolution with preferred IP protocol failed, attempting fallback protocol" fallback_protocol=ip4 err="address dev.domain.com: no suitable address found"
ts=2017-12-14T06:10:37.838704224Z caller=main.go:174 module=http_post_2xx target=https://dev.domain.com/login level=debug msg="Resolved target address" ip=54.228.11.715
ts=2017-12-14T06:10:37.838775099Z caller=main.go:174 module=http_post_2xx target=https://dev.domain.com/login level=debug msg="Making HTTP request" url=https://[54.228.11.715]/login host=dev.domain.com
ts=2017-12-14T06:10:37.853240222Z caller=main.go:174 module=http_post_2xx target=https://dev.domain.com/login level=debug msg="Received redirect" url=https://[54.228.11.715]/login/
ts=2017-12-14T06:10:37.865608459Z caller=main.go:174 module=http_post_2xx target=https://dev.domain.com/login level=debug msg="Received HTTP response" status_code=200
ts=2017-12-14T06:10:37.865737727Z caller=main.go:174 module=http_post_2xx target=https://dev.domain.com/login level=debug msg="Response timings for roundtrip" roundtrip=0 start=2017-12-14T06:10:37.838860727Z dnsDone=2017-12-14T06:10:37.838860727Z connectDone=2017-12-14T06:10:37.841451893Z gotConn=2017-12-14T06:10:37.847667361Z responseStart=2017-12-14T06:10:37.853089893Z end=2017-12-14T06:10:37.853192373Z
ts=2017-12-14T06:10:37.865818784Z caller=main.go:174 module=http_post_2xx target=https://dev.domain.com/login level=debug msg="Response timings for roundtrip" roundtrip=1 start=2017-12-14T06:10:37.853395763Z dnsDone=2017-12-14T06:10:37.853395763Z connectDone=2017-12-14T06:10:37.855136578Z gotConn=2017-12-14T06:10:37.860426114Z responseStart=2017-12-14T06:10:37.865533699Z end=2017-12-14T06:10:37.865567542Z
ts=2017-12-14T06:10:37.865928359Z caller=main.go:174 module=http_post_2xx target=https://dev.domain.com/login level=debug msg="Probe succeeded" duration_seconds=0.041669282
```

### What did you do that produced an error?
I have added wrong password and probe_success value is 1

### What did you expect to see?
This login should fail and probe_success value should be 0

### What did you see instead?
Probe succeeded
