### ISSUE TITLE
Redirected requests don't pass proper Host header

### ISSUE THREAD

**Issue by eliecharra** [prometheus/blackbox_exporter#275]
### Host operating system: 
Linux xxx 3.16.0-4-amd64 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

### blackbox_exporter version: 
docker image prom/blackbox-exporter:v0.10.0

### What is the blackbox.yml module config.

```yaml
modules:
  http:
    prober: http
    timeout: 5s
    http:
      headers:
        Accept: "*/*"
      preferred_ip_protocol: ip4
      tls_config:
        insecure_skip_verify: true
```

### What is the prometheus.yml scrape config.
```yaml
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http]  # Look for a HTTP response.
    static_configs:
      - targets: {{ prom_https_check|to_yaml }} #This template came from jinja 2, this is not prom related
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Blackbox exporter.
```

### What logging output did you get from adding `&debug=true` to the probe URL?
```yaml
ts=2017-12-15T16:03:12.279836699Z caller=main.go:116 module=http target=example.com level=info msg="Beginning probe" probe=http timeout_seconds=4.5
ts=2017-12-15T16:03:12.279996927Z caller=utils.go:43 module=http target=example.com level=info msg="Resolving target address" preferred_ip_protocol=ip4
ts=2017-12-15T16:03:12.366414511Z caller=utils.go:63 module=http target=example.com level=info msg="Resolved target address" ip=37.XXX.XXX.XXX
ts=2017-12-15T16:03:12.366477147Z caller=http.go:190 module=http target=example.com level=info msg="Making HTTP request" url=http://[37.XXX.XXX.XXX] host=example.com
ts=2017-12-15T16:03:12.43056398Z caller=http.go:150 module=http target=example.com level=info msg="Received redirect" url=http://[37.XXX.XXX.XXX]/fr
ts=2017-12-15T16:03:12.434590837Z caller=http.go:197 module=http target=example.com level=info msg="Received HTTP response" status_code=400
ts=2017-12-15T16:03:12.434630864Z caller=http.go:212 module=http target=example.com level=info msg="Invalid HTTP response status code, wanted 2xx" status_code=400
ts=2017-12-15T16:03:12.43466107Z caller=main.go:129 module=http target=example.com level=error msg="Probe failed" duration_seconds=0.15472163
```
### What did you do that produced an error?

When a redirect occurs, seems like blackbox exporter is not passing proper host header to second request, which generate a bad request response from server. Location header send by the first 302 response is good.

This capture was taken on the remote probed server :
![selection_442](https://user-images.githubusercontent.com/6154987/34050835-9b1ebc0c-e1bc-11e7-9789-889d4f939b4a.jpg)

### What did you expect to see?

200 as `probe_http_status_code` value

### What did you see instead?

400 as `probe_http_status_code` value

I found this hidden behaviour while digging around issue #90
