### ISSUE TITLE
HTTP client configuration isn't validated as expected

### ISSUE THREAD

**Issue by simonpasquier** [prometheus/blackbox_exporter#278]
### Host operating system: output of `uname -a`

Ubuntu 16.04

### blackbox_exporter version: output of `blackbox_exporter -version`

blackbox_exporter, version 0.11.0 (branch: master, revision: 200181ba84e595570eeed8cb1848491d3d4f85f0)
  build user:       pasquier-s@simon-trusty
  build date:       20171219-09:41:05
  go version:       go1.9.2

### What is the blackbox.yml module config.

```
modules:
  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
      bearer_token: foo
      bearer_token_file: foo
      basic_auth:
        username: "username"
        password: "mysecret"
```

### What is the prometheus.yml scrape config.

N/A

### What logging output did you get from adding `&debug=true` to the probe URL?

N/A

### What did you do that produced an error?

N/A

### What did you expect to see?

I expected that the blackbox exporter would reject the configuration because the module contains both `bearer_token` and `bearer_token_file`.

### What did you see instead?

The blackbox exporter didn't complain.

I've reproduced the problem with a unit test (see https://github.com/simonpasquier/blackbox_exporter/commit/17fb97295e808aa46d95b870b9c45c9b05ca08c1). The fix in the code of the blackbox exporter itself is fairly contained (see https://github.com/simonpasquier/blackbox_exporter/commit/1e9bed841ebc81ad20766be17a39dc80d2d55d5b) but it has implications on the prometheus/common/config package too (see https://github.com/simonpasquier/blackbox_exporter/commit/1e9bed841ebc81ad20766be17a39dc80d2d55d5b#diff-fbe65e96815b1559a386cd8521b5c79e) which are less trivial.
