### ISSUE TITLE
http: Accept error: accept tcp [::]:9115: accept4: too many open files

### ISSUE THREAD

**Issue by alvaroaleman** [prometheus/blackbox_exporter#288]
### Host operating system: output of `uname -a`

Linux <fqdn> 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`

```
blackbox_exporter, version 0.10.0 (branch: HEAD, revision: 75681e3c4f051e24269a132e8ec19517118e1586)
  build user:       root@0334aae810a6
  build date:       20171009-14:25:49
  go version:       go1.9.1
```

### What is the blackbox.yml module config.

```
modules:
  http_2xx_v4:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
  http_2xx_v6:
    prober: http
    http:
      preferred_ip_protocol: "ip6"
  http_2xx_ba_v4:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
      basic_auth:
        username: 'someuser'
        password: 'somepass'
  http_2xx_ba_v6:
    prober: http
    http:
      preferred_ip_protocol: "ip6"
      basic_auth:
        username: 'someuser'
        password: 'somepass'
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  icmp:
    prober: icmp
```

### What is the prometheus.yml scrape config.

```
    scrape_configs:
    - job_name: 'blackbox_v4'
      metrics_path: /probe
      params:
        module:
          - http_2xx_v4
      static_configs:
        - targets: 
            - https://list
            - https://of
            - https://hosts
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 'blackbox_exporter_host:9115'
    - job_name: 'blackbox_v6'
      metrics_path: /probe
      params:
        module:
          - http_2xx_v6
      static_configs:
        - targets:
            - https://some
            - https://hosts
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 'blackbox_exporter_host:9115'
    - job_name: 'blackbox_ba_v4'
      metrics_path: /probe
      params:
        module:
          - http_2xx_ba_v4
      static_configs:
        - targets:
          - https://some
          - https://hosts
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 'blackbox_exporter_host:9115'
    - job_name: 'blackbox_ba_v6'
      metrics_path: /probe
      params:
        module:
          - http_2xx_ba_v6
      static_configs:
        - targets:
          - https://some
          - https://hosts
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 'blackbox_exporter_host:9115'
    - job_name: 'blackbox_ssh_v6'
      metrics_path: /probe
      params:
        module:
          - ssh_banner
      static_configs:
        - targets:
            - 'ahost:2222'
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 'blackbox_exporter_host:9115'
```

### What did you do that produced an error?

Run the blackbox_exporter for about 50 days

### What did you expect to see?

No errors

### What did you see instead?

`http: Accept error: accept tcp [::]:9115: accept4: too many open files; retrying in 1s`

Restarting the blackbox_exporter fixes the issue, however that is not a real solution. Maybe noteworthy is that my Prometheus scrapes the blackbox_exporter via an IPv6 address.

**Comment by brian-brazil** [comment]
Do you know which probe is causing this?

**Comment by alvaroaleman** [comment]
Unfortunately not, but _wild guess_, I'd say there is a higher chance it is caused by the ssh prober since that is the most exotic one, if it was caused by one of the others there is a high chance someone else already experienced the issue.

**Comment by brian-brazil** [comment]
The `process_open_fds` will help spot an FD leak.

**Comment by alvaroaleman** [comment]
I am not sure I get your point. `process_open_fds` will tall me _that_ there is a leak, but not what codepath/probe in the blackbox_exporter caused it.

**Comment by brian-brazil** [comment]
If you only send one type of probe to a blackbox exporter at a time, you could help narrow it down.

**Comment by alvaroaleman** [comment]
So after I hit the max fd limit another two times I took the time to investigate. The fd leak seems to be caused by this job, because if I leave it on as the only job that uses the blackbox_exporter it happens, if I turn it off and keep all other jobs running it does not happen:

```
          #    - job_name: 'blackbox_ba_v4'
          #      metrics_path: /probe
          #      params:
          #        module:
          #          - http_2xx_ba_v4
          #      static_configs:
          #        - targets:
          #          - https://a.com
          #          - https://b.com
          #          - https://c.com
          #          - https://d.com
          #      relabel_configs:
          #        - source_labels: [__address__]
          #          target_label: __param_target
          #        - source_labels: [__param_target]
          #          target_label: instance
          #        - target_label: __address__
          #          replacement: '192.168.0.41:9115'
```

The module config looks like this:

```
  http_2xx_ba_v4:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
      basic_auth:
        username: 'a_user'
        password: 'a_pass'
```

Other stuff that may or may not be of relevance:

* Prometheus only talks via IPv6 to the blackbox_exporter, the `192.168.0.41:9115` above is a haproxy that does ipv4 to ipv6 translation
* There is another job that is identical to the above one except it uses ipv6, it causes no fd leak
* There is another job that is identical to the above one except it uses no basic_auth, it causes no fd leak
