### ISSUE TITLE
Canonicalization of HTTP-Headers in http Module

### ISSUE THREAD

**Issue by volllly** [prometheus/blackbox_exporter#293]
### Host operating system: output of `uname -a`
running on the docker container `prom/blackbox-exporter:latest`
### blackbox_exporter version: output of `blackbox_exporter -version`
```
blackbox_exporter, version 0.11.0 (branch: HEAD, revision: 00181ba84e595570eeed8cb1848491d3d4f85f0)
    build user:       root@3db6abb4b9fb
    build date:       20171128-13:47:58
    go version:      go1.9.2
```
### What is the blackbox.yml module config.
```
modules:
  sign_echo:
    prober: http
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      fail_if_not_matches_regexp: ['^"Hello World!$"']
      preferred_ip_protocol: ip4
      method: POST
      headers: 
        cashboxid: xxx
        accesstoken: xxx
        Content-Type: application/json
      body: '"Hello World!"'
```
### What is the prometheus.yml scrape config.
```
- job_name: 'xxx'
    metrics_path: /probe
    params:
      module: 
        - sign_echo
    static_configs:
      - targets:
        - 'xxx'
        - 'xxx'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
```
### What did you expect to see?
I looked at the HTTP-Headers sent from the blackbox_exporter to the target expecting to see:
```
cashboxid:xxx
accesstoken:xxx
```
### What did you see instead?
```
Cashboxid:xxx
Accesstoken:xxx
```
The API Im monitoring need lowercase HTTP-Headers. But the Headers get Capitalized.

I found out, the go `request.Header.Set` function [https://godoc.org/net/http#Header](https://godoc.org/net/http#Header) is automatically canonicalizing HTTP-Headers. 

I think [this](https://stackoverflow.com/questions/26351716/how-to-keep-key-case-sensitive-in-request-header-using-golang) would solve the problem.
