### ISSUE TITLE
Feature request: toggle to suppress newlines in tcp query_response mode

### ISSUE THREAD

**Issue by h3po** [prometheus/blackbox_exporter#295]
### Host operating system:
docker prom/blackbox-exporter:latest

### blackbox_exporter version:
```
blackbox_exporter, version 0.11.0 (branch: HEAD, revision: 200181ba84e595570eeed8cb1848491d3d4f85f0)
  build user:       root@3db6abb4b9fb
  build date:       20171128-13:47:58
  go version:       go1.9.2
```
### What is the blackbox.yml module config.
```
modules:
  ldap:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"
      query_response:
        - send: !!binary "ME4CAQFgSQIBAwQyQ049cHJvbWV0aGV1cyxPVT1Vc2VycywtY2Vuc29yZWQtgBAtY2Vuc29yZWQt"
        - expect: !!binary "MAwCAQFhBwoBAAQABAA="
        - send: !!binary "MB4CAQJ3GYAXMS4zLjYuMS40LjEuNDIwMy4xLjExLjM="
        - expect: !!binary "MEMCAQJ4PgoBAAQABACLNWRuOmNuPXByb21ldGhldXMsb3U9VXNlcnMsLWNlbnNvcmVkLQ=="
        - send: !!binary "MAUCAQNCAA=="

```
### What did you do that produced an error?
I am aware the send/response feature was not intended for binary data. I'm trying here to do a simple bind with an ldap server and then issue a "whoami" to verify that the server is working. It looks to me like this could work, but the query_response mode is appending a newline character (\x0a) to each send: line which breaks the protocol

### What did you expect to see?
I'd like to be able to toggle the automatic newline off.

**Comment by SuperQ** [comment]
This seems reasonable to me.. I'd almost prefer that we don't mangle the `send` string at all, and require that configurations include the `\n` in them explicitly.

**Comment by brian-brazil** [comment]
This feature is only intended for line-based protocols, and your requested feature does not make it support binary protocols - it'll just break at the next step.

You'll want to write a exporter for this.

**Comment by h3po** [comment]
@brian-brazil 
>it'll just break at the next step.
What do you think exactly would break? I'm fine with writing my own exporter, but I don't see why it couldn't be handled by blackbox. The only difference between a line protocol like smtp and ldap in this example is that ldap uses asn1 encoding instead of ascii.

**Comment by brian-brazil** [comment]
> What do you think exactly would break?

It's line oriented, so we're waiting for a `\n` which is not at all guaranteed by a binary protocol.

**Comment by h3po** [comment]
To future people who find this looking for how to monitor ldap with blackbox_exporter: @brian-brazil is right, send/expect is not suitable to actually talk the asn1 encoded protocol of ldap. If all one wants to do is test wether an ldap server is answering, you can still send a bind request with invalid credentials and expect the server to answer accordingly. This works since there happens to be a 0x0a in the "invalid" response packet:
```
  ldap:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: "ip4"
      query_response:
        - send: !!binary "MCICAQFgHQIBAwQIbm90YXVzZXKADm5vdHRoZXBhc3N3b3Jk"
        - expect: !!binary "MAwCAQFhBw=="
```

**Comment by dswarbrick** [comment]
Riding on the coat tails of the previous comment, it's also possible to do an LDAP STARTTLS handshake by sending an `extendedReq` with `LDAP_START_TLS_OID`. This is a hex string of `301d02010177188016312e332e362e312e342e312e313436362e3230303337`, which is then base64 encoded in the blackbox config. The `extendedResp` is the same as in the previous example.
```yaml
  ldap_starttls:
    prober: tcp
    tcp:
      preferred_ip_protocol: ip4
      query_response:
      - send: !!binary MB0CAQF3GIAWMS4zLjYuMS40LjEuMTQ2Ni4yMDAzNw==
      - expect: !!binary MAwCAQF4Bw==
      - starttls: true
```
