### ISSUE TITLE
Metric probe_ssl_earliest_cert_expiry always returning 17 days

### ISSUE THREAD

**Issue by Shantira** [prometheus/blackbox_exporter#298]
The problem is for every domain metric `probe_ssl_earliest_cert_expiry` returning only 17 days. And it`s not depending on how many days left for ssl certificate until it will expire.

### Host operating system:
Ubuntu 16.04 4.4.0-112-generic
Prometheus v2.0
### blackbox_exporter version:
0.12, 0.11 has same problem
### The blackbox.yml module config.
```yaml
modules:  
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4"
```
### The prometheus.yml scrape config.
```yaml
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'monitor'
scrape_configs:
  - job_name: "http_check"
    metrics_path: /probe
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
          - https://google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter_dns_record:19104
```
### What did you do that produced an error?
Prometheus query: `probe_ssl_earliest_cert_expiry{instance="https://google.com",job="http_check"}`
### What did you expect to see?
About 63 days in milliseconds time format
### What did you see instead?
17 days or 1525295400 milliseconds
