### ISSUE TITLE
Support to disable protocol fallback.

### ISSUE THREAD

**Issue by SuperQ** [prometheus/blackbox_exporter#302]
When using `preferred_ip_protocol`, it would be nice to disable fallback in order to explicitly test IPv4 or IPv6 when probing.

Proposal:
```yaml
modules:
  icmp_v6:
    prober: icmp
      icmp:
        preferred_ip_protocol: "ip6"
        protocol_fallback: false
```

**Comment by SuperQ** [comment]
Another option could be to extend the string handling to support something like this:

```yaml
preferred_ip_protocol: ip6-only
```

**Comment by rudis** [comment]
Ping (as requested on IRC).

Personally I prefer the `ip6-only` solution for it's simplicity; however it conflicts with the naming of the option which strongly suggests that is this only a preference. The `protocol_fallback` has a similar issue and may be even more confusing because it's not directly related to the `preferred_ip_protocol` option (it's not clear that there is a connection between the preference and a fallback; it's only clear if you know the code).

Maybe a new option `force_ip_protocol` which conflicts with `preferred_ip_protocol` is a cleaner solution.

**Comment by debugloop** [comment]
I do not know what the policy regarding probers is, but another option one might consider is having two additional probers, for instance `icmp_v{4,6}`. The plain `icmp` prober could keep all its settings and documentation as it was and the new ones would not have to bother with too many, possible conflicting options.

Thats of course only an option if you're open to having more probers, I can see why one would like to keep the number low and the selection simple.

**Comment by SuperQ** [comment]
@debugloop Are you talking about the default example config? I think that's intended to be a simple version. Users are free to add things like you suggest.

**Comment by SuperQ** [comment]
@Rufus, what if we replace "preferred" with `ip_protocol` and have the values `ip6-ip4`, `ip4-ip6`, `ip4`, and `ip6`. Would that be clear enough?

**Comment by debugloop** [comment]
@SuperQ no I meant distinct probers, for example:

```yaml
icmp_v6:
    prober: icmp_v6
    timeout: 5s
    icmp_v6:
        source_ip_address: "127.0.0.1"
```

Or one for `_v4`, while keeping the `icmp` probe as a variant supporting both stacks with the `preferred_ip_protocol` option.
