### ISSUE TITLE
ICMP RTT not accurate 

### ISSUE THREAD

**Issue by mancubus77** [prometheus/blackbox_exporter#315]
### Host operating system: output of `uname -a`
```
Linux basic 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
```
### blackbox_exporter version: output of `blackbox_exporter -version`

```
master 
commit 969228a28772a448591e37ca7fbac5aad708b57c
```
### What is the blackbox.yml module config.
```
modules:
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
```
### What is the prometheus.yml scrape config.
```
  - job_name: 'blackbox-icmp'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 8.8.8.8    # DNS1
        - 1.1.1.1    # DNS2
        - 127.0.0.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.0.1:9115
```
### What logging output did you get from adding `&debug=true` to the probe URL?
```
--log.lever=debug
```
### Issue

ICMP RTT for localhost:
[root@ise-basic ~]# ping 127.0.0.1 -c 5
```
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.030 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.049 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.032 ms
64 bytes from 127.0.0.1: icmp_seq=4 ttl=64 time=0.020 ms
64 bytes from 127.0.0.1: icmp_seq=5 ttl=64 time=0.034 ms
```
Meanwhile blackbox returns:
```
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 2.0513e-05
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.000377028
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 1
```
0.000377028s equals 0.377028ms, which is looks wrong for me.
Nevertheless in debug mode based on timestamp I notices nearly same time stamps:
```
ts=2018-04-28T12:42:14.747479787Z caller=main.go:176 module=icmp target=127.0.0.1 level=debug msg="Beginning probe" probe=icmp timeout_seconds=4.5
ts=2018-04-28T12:42:14.747534755Z caller=main.go:176 module=icmp target=127.0.0.1 level=debug msg="Resolving target address" preferred_ip_protocol=ip4
ts=2018-04-28T12:42:14.747557102Z caller=main.go:176 module=icmp target=127.0.0.1 level=debug msg="Resolved target address" ip=127.0.0.1
ts=2018-04-28T12:42:14.747573825Z caller=main.go:176 module=icmp target=127.0.0.1 level=debug msg="Creating socket"
ts=2018-04-28T12:42:14.747633676Z caller=main.go:176 module=icmp target=127.0.0.1 level=debug msg="Creating ICMP packet" seq=41 id=46168
ts=2018-04-28T12:42:14.74765198Z caller=main.go:176 module=icmp target=127.0.0.1 level=debug msg="Writing out packet"
ts=2018-04-28T12:42:14.747746052Z caller=main.go:176 module=icmp target=127.0.0.1 level=debug msg="Waiting for reply packets"
ts=2018-04-28T12:42:14.747779592Z caller=main.go:176 module=icmp target=127.0.0.1 level=debug msg="Found matching reply packet"
ts=2018-04-28T12:42:14.747812433Z caller=main.go:176 module=icmp target=127.0.0.1 level=debug msg="Probe succeeded" duration_seconds=0.000301551
```
Based on the timestamps between "Waiting for reply packets" and "Found matching reply packet", waiting takes 747779592-747746052=33540ns, which is equals **0.033ms**

Also I've noticed difference in timestamps:
ts=2018-04-28T12:42:14.**74765198**Z caller=main.go:176 module=icmp target=127.0.0.1 level=debug msg="Writing out packet"
ts=2018-04-28T12:42:14.**747746052**Z caller=main.go:176 module=icmp target=127.0.0.1 level=debug msg="Waiting for reply packets"

I don't believe that it might be cause of issue based on source code, but how knows.
Any advices on this?
