### ISSUE TITLE
probe_http_status_code returns 0 sporadically

### ISSUE THREAD

**Issue by cschyma** [prometheus/blackbox_exporter#326]
### Host operating system: output of `uname -a`

`Linux eedaf5449194 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 GNU/Linux`

### blackbox_exporter version: output of `blackbox_exporter -version`

```
blackbox_exporter, version 0.12.0 (branch: HEAD, revision: 4a22506cf0cf139d9b2f9cde099f0012d9fcabde)
  build user:       root@634195974c8e
  build date:       20180227-11:50:29
  go version:       go1.10
```

### What is the blackbox.yml module config.

```
modules:
  UnauthorizedRequests:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: [307, 401, 403, 503]
      method: GET
      no_follow_redirects: true
      fail_if_not_ssl: true
      preferred_ip_protocol: "ip4"
```

### What is the prometheus.yml scrape config.

```
- job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [UnauthorizedRequests]
    static_configs:
      - targets:
        - https://domain.name
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: blackboxexporter:9115  # The blackbox exporter's real hostname:port.
```

### What logging output did you get from adding `&debug=true` to the probe URL?

Following a logging output when working as expected.

```
Logs for the probe:
ts=2018-05-25T09:47:39.573864281Z caller=main.go:116 module=UnauthorizedRequests target=https://domain.name level=info msg="Beginning probe" probe=http timeout_seconds=9.5
ts=2018-05-25T09:47:39.573994201Z caller=utils.go:42 module=UnauthorizedRequests target=https://domain.name level=info msg="Resolving target address" preferred_ip_protocol=ip4
ts=2018-05-25T09:47:39.577327732Z caller=utils.go:65 module=UnauthorizedRequests target=https://domain.name level=info msg="Resolved target address" ip=52.174.181.178
ts=2018-05-25T09:47:39.577471051Z caller=http.go:282 module=UnauthorizedRequests target=https://domain.name level=info msg="Making HTTP request" url=https://[52.174.181.178] host=domain.name
ts=2018-05-25T09:47:39.658253234Z caller=http.go:300 module=UnauthorizedRequests target=https://domain.name level=info msg="Received HTTP response" status_code=401
ts=2018-05-25T09:47:39.658297339Z caller=http.go:354 module=UnauthorizedRequests target=https://domain.name level=info msg="Response timings for roundtrip" roundtrip=0 start=2018-05-25T09:47:39.577598771Z dnsDone=2018-05-25T09:47:39.577598771Z connectDone=2018-05-25T09:47:39.578005211Z gotConn=2018-05-25T09:47:39.629089584Z responseStart=2018-05-25T09:47:39.65813966Z end=2018-05-25T09:47:39.658193487Z
ts=2018-05-25T09:47:39.6584662Z caller=main.go:127 module=UnauthorizedRequests target=https://domain.name level=info msg="Probe succeeded" duration_seconds=0.084520408



Metrics that would have been returned:
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.003439116
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.084520408
# HELP probe_failed_due_to_regex Indicates if probe failed due to regex
# TYPE probe_failed_due_to_regex gauge
probe_failed_due_to_regex 0
# HELP probe_http_content_length Length of http content response
# TYPE probe_http_content_length gauge
probe_http_content_length 58
# HELP probe_http_duration_seconds Duration of http request by phase, summed over all redirects
# TYPE probe_http_duration_seconds gauge
probe_http_duration_seconds{phase="connect"} 0.000406458
probe_http_duration_seconds{phase="processing"} 0.029050094
probe_http_duration_seconds{phase="resolve"} 0.003439116
probe_http_duration_seconds{phase="tls"} 0.051490836
probe_http_duration_seconds{phase="transfer"} 5.3794e-05
# HELP probe_http_redirects The number of redirects
# TYPE probe_http_redirects gauge
probe_http_redirects 0
# HELP probe_http_ssl Indicates if SSL was used for the final redirect
# TYPE probe_http_ssl gauge
probe_http_ssl 1
# HELP probe_http_status_code Response HTTP status code
# TYPE probe_http_status_code gauge
probe_http_status_code 401
# HELP probe_http_version Returns the version of HTTP of the probe response
# TYPE probe_http_version gauge
probe_http_version 1.1
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_ssl_earliest_cert_expiry Returns earliest SSL cert expiry in unixtime
# TYPE probe_ssl_earliest_cert_expiry gauge
probe_ssl_earliest_cert_expiry 1.581946863e+09
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 1



Module configuration:
prober: http
timeout: 10s
http:
  valid_status_codes:
  - 307
  - 401
  - 403
  - 503
  preferred_ip_protocol: ip4
  no_follow_redirects: true
  fail_if_not_ssl: true
  method: GET
```

### What did you do that produced an error?

Not reproducible, Happens sporadically.

![image](https://user-images.githubusercontent.com/1670201/40538451-0015ec38-6012-11e8-8c0b-acec0715001b.png)

### What did you expect to see?

A status code outside of valid_status_codes.

### What did you see instead?

probe_http_status_code == 0
