### ISSUE TITLE
Correctly reflect target status with "up" metric

### ISSUE THREAD

**Issue by veksh** [prometheus/blackbox_exporter#354]
Blackbox targets are shown as always "up", while actual reachability status is reflected in `probe_success`. This is misleading and inconsistent with rest of exporters (e.g. snmp_exporter) and Prometheus targets. Maybe it would be nice to reflect actual target status in "up" metric.

**Comment by brian-brazil** [comment]
This is not an uncommon design, see https://prometheus.io/docs/instrumenting/writing_exporters/#failed-scrapes
The blackbox exporter can provide useful metrics even when the probe fails, so it does not fail the entire scrape.

**Comment by brian-brazil** [comment]
Information relating to DNS resolution is still available, and the blackbox exporter is more than just one probe type. Having consistency across the probe types is important.

**Comment by veksh** [comment]
Making "up" to follow probe success is exactly about consistency for me. SNMP and Prometheus are setting "up" to 0 on failed scrape (even if target is having correct DNS), while blackbox is not.

I meant per-module option, something like

```yaml
modules:
  icmp:
    prober:  icmp
    timeout: 5s
  icmp-up:
    prober: icmp
    timeout: 5s
    up_follows_success: true
```

this would work for both kinds of consistency :)
