### ISSUE TITLE
sendto: invalid argument

### ISSUE THREAD

**Issue by bswinnerton** [prometheus/blackbox_exporter#357]
👋 Hi there,

I'm trying to get blackblox_exporter running inside of a Docker container. The only image I was able to get [sort of] working was `prom/blackbox-exporter:master`, as per https://github.com/prometheus/blackbox_exporter/issues/14#issuecomment-227348894. Output including the error is below:

### Host operating system: output of `uname -a`

Docker host: `Linux nuc7i5a 4.18.6-629.native #1 SMP Wed Sep 5 15:16:26 UTC 2018 x86_64 GNU/Linux`
Docker guest: `Linux 8a4913db0bc6 4.18.6-629.native #1 SMP Wed Sep 5 15:16:26 UTC 2018 x86_64 GNU/Linux`

### blackbox_exporter version: output of `blackbox_exporter -version`

The `master` release of `prom/blackbox_exporter`.

```
/ # blackbox_exporter -version
blackbox_exporter: error: unknown short flag '-v', try --help
```

```
/ # blackbox_exporter --version
blackbox_exporter, version 0.12.0 (branch: master, revision: 9a02cbf751629830cdf9147d0935abb8fdf2dc17)
  build user:       root@77bd43f2e822
  build date:       20180814-14:39:03
  go version:       go1.10.3
```

### What is the blackbox.yml module config.

```yaml
modules:
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
      source_ip_address: "127.0.0.1"
```

### What is the prometheus.yml scrape config.

```
  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 10.70.117.1
        - 10.70.84.82
        - 4.2.2.1     # The internet
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
```

(truncated)

### What logging output did you get from adding `&debug=true` to the probe URL?

```
Logs for the probe:
ts=2018-09-10T21:18:36.908162691Z caller=main.go:118 module=icmp target=google.com level=info msg="Beginning probe" probe=icmp timeout_seconds=4.5
ts=2018-09-10T21:18:36.908212876Z caller=utils.go:42 module=icmp target=google.com level=info msg="Resolving target address" preferred_ip_protocol=ip4
ts=2018-09-10T21:18:36.936155704Z caller=utils.go:65 module=icmp target=google.com level=info msg="Resolved target address" ip=172.217.10.238
ts=2018-09-10T21:18:36.93619234Z caller=icmp.go:80 module=icmp target=google.com level=info msg="Using source address" srcIP=127.0.0.1
ts=2018-09-10T21:18:36.936203587Z caller=icmp.go:84 module=icmp target=google.com level=info msg="Creating socket"
ts=2018-09-10T21:18:36.936231872Z caller=icmp.go:139 module=icmp target=google.com level=info msg="Creating ICMP packet" seq=8 id=1
ts=2018-09-10T21:18:36.936243318Z caller=icmp.go:152 module=icmp target=google.com level=info msg="Writing out packet"
ts=2018-09-10T21:18:36.936252502Z caller=icmp.go:155 module=icmp target=google.com level=warn msg="Error writing to socket" err="write ip4 127.0.0.1->172.217.10.238: sendto: invalid argument"
ts=2018-09-10T21:18:36.936270902Z caller=main.go:131 module=icmp target=google.com level=error msg="Probe failed" duration_seconds=0.028083233



Metrics that would have been returned:
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.027966582
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.028083233
# HELP probe_icmp_duration_seconds Duration of icmp request by phase
# TYPE probe_icmp_duration_seconds gauge
probe_icmp_duration_seconds{phase="resolve"} 0.027966582
probe_icmp_duration_seconds{phase="rtt"} 0
probe_icmp_duration_seconds{phase="setup"} 3.9808e-05
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0



Module configuration:
prober: icmp
timeout: 5s
icmp:
  preferred_ip_protocol: ip4
  source_ip_address: 127.0.0.1
```

### What did you do that produced an error?

Hit `http://prometheus:9115/probe?module=icmp&target=8.8.8.8&debug=true`.

### What did you expect to see?

A successful probe.

### What did you see instead?

An error: 

```
ts=2018-09-10T21:18:36.936252502Z caller=icmp.go:155 module=icmp target=google.com level=warn msg="Error writing to socket" err="write ip4 127.0.0.1->172.217.10.238: sendto: invalid argument"
```
