### ISSUE TITLE
[Documentation] How to probe an ADDRESS + URL PATH?

### ISSUE THREAD

**Issue by kumukum** [prometheus/blackbox_exporter#365]
I'm trying to use blackbox exporter and prometheus to probe an instance at a specific address and probing path but I am unable to find this info in documentation.
i.e., I want to probe  `http://ADDRESS/url_path`

I tried this job_name config in prometheus config:

```
  - job_name: 'probe'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response
    static_configs:
      - labels:
          url_path: 'url_path'
      - targets: [ "ADDRESS:80" ]
    relabel_configs:
      - source_labels: [__address__, url_path]   <=== See here, I'm trying to append /url_path to probing target
        separator: '/'
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: '127.0.0.1:9115'
```

I have also tried this way:

```
      - source_labels: [__address__, __url_path__]   <=== See here, I'm trying to append /url_path to probing target
        separator: '/'
        target_label: __param_target
```

But it is still not probing with the url_path, but is instead only probing  http://ADDRESS/

How would I handle url path probing in config?

**Comment by europemaster** [comment]
hey @kumukum 
I had similar problem where exporter documentation felt misleading but found solution.
Check [this](https://www.digitalocean.com/community/tutorials/how-to-use-alertmanager-and-blackbox-exporter-to-monitor-your-web-server-on-ubuntu-16-04#step-4-%E2%80%94-configuring-prometheus-to-scrape-blackbox-exporter) where you point to the url in prometheus.yml and not directly in blackbox config.

- job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - {url and endpoint of actual page you want to check uptime}
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: {blackbox url and port}

**Comment by shinebayar-g** [comment]
Had same issue, my app doesn't return 200 on path /
instead it returns 200 on /healthz path. 

Now If I write something like this:
```YAML
- job_name: 'blackbox'
  metrics_path: /probe
  params:
    module: [http_2xx]  # Look for a HTTP 200 response.
  static_configs:
    - targets:
      - https://api.mydomain.com/healthz
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: localhost:9115
```

It works.
