### ISSUE TITLE
Support HTTP request body

### ISSUE THREAD

**Issue by kaihendry** [prometheus/blackbox_exporter#37]
Could there please be an example of a POST with a JSON payload & a check on the response like looking for a `"status": "success"` in the JSON response.

**Comment by brian-brazil** [comment]
We don't support HTTP POST bodys yet, PRs welcome.

**Comment by czerasz** [comment]
In the `README.md` is a example with `body`.
I see it was added recently [here](https://github.com/prometheus/blackbox_exporter/commit/500173b939664c0399f5430230d8ae33858f2039).

This could work:

```
http_post_json:
  prober: http
  timeout: 5s
  http:
    method: POST
    headers:
      Content-Type: application/json
    body: '{}'
    fail_if_not_matches_regexp:
      - '\"status\"\:\s?\"success\"'
```
