### ISSUE TITLE
[Feature] Smokeping like metrics (based on a series of multiple consecutive ICMP pings)

### ISSUE THREAD

**Issue by frittentheke** [prometheus/blackbox_exporter#370]
RRDtool did wonders for storing the metrics of various types of monitoring for years - apart from modern time-series databases like Prometheus replacing the storage, there are all the exporters to provide all the data (to then store and use for graphing / alerting on).

One tool to provide great detail about network link health apart from basic reach-ability of a target, such as like jitter, latency, packet loss, ... was or is smokeping (https://oss.oetiker.ch/smokeping/). 

While the blackbox exporter very much provides a configurable ICMP test, there are is only a single sample done for every run / scrape / call of the blackbox exporter, and only success and latency are being reported on.

Smokeping, doing a number of icmp pings is also able to report the:

> av md
>     average median
> av ls
>     average loss
> av sd
>     the average standard deviation of the multiple measurements in each round
> am/as
>     the ratio of average median and average standard deviation 

see https://oss.oetiker.ch/smokeping/doc/reading.en.html or if you like the cool graphs it produces - https://oss.oetiker.ch/smokeping-demo/?target=Customers.OP.james.

I understand that the graphing part is the job of i.e. Gafana or other tools making use of the data Prometheus has collected. Also some PromQL provides much of the math / functions required to return deviation and other metrics.

The feature I am asking for is doing a more intensive multi-packet pinging to increase the  measuring (!) sampling rate. Certainly there would only be one sample taken at every scrape interval the blackbox_exporter is called, but that sample could be done with a rather high sampling rate, allowing to better measure latency and especially jitter.

And I do not thing this requires are new / different exporter altogether, because at leat to me it seems all that is required are some more ICMP pings done per scrape and some more metrics collected on the various runtimes and potential losses of those packets of a single scrape.

**Comment by SuperQ** [comment]
This is a separate exporter I've been thinking about writing.  Rather than re-implement smokeping exactly, I have more interesting plans.

Sending a stream of pings, rather than batches, and using Prometheus histograms rather than pre-calculated averages.

**Comment by SuperQ** [comment]
Another comment.

I've built a smokeping-ish with the blackbox_exporter by having a job in Prometheus with a scrape_interval of 1s.

Then a recording rule like this:
```yaml
- name: ICMP Reachability
  interval: 30s
  rules:
  - record: job:probe_success:avg30s
    expr: avg_over_time(probe_success{job=~"blackbox_icmp.*"}[30s])
  - record: job:probe_dns_lookup_time_seconds:avg30s
    expr: avg_over_time(probe_dns_lookup_time_seconds{job=~"blackbox_icmp.*"}[30s])
  - record: job:probe_duration_seconds:min30s
    expr: min_over_time(probe_duration_seconds{job=~"blackbox_icmp.*"}[30s])
  - record: job:probe_duration_seconds:q25_30s
    expr: quantile_over_time(0.25, probe_duration_seconds{job=~"blackbox_icmp.*"}[30s])
  - record: job:probe_duration_seconds:q50_30s
    expr: quantile_over_time(0.5, probe_duration_seconds{job=~"blackbox_icmp.*"}[30s])
  - record: job:probe_duration_seconds:q75_30s
    expr: quantile_over_time(0.75, probe_duration_seconds{job=~"blackbox_icmp.*"}[30s])
  - record: job:probe_duration_seconds:max30s
    expr: max_over_time(probe_duration_seconds{job=~"blackbox_icmp.*"}[30s])
  - alert: PacketLoss
    expr: (1 - avg_over_time(job:probe_success:avg30s[5m])) * 100 > 10
    labels:
    annotations:
      description: "ICMP packet loss for {{ $labels.instance }} has been over 10% ({{ $value }}%) for 5 minutes."
      summary: "ICMP packet loss over 10%"
```
