### ISSUE TITLE
Parameter ?module is ignored

### ISSUE THREAD

**Issue by piotrkochan** [prometheus/blackbox_exporter#377]
### blackbox_exporter version: output of `blackbox_exporter -version`
Linux log 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### What is the blackbox.yml module config.
```
modules:
  my_module:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: [200]
      method: GET
      headers:
        Accept-Language: pl-PL
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4" # defaults to "ip6"
```

### What is the prometheus.yml scrape config.
Not important

### What did you expect to see?

I try to probe some data using CURL. So example request is:
```
curl localhost:9115/probe?target=google.com&module=my_module
```

The blackbox throws an error:
```
Unknown module "http_2xx"
```

Why http_2xx? I want to use "my_module". ?module is totally ignored and fallback to default "http_2xx".
If my change blackbox.yml to:

```
modules:
  http_2xx:
      .....
```

Then try to use not-existing module:
```
curl localhost:9115/probe?target=google.com&module=asdfghjkl
```

Then blackbox still uses http_2xx....

```
 HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.000791651
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.096999567
```

### What did you see instead?

I just want to ?module works properly.
