### ISSUE TITLE
Feature request: add fail_if_not_matches_regexp_with_env_vars

### ISSUE THREAD

**Issue by geekodour** [prometheus/blackbox_exporter#394]
#### Feature request
add a config to the http prober which can check regex with dynamic values from the OS.

`add fail_if_not_matches_regexp_with_env_vars`

```yml
http_200_check:
  prober: http
  http:
    valid_status_codes: [200]
    fail_if_not_matches_regexp:
      - myregex
```
adding this feature will enable us to do something like:

```yml
http_200_check:
  prober: http
  http:
    valid_status_codes: [200]
    fail_if_not_matches_regexp_with_env_vars:
      - myregex_$TODAY_otherpartoftheregex
```
so `$TODAY` is an env var that the user will set before hand.

If this is a possible feature that can be added I can work on the PR.
