### ISSUE TITLE
Always check all ports if your service have multiple ports  

### ISSUE THREAD

**Issue by johnzheng1975** [prometheus/blackbox_exporter#402]
My configure file
```
- job_name: health-check
  params:
    module:
    - http_2xx
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /probe
  scheme: http
  kubernetes_sd_configs:
  - api_server: null
    role: service
    namespaces:
      names: []
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_healthcheck]
    separator: ;
    regex: "true"
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_service_name]
    separator: ;
    regex: (.*)
    target_label: service_name
    replacement: $1
    action: replace
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_healthcheckpath]
    regex: (.*)(:80)?
    target_label: __param_target
    replacement: ${1}
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: ${1}
    action: replace
  - separator: ;
    regex: .*
    target_label: __address__
    replacement: blackbox-exporter-service:9115
    action: replace
  - separator: ;
    regex: (.*)
    target_label: sourcejob
    replacement: healthcheck
    action: replace
```

My svc file:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/healthcheck: "true"
    prometheus.io/healthcheckpath: /xxx/v1/health
    prometheus.io/path: /metrics
    prometheus.io/port: "9090"
    prometheus.io/probe: "true"
    prometheus.io/scrape: "true"
  name: xx-xxx-service
  namespace: xx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9000
  - name: prom
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: xxx
```
