### ISSUE TITLE
Content-Type: application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by roasten** [prometheus/blackbox_exporter#409]
I have a config looking like this:

    prober: http
    http:
      method: POST
      headers:
        Content-Type: application/x-www-form-urlencoded
      body:

Seems it doesn't take the "Content-Type: application/x-www-form-urlencoded" parameter, since Im getting error 500. Tried manually and it sends 500 if Content-Type isn't set.

**Comment by roasten** [comment]
No problems thanks anyway!

**Comment by roasten** [comment]
Actually this is a bug in the code of http.go

https://stackoverflow.com/questions/19253469/make-a-url-encoded-post-request-using-http-newrequest

Original
if httpConfig.Body != "" {
		body = strings.NewReader(httpConfig.Body)
	}

Update
if httpConfig.Body != "" {
		body = strings.NewReader(httpConfig.Body).Encode()

	}

**Comment by brian-brazil** [comment]
The code is correct, it sends on whatever data you give it. If you want it encoded, you need to do it yourself.

**Comment by roasten** [comment]
Correct, did a big misstake: used none url encoded data in the body, so it failed on that.

**Comment by typ431127** [comment]
I also get a 500 error, after testing body: 'code=200&type=0' there will be no problem, the program can parse application/x-www-form-urlencoded normally
```
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []
      method: POST
      headers:
        Accept: application/json, text/javascript, */*; q=0.01
        Accept-Encoding: gzip, deflate, br
        Accept-Language: zh,zh-CN;q=0.9
        Content-Type: 'application/x-www-form-urlencoded; charset=UTF-8'
        Sec-Fetch-Dest: empty
        Sec-Fetch-Mode: cors
        Sec-Fetch-Site: same-origin
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
        X-Requested-With: XMLHttpRequest
        sec-ch-ua-mobile: ?0
        sec-ch-ua-platform: "Windows"
      body: 'code=200&type=0'
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
```
