### ISSUE TITLE
Please support custom CAs for http prober

### ISSUE THREAD

**Issue by FauxFaux** [prometheus/blackbox_exporter#41]
The `tcp` prober supports specifying a custom certificate authority store, but the `http` one does not.

**Comment by brian-brazil** [comment]
Would you like to send a PR adding a `TLSConfig` to the http module?

**Comment by lausser** [comment]
Hi,
i just played around a bit. Before sending a pull-request, what's better in your opinion?
1) new option for the http prober
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [] # Defaults to 2xx
      .....
      tls_config:
        insecure_skip_verify: true

2) using the tcp prober to tell the module how to handle insecure CAs
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [] # Defaults to 2xx
      ...
      no_follow_redirects: false
    tcp:
      tls: true
      tls_config:
        insecure_skip_verify: true

Gerhard

**Comment by brian-brazil** [comment]
Definitely the former. Probers shouldn't depend on each other.

**Comment by javefang** [comment]
Looks like this is supported already. This is not documented in this repository, but I noticed you can set "ca_file" under the "tls_config".

e.g.
```
modules:
  http_2xx:
    probe: http
    timeout: 5s
    http:
      method: GET
      tls_config:
        ca_file: <path_to_custom_ca.pem>
```
