### ISSUE TITLE
icmp probe missing config

### ISSUE THREAD

**Issue by kennethlimcp** [prometheus/blackbox_exporter#418]
It seems like the `ip_protocol_fallback` config is not available for `icmp` though it's mentioned in the docs.

### Host operating system: 

`Darwin xxx.local 16.7.0 Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64 x86_64`

### blackbox_exporter version: output of `blackbox_exporter -version`

using docker image: `prom/blackbox-exporter:cd438996c807`

### What is the blackbox.yml module config.

```
modules:
  icmp:
    prober: icmp
    icmp:
      preferred_ip_protocol: "ip6"
      payload_size: 1
      dont_fragment: true
      ip_protocol_fallback: true
```

### What is the prometheus.yml scrape config.

NIL

### What logging output did you get from adding `&debug=true` to the probe URL?

NIL

### What did you do that produced an error?

Running `blackbox_exporter` using the `config.yml` above

### What did you expect to see?

`blackbox_exporter` runs as expected

### What did you see instead?

```
level=error ts=2019-02-15T05:24:46.3322428Z caller=main.go:219 msg="Error loading config" err="Error parsing config file: yaml: unmarshal errors:\n  line 8: field ip_protocol_fallback not found in type config.plain"
```
