### ISSUE TITLE
Using the documented relabel_configs results in false positive

### ISSUE THREAD

**Issue by drewhemm** [prometheus/blackbox_exporter#43]
Hi,

```yaml
relabel_configs:
  - source_labels: [__address__]
    regex: (.*)(:5050)?
    target_label: __param_target
    replacement: ${1}
  - source_labels: [__param_target]
    regex: (.*)
    target_label: instance
    replacement: ${1}
  - source_labels: []
    regex: .*
    target_label: __address__
    replacement: 127.0.0.1:9115  # Blackbox exporter.
```

For some reason, this relabel config causes the http_2xx to report that a targeted service is available, even the host is inaccessible for whatever reason, such as firewall rules. Here's the output from a curl that shows the host is not reachable, yet when using the above relabel config, Prometheus reports it is 'Up':

`[aop-dev@prometheus-i-e588886d ~]$ curl -v content-service.si.example.org:5050
* About to connect() to content-service.si.example.org port 5050 (#0)
*   Trying 54.555.55.55...
* Connection timed out
*   Trying 55.555.55.55...
* After 86359ms connect time, move on!
* Failed connect to content-service.si.example.org:5050; Operation now in progress
* Closing connection 0
curl: (7) Failed connect to content-service.si.example.org:5050; Operation now in progress`

(TLDs and IPs changed for privacy)

Removing the block that targets ```__address__``` solves this issue, but leaves the wrong value displayed in the interface.
