### ISSUE TITLE
Prometheus metrics path with probe not working

### ISSUE THREAD

**Issue by zjeraar** [prometheus/blackbox_exporter#45]
It might be that I'm doing it wrong, but I want to add the probe path as a metrics path in the Prometheus configuration, something like:

```
- job_name: "blackbox_exporter"
  scheme: "http"
  metrics_path: "/probe?target=google.com&module=http_2xx"
  static_configs:
  - targets:
    - localhost:9115
    labels:
      target_name: "google.com"
```

This doesn't work. In Prometheus I get the error `text format parsing error in line 1: invalid metric name`. When I look at the prometheus server `localhost:9090/targets` I see the endpoint as I put it in the configuration, however, when I click on it, I get the standard blackbox page:

![image](https://cloud.githubusercontent.com/assets/3328003/16538788/e373d860-402e-11e6-9dbd-7ea32e93bee3.png)

Which is probably causing the error. When I look at the url in the browser then, I see that it's not `http://localhost:9115/probe?target=google.com&module=http_2xx`, but `http://localhost:9115/probe%3target=google.com&module=http_2xx`. The ? in the metric_path seems to get encoded (%3). When I replace the %3 by a ? it works as expected.

Since nobody else seems to have this problem, I might be doing something wrong. Any help would be greatly appreciated.
