### ISSUE TITLE
"Invalid HTTP response status code" results in "UP" in Prometheus

### ISSUE THREAD

**Issue by SLE-TheRealOne** [prometheus/blackbox_exporter#454]
### Host operating system: output of `uname -a`
Linux contrib-stretch 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`
0.14.0

### What is the blackbox.yml module config.
```
modules:
  http_2xx:
    prober: http
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      method: "GET"
      proxy_url: "http://127.0.0.1:3128"
      tls_config:
        ca_file: ca.pem
      valid_status_codes: [200]
```

### What is the prometheus.yml scrape config.
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - 'https://{dns_alias}/${appName}/status/full'

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115 # Blackbox exporter.
```

### What logging output did you get from adding `&debug=true` to the probe URL?
```
Logs for the probe:
ts=2019-04-05T09:20:46.805607998Z caller=main.go:118 module=http_2xx target=https://${dns_alias}/keepAlive level=info msg="Beginning probe" probe=http timeout_seconds=9.5
ts=2019-04-05T09:20:46.805925486Z caller=utils.go:42 module=http_2xx target=https://${dns_alias}/keepAlive level=info msg="Resolving target address" ip_protocol=ip6
ts=2019-04-05T09:20:46.812952629Z caller=utils.go:55 module=http_2xx target=https://${dns_alias}/keepAlive level=warn msg="Resolution with IP protocol failed, attempting fallback protocol" fallback_protocol=ip4 err="address ${dns_alias}: no suitable address found"
ts=2019-04-05T09:20:46.817747549Z caller=utils.go:75 module=http_2xx target=https://${dns_alias}/keepAlive level=info msg="Resolved target address" ip=10.249.23.23
ts=2019-04-05T09:20:46.818983728Z caller=http.go:349 module=http_2xx target=https://${dns_alias}/keepAlive level=info msg="Making HTTP request" url=https://${ip_port}/keepAlive host=${dns_alias}
ts=2019-04-05T09:20:46.976867359Z caller=http.go:368 module=http_2xx target=https://${dns_alias}/keepAlive level=info msg="Received HTTP response" status_code=503
ts=2019-04-05T09:20:46.976994841Z caller=http.go:377 module=http_2xx target=https://${dns_alias}/keepAlive level=info msg="Invalid HTTP response status code" status_code=503 valid_status_codes=[200]
ts=2019-04-05T09:20:46.977174434Z caller=http.go:450 module=http_2xx target=https://${dns_alias}/keepAlive level=info msg="Response timings for roundtrip" roundtrip=0 start=2019-04-05T09:20:46.819186435Z dnsDone=2019-04-05T09:20:46.819186435Z connectDone=2019-04-05T09:20:46.819605084Z gotConn=2019-04-05T09:20:46.955392788Z responseStart=2019-04-05T09:20:46.976692272Z end=2019-04-05T09:20:46.977161483Z
ts=2019-04-05T09:20:46.97738708Z caller=main.go:131 module=http_2xx target=https://${dns_alias}/keepAlive level=error msg="Probe failed" duration_seconds=0.171691756
```

### What did you do that produced an error?
Call http://localhost:9090/targets

### What did you expect to see?
Status DOWN for my instance as i volontarly set it to return 503

### What did you see instead?
Status UP for my instance

"Status" of the /alert page returns the status of the probe itself rather than the status of the endpoint called.

![image](https://user-images.githubusercontent.com/18751352/55621371-9737a880-579d-11e9-807f-82d483c97da2.png)
