### ISSUE TITLE
Show probe failed due to in alerts

### ISSUE THREAD

**Issue by cpoetter** [prometheus/blackbox_exporter#459]
Hi,

thank you very much for making such an awesome product! I am pretty new to prometheus and blackbox. But I made it to deploy a complete prometheus environment to production thanks to your awesome documentations! 🎉

I have just one question/feature request:

In my `alert.rules` file I would like to include in the alert **why** the probe was failing. 

```
- name: blackbox
  rules:
   - alert: probe_failing
     expr: up{job="blackbox"} == 0 or probe_success{job="blackbox"} == 0
     for: 1m
     labels:
       severity: critical
     annotations:
       summary: "Webserver not reachable"
       description: "{{ $labels.instance }} is not reachable."
```

As you can see, currently my (Slack) alert is only showing *that* a probe is failing. I would like to include for example that it is failing because of a timeout, or because the HTTP status is different as the expected one, or because the SSL certificate expired, etc...

It would be awesome if there would be a variable like `$probe_failed_due_to` that could be included in the alert. For example like:

```
summary: "Webserver probe failed"
description: "{{ $labels.instance }} failed due to {{ probe_failed_due_to}}."
```

Thanks for your help!
