### ISSUE TITLE
How to monitor multiple targets with servicemonitor ?

### ISSUE THREAD

**Issue by RealArtemiy** [prometheus/blackbox_exporter#464]
### Host operating system: output of `uname -a`
kubernetes, installed via helm chart
https://github.com/helm/charts/tree/master/stable/prometheus-blackbox-exporter

### blackbox_exporter version: output of `blackbox_exporter -version`

```
blackbox_exporter --version
blackbox_exporter, version 0.14.0 (branch: HEAD, revision: bba7ef76193948a333a5868a1ab38b864f7d968a)
  build user:       root@63d11aa5b6c6
  build date:       20190315-13:32:31
  go version:       go1.11.5
```

### What is the blackbox.yml module config.
```
modules:
  health:
    http:
      fail_if_body_matches_regexp:
      - DOWN
      headers:
        User-Agent: BlackBox-exporter/v0.14.0
      method: GET
      preferred_ip_protocol: ip4
      valid_status_codes:
      - 200
    prober: http
  http_2xx:
    http:
      no_follow_redirects: false
      preferred_ip_protocol: ip4
      valid_http_versions:
      - HTTP/1.1
      - HTTP/2
    prober: http
    timeout: 5s
```
### What is the prometheus.yml scrape config.
```
- job_name: monitoring/prometheus-blackbox-exporter-github/0
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - monitoring
  relabel_configs:
    ......

```
### What did you do that produced an error?
I used this servicemonitor config

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-blackbox-exporter
  name: prometheus-blackbox-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 60s
    port: http-metrics
  - interval: 60s
    params:
      module:
        - health
      targets:
        - https://google.com
        - https://github.io
    path: "/probe"
    targetPort: 9115
    relabelings:
      - sourceLabels:
          - __param_target
        targetLabel: target
      - sourceLabels:
          - __param_module
        targetLabel: module
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    app: prometheus-blackbox-exporter
```

### What did you expect to see?

Multiple targets monitor

### What did you see instead?
In prometheus "targets" page
```
server returned HTTP status 400 Bad Request
```

--
