### ISSUE TITLE
preferred_ip_protocol does not persist through HTTP redirects

### ISSUE THREAD

**Issue by jtackaberry** [prometheus/blackbox_exporter#465]
Given this probe:
```
  http_2xx_v4:
    prober: http
    http:
      preferred_ip_protocol: ip4
```

If passing targets that issue a 301 redirect, the first request is to the IPv4 address expected, but the second connection for the redirected URL is IPv6.

My use-case is to set up two different types of probers: one to test v4 connectivity and another to test v6 connectivity.  The http_2xx_v4 proper described above is only half effective in the face of an HTTP redirect.
