### ISSUE TITLE
Create exception for no SSL

### ISSUE THREAD

**Issue by thachnv92** [prometheus/blackbox_exporter#499]
Hello, I have a problem with blackbox exporter.

I have 2 APIs.
API 1st: https, and SSL status is **valid**
API 2nd: http, and SSL status is **Invalid**

But I want to except case http (no SSL), I want SSL status of API http no SSL is **valid**
Please help me to config it.
Thanks

**Comment by kongslund** [comment]
Perhaps what you are looking for are the flags `fail_if_not_ssl` and `fail_if_ssl`?

Take a look at https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md

**Comment by thachnv92** [comment]
@kongslund 
I try with `fail_if_not_ssl` and `fail_if_ssl` but It's metric `probe_success`, not `probe_http_ssl`.

**Comment by thachnv92** [comment]
I try to false with 2 config above, but it's "invalid"

**Comment by kongslund** [comment]
I don't understand. Can you be more specific? What does your blackbox exporter config look like? What does the probe URL look like? For the HTTP target, what return value do you expect for `probe_success` and `probe_http_ssl`?

**Comment by thachnv92** [comment]
This is my blackbox exporter config:
```
  http_post_web:
    prober: http
    timeout: 50s
    http:
      method: POST
      fail_if_ssl: false
      fail_if_not_ssl: false
      headers:
        Content-Type: 'application/json'
        Accept: 'application/json'
        Accept-Language: 'en_US'
        X-Device-Model: 'SAMSUNG-SM-G925A'
        X-Device-MNO: 'ATT'
        X-Internet-Version: '6.0'
        X-Country-Code: 'US'
        X-Api-Key: 'xxx'
        X-Transaction-Id: 'xxxxxxxxxxxxxxxxxxxxxx'
      body: '{"url":"hello"}'
```
`probe_success` return **1** => UP. It's OK
`probe_http_ssl` return **Invalid** => I want expect this case and config result to **valid**.
