### ISSUE TITLE
http basic_auth: allow credentials via parameter from prometheus.yml

### ISSUE THREAD

**Issue by azrdev** [prometheus/blackbox_exporter#507]
To probe a (number of) http service(s) which require basic_auth authentication, it is currently necessary to define an extra module for each set of credentials. This is clarified in https://github.com/prometheus/blackbox_exporter/issues/53#issuecomment-234252997 together with the suggestion to use matching credentials on all hosts. This is not only inconvenient, but not recommendable from a security perspective.

I suggest to add a config parameter which allows to specify the credentials for each target host/url together with that target in the prometheus config, allowing to reuse a single http basic auth module from `blackbox.yml`.

**Comment by brian-brazil** [comment]
That would be insecure, as labels are not secret. In addition this is not our configuration management approach. You'll need to have one module per credential.

**Comment by bzon** [comment]
@brian-brazil using the config file, is it possible (as a feature) to get credentials from secret providers? e.g. k8s secret.

```yaml
http:
  basic_auth:
    user: "x"
    password: "x
```

to something like.

```yaml
http:
  basic_auth_from_k8s:
    secretKeyRef: "basic-auth-cred"
```
