### ISSUE TITLE
Timeout reading from socket

### ISSUE THREAD

**Issue by krakazyabra** [prometheus/blackbox_exporter#518]
### Host operating system: output of `uname -a`
```
Linux blackbox-prometheus-blackbox-exporter-66f5bcf898-qrdxt 4.15.18-18-pve #1 SMP PVE 4.15.18-44 (Wed, 03 Jul 2019 11:19:13 +0200) x86_64 GNU/Linux
```
### blackbox_exporter version: output of `blackbox_exporter -version`
```
blackbox_exporter, version 0.14.0 (branch: HEAD, revision: bba7ef76193948a333a5868a1ab38b864f7d968a)
  build user:       root@63d11aa5b6c6
  build date:       20190315-13:32:31
  go version:       go1.11.5
```
### What is the blackbox.yml module config.
```
    modules:
      http_2xx:
        http:
          no_follow_redirects: false
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2
        prober: http
        timeout: 5s
      icmp:
        icmp:
          preferred_ip_protocol: ip4
          source_ip_address: 127.0.0.1
        prober: icmp
        timeout: 10s
```
### What is the prometheus.yml scrape config.
```
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module:
            - http_2xx
            - icmp
        static_configs:
          - targets:
            - mydomain.com
            - prometheus.io
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: blackbox.mydomain.org
```
### What logging output did you get from adding `&debug=true` to the probe URL?
```
Logs for the probe:
ts=2019-09-05T17:18:55.517348794Z caller=main.go:118 module=icmp target=prometheus.io level=info msg="Beginning probe" probe=icmp timeout_seconds=9.5
ts=2019-09-05T17:18:55.51754965Z caller=utils.go:42 module=icmp target=prometheus.io level=info msg="Resolving target address" ip_protocol=ip4
ts=2019-09-05T17:18:55.521502261Z caller=utils.go:75 module=icmp target=prometheus.io level=info msg="Resolved target address" ip=104.24.120.60
ts=2019-09-05T17:18:55.521592996Z caller=icmp.go:95 module=icmp target=prometheus.io level=info msg="Using source address" srcIP=127.0.0.1
ts=2019-09-05T17:18:55.521639172Z caller=icmp.go:99 module=icmp target=prometheus.io level=info msg="Creating socket"
ts=2019-09-05T17:18:55.521725122Z caller=icmp.go:154 module=icmp target=prometheus.io level=info msg="Creating ICMP packet" seq=39444 id=33313
ts=2019-09-05T17:18:55.521769787Z caller=icmp.go:167 module=icmp target=prometheus.io level=info msg="Writing out packet"
ts=2019-09-05T17:18:55.521903073Z caller=icmp.go:188 module=icmp target=prometheus.io level=info msg="Waiting for reply packets"
ts=2019-09-05T17:19:05.017450421Z caller=icmp.go:193 module=icmp target=prometheus.io level=warn msg="Timeout reading from socket" err="read ip4 127.0.0.1: i/o timeout"
ts=2019-09-05T17:19:05.017568922Z caller=main.go:131 module=icmp target=prometheus.io level=error msg="Probe failed" duration_seconds=9.500115242
```
### What did you do that produced an error?
Run blackbox-exporter, added ICMP module
### What did you expect to see?
`probe_success 1`
### What did you see instead?
`probe_success 0`
