### ISSUE TITLE
[bug?] http prober follows redirects -- with the original hostname

### ISSUE THREAD

**Issue by evilham** [prometheus/blackbox_exporter#525]
### Host operating system: output of `uname -a`
Debian-based kernel 4.19

### blackbox_exporter version: output of `blackbox_exporter -version`
0.15.0 / 0.15.1

### What is the blackbox.yml module config.

```
  http_2xx_ipv6_tls:
    prober: http
    http:
      valid_status_codes: [ 200,  201, 202, 204, 206, 207, 401, 403]
      fail_if_not_ssl: true
      preferred_ip_protocol: "ip6"
      ip_protocol_fallback: false
```

### What is the prometheus.yml scrape config.

```
  - job_name: http_ipv6
    metrics_path: /probe
    params:
      module:
      - http_2xx_ipv6_tls
    relabel_configs: *id001
    scrape_interval: 2m
    static_configs:
    - targets:
      - https://example.org
```
### What logging output did you get from adding `&debug=true` to the probe URL?

```
2019-09-18_16:22:27.98737 ts=2019-09-18T16:22:27.985646065Z caller=main.go:174 module=http_2xx_ipv6_tls target=https://example.org level=debug msg="Error for HTTP request" err="Get https://stuff.example.org: x509: certificate is valid for stuff.example.org, not example.org"
```

### What did you do that produced an error?

The `example.org` host over HTTPS replies with a 307 redirect to `stuff.example.org` (also over https).

### What did you expect to see?

The redirect followed and the new hostname used for TLS.

### What did you see instead?

The probe continued with the original hostname, which fails.
To be fair, there are cases where this behaviour is already expected, so maybe what is missing is some kind of setting for that?
