### ISSUE TITLE
error parsing config file: yaml: line 2: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by bbigras** [prometheus/blackbox_exporter#527]
### Host operating system: output of `uname -a`
Linux hostname 4.4.0-164-generic #192-Ubuntu SMP Fri Sep 13 12:02:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`
blackbox_exporter, version 0.15.1 (branch: HEAD, revision: 7dd86a593b5a2270e738be1654d9c112509e46ce)
  build user:       root@626ba8fd110c
  build date:       20190917-12:31:25
  go version:       go1.13

from the `prom/blackbox-exporter` docker image.

### What is the blackbox.yml module config.
```yml
modules:
  http_2xx:
    prober: http
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp
```

### What did you do that produced an error?
I updated the docker image. 

same problem with prom/blackbox-exporter:v0.15.0
prom/blackbox-exporter:v0.14.0 looks fine.

### What did you see instead?

```
level=info ts=2019-09-19T14:02:24.603Z caller=main.go:212 msg="Starting blackbox_exporter" version="(version=0.15.1, branch=HEAD, revision=7dd86a593b5a2270e738be1654d9c112509e46ce)"
level=info ts=2019-09-19T14:02:24.603Z caller=main.go:213 msg="Build context" (gogo1.13,userroot@626ba8fd110c,date20190917-12:31:25)=(MISSING)
level=error ts=2019-09-19T14:02:24.603Z caller=main.go:216 msg="Error loading config" err="error parsing config file: yaml: line 2: mapping values are not allowed in this context"
```
