### ISSUE TITLE
Probe timeout more than 10s

### ISSUE THREAD

**Issue by fatgit** [prometheus/blackbox_exporter#529]
I've tried to setup timeout more than 10s in Blackbox exporter. I made it for icmp, tcp and http probes.

Anybody knows, why is 10s limit of a probe?
![image](https://user-images.githubusercontent.com/11026137/65644377-eae6ba00-dfa8-11e9-85b4-75dded59b62e.png)

### Host operating system: output of `uname -a`
Linux prom-2 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
### blackbox_exporter version: output of `blackbox_exporter -version`
blackbox_exporter, version 0.14.0

### What is the blackbox.yml module config.
```
  icmp_sensors:
    prober: icmp
    timeout: 60s
    icmp:
      preferred_ip_protocol: "ip4"
```
### What is the prometheus.yml scrape config.
```
  - job_name: 'icmp'
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
          - icmp.json
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
```
