### ISSUE TITLE
https: context deadline exceeded for host that is up and running

### ISSUE THREAD

**Issue by shibumi** [prometheus/blackbox_exporter#533]
### Host operating system: output of `uname -a`

Linux odroid 4.14.94-155 #1 SMP PREEMPT Wed Jan 23 05:19:08 -02 2019 armv7l armv7l armv7l GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter -version`

blackbox_exporter, version 0.14.0 (branch: HEAD, revision: bba7ef76193948a333a5868a1ab38b864f7d968a)
  build user:       root@63d11aa5b6c6
  build date:       20190315-13:37:51
  go version:       go1.11.5

### What is the blackbox.yml module config.

```yaml
modules:
  http_2xx:
    http:
      preferred_ip_protocol: "ip4"
      tls_config:
        insecure_skip_verify: true
    prober: http
```

### What is the prometheus.yml scrape config.

```yaml
#
# Ansible managed
#
# http://prometheus.io/docs/operating/configuration/

global:
  evaluation_interval: 15s
  scrape_interval: 15s
  scrape_timeout: 15s

  external_labels:
    environment: XXX




rule_files:
  - /etc/prometheus/rules/*.rules


scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
    - targets:
      - XXX:9090
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/node.yml
    job_name: node
  - file_sd_configs:
    - files:
      - /etc/prometheus/file_sd/alertmanager.yml
    job_name: alertmanager
  - job_name: blackbox
    metrics_path: /probe
    params:
      module:
      - http_2xx
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_target
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: XXX:9115
      target_label: __address__
    static_configs:
    - labels:
        blackbox_instance: XXX
      targets:
      - https://tu-clausthal.de
```

### What logging output did you get from adding `&debug=true` to the probe URL?

```
Logs for the probe:
ts=2019-10-02T13:38:16.534760758Z caller=main.go:118 module=http_2xx target=https://tu-clausthal.de level=info msg="Beginning probe" probe=http timeout_seconds=9.5
ts=2019-10-02T13:38:16.537264814Z caller=utils.go:42 module=http_2xx target=https://tu-clausthal.de level=info msg="Resolving target address" ip_protocol=ip4
ts=2019-10-02T13:38:16.545592804Z caller=utils.go:75 module=http_2xx target=https://tu-clausthal.de level=info msg="Resolved target address" ip=139.174.32.9
ts=2019-10-02T13:38:16.545789219Z caller=http.go:349 module=http_2xx target=https://tu-clausthal.de level=info msg="Making HTTP request" url=https://[139.174.32.9] host=tu-clausthal.de
ts=2019-10-02T13:38:26.035054651Z caller=http.go:364 module=http_2xx target=https://tu-clausthal.de level=error msg="Error for HTTP request" err="Get https://[139.174.32.9]: context deadline exceeded"
ts=2019-10-02T13:38:26.035495771Z caller=http.go:450 module=http_2xx target=https://tu-clausthal.de level=info msg="Response timings for roundtrip" roundtrip=0 start=2019-10-02T13:38:16.546092632Z dnsDone=2019-10-02T13:38:16.546092632Z connectDone=2019-10-02T13:38:16.548142859Z gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z end=0001-01-01T00:00:00Z
ts=2019-10-02T13:38:26.036198138Z caller=main.go:131 module=http_2xx target=https://tu-clausthal.de level=error msg="Probe failed" duration_seconds=9.500862511
```

### What did you do that produced an error?

start blackbox_exporter with the config (above) and prometheus with the config (above)

### What did you expect to see?

I expect to see a successful probe

### What did you see instead?

I see the `context deadline exceeded` message instead, although prometheus web UI shows the target as "UP" and the website is definitely reachable over TLS. When I generate a traffic dump via tshark I see successful TLS requests and I see a redirect on the correct website. With curl I can access the target website as well, just the blackbox_exporter shows that the probe wasn't successful.

### How to reproduce

Set up a blackbox_exporter and probe the target:"https://tu-clausthal.de"
