### ISSUE TITLE
Feature request: Custom endpoint IP for http checks

### ISSUE THREAD

**Issue by mblaschke** [prometheus/blackbox_exporter#543]
Allow custom endpoint IP addresses for HTTP checks.
Sometimes services are exposed behind a NAT or not reachable via the published DNS address so it would be nice to specify a custom IP address for overriding the DNS request.

possible example:

```
  http_2xx:
    prober: http
    timeout: 30s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      preferred_ip_protocol: "ip4"
      endpoint: "10.1.2.3"
```

The current solution (creating a module for each check) is too much work and creates a huge configuration :(
