### ISSUE TITLE
Please specify the user-agent header in the HTTP requests.

### ISSUE THREAD

**Issue by pvalsecc** [prometheus/blackbox_exporter#555]
### What did you expect to see?

I'm expecting to be able to filter out the requests from blackbox exporter in my access logs.
So, please, add a user agent header that container the "blackbox exporter" string somewhere.

### What did you see instead?

I see User-Agent: Go-http-client/1.1
Not easy to filter in the access logs...

**Comment by pvalsecc** [comment]
Looks like it's possible:
```yaml
modules:
  http_2xx:
    prober: http
    http:
      #preferred_ip_protocol: "ip4" # defaults to "ip6"
      #ip_protocol_fallback: false  # no fallback to "ip6"
      headers:
        User-Agent: "blackbox-monitoring"
```

**Comment by brian-brazil** [comment]
Would you like to send a PR? Note that we must allow this to be overridden, and see the format we use over in Prometheus for scapes.

**Comment by pauloczava** [comment]
This Issue seems to be already resolved since you can change headers.

`modules:
  http_2xx:
    prober: http
    timeout: 30s
    http:
      valid_status_codes: [] #default to 2xx
      method: GET
      headers:
        User-Agent: potatohead1.1`

**Comment by tdm4** [comment]
This is not working for me:
```
modules:
  http_2xx:
    prober: http
    timeout: 60s
    http:
      headers:
        User-Agent: "blackbox_exporter"
```

Restarted prometheus and it continues to use `Go-http-client/1.1` regardless.
