### ISSUE TITLE
SSL certificate check problem

### ISSUE THREAD

**Issue by Tri0L** [prometheus/blackbox_exporter#558]
Config:
```
  http_test:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      method: GET
      headers:
        Host: google.com
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      ip_protocol_fallback: false  # no fallback to "ip6"
```

```
# dig google.com +short
216.58.201.238
```

Debug url:
```
my_exporter_ip:9115/probe?target=https://216.58.201.238:443&module=http_test&debug=true
```

Logs for the probe:
```
ts=2019-12-14T12:30:34.920215284Z caller=main.go:304 module=http_test target=https://216.58.201.238:443 level=info msg="Beginning probe" probe=http timeout_seconds=5
ts=2019-12-14T12:30:34.920454871Z caller=http.go:318 module=http_test target=https://216.58.201.238:443 level=info msg="Resolving target address" ip_protocol=ip4
ts=2019-12-14T12:30:34.920489968Z caller=http.go:318 module=http_test target=https://216.58.201.238:443 level=info msg="Resolved target address" ip=216.58.201.238
ts=2019-12-14T12:30:34.920554734Z caller=client.go:250 module=http_test target=https://216.58.201.238:443 level=info msg="Making HTTP request" url=https://216.58.201.238:443 host=google.com
ts=2019-12-14T12:30:34.941038598Z caller=main.go:119 module=http_test target=https://216.58.201.238:443 level=error msg="Error for HTTP request" err="Get https://216.58.201.238:443: x509: cannot validate certificate for 216.58.201.238 because it doesn't contain any IP SANs"
ts=2019-12-14T12:30:34.941106714Z caller=main.go:119 module=http_test target=https://216.58.201.238:443 level=info msg="Response timings for roundtrip" roundtrip=0 start=2019-12-14T13:30:34.920659514+01:00 dnsDone=2019-12-14T13:30:34.920659514+01:00 connectDone=2019-12-14T13:30:34.927416113+01:00 gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z end=0001-01-01T00:00:00Z
ts=2019-12-14T12:30:34.941135738Z caller=main.go:304 module=http_test target=https://216.58.201.238:443 level=error msg="Probe failed" duration_seconds=0.020777461
```

Why `x509: cannot validate certificate for 216.58.201.238 because it doesn't contain any IP SANs`?
In config you can see that `Host` header provided.
