### ISSUE TITLE
How to Set Muti-endpoints in the same job

### ISSUE THREAD

**Issue by bubbleatgit** [prometheus/blackbox_exporter#563]
### blackbox_exporter version
```
blackbox_exporter, version 0.16.0 (branch: HEAD, revision: 991f89846ae10db22a3933356a7d196642fcb9a9)
  build user:       root@64f600555645
  build date:       20191111-16:27:24
  go version:       go1.13.4

```

###  blackbox.yml module config.
```
modules:                                                                                                                                                                           
  posp_http_check:
    prober: http
    timeout: 5s
    http:
      method: GET
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      fail_if_not_ssl: true

```

### prometheus.yml scrape config
```
    - job_name: 'posp_http_check'
      metrics_path: /probe
      params:
          module: [posp_http_check]
      file_sd_configs:
        - files:
          - 'targets/probes/http_probes.json'
          refresh_interval: 5m
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          regex: (.*)
          target_label: url
          replacement: ${1}
        - target_label: __address__
          replacement: 'black-exporter:9115' 
```
### What did you expect to see?
How to Set Muti-endpoints in the same job,like:
```
    - job_name: 'posp_http_check'
      metrics_path: /probe
      params:
          module: [posp_http_check]
      file_sd_configs:
        - files:
          - 'targets/probes/http_probes.json'
          refresh_interval: 5m
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          regex: (.*)
          target_label: url
          replacement: ${1}
        - target_label: __address__
          replacement: ['black-exporter:9115','1.2.3.4:9115','2.3.1.2:9115' ]
```
