### ISSUE TITLE
Execute action after scrape

### ISSUE THREAD

**Issue by caruccio** [prometheus/blackbox_exporter#569]
### This is a feature request

What you think of some way to execute a command after target scrape? Is it something valid for a PR?

My initial idea is to have an `module.action` entry like this:

```
modules:
  http_301:
    prober: http
    timeout: 2s
    action:
        command: "/home/mateus/getup/git/blackbox_exporter/action"
        timeout: 10s
    http:
      method: GET
      valid_status_codes: [301]
```
