### ISSUE TITLE
Bug: Large comment in configuration yaml causes crash

### ISSUE THREAD

**Issue by jamiely** [prometheus/blackbox_exporter#572]
### Host operating system: output of `uname -a`

docker image prom/blackbox-exporter:v0.16.0

### blackbox_exporter version: output of `blackbox_exporter -version`

v0.16.0

### What is the blackbox.yml module config.

```yaml
modules:
  # allows a mix of 2xx, 3xx, and 4xx status codes
  http_234xx:
    prober: http
    http:
      valid_status_codes: [200, 201, 202, 204, 300, 301, 302, 303, 304, 307, 308, 401, 403, 410]
      headers:
        User-Agent: "hi"
      tls_config:
        insecure_skip_verify: True
      # Do not follow redirects. We are just interested in the initial code.
      no_follow_redirects: true

#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#
#aaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaa
#aaaaaaaaaaaaaaaaaa
#aaaaaaaaa
#aaaaaaaaaaaaaaa
#aaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaa
#aaaaaaaaaaaaaaa
#aaaaaaaaaaaaa
#aaaaaaaaa
#aaaaaaa
#aaaaa
#aaaa
#
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaa
#aaaa
#
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaa
#
#aaaaaaaa
#a#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#a#aaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaa
#
#aaaaaaaaaaaaaa
#aaaa
#aaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
#?
```

### What is the prometheus.yml scrape config.

N/A

### What logging output did you get from adding `&debug=true` to the probe URL?

N/A

### What did you do that produced an error?

Run the container like so
```shell
docker run -it --rm -v $(pwd)/blackbox.yml:/etc/blackbox_exporter/config.yml prom/blackbox-exporter:v0.16.0
```

It will crash with the message below.

### What did you expect to see?

The program should start normally (this works fine in v0.12.0).

### What did you see instead?

```
level=info ts=2020-02-06T15:41:17.782Z caller=main.go:212 msg="Starting blackbox_exporter" version="(version=0.16.0, branch=HEAD, revision=991f89846ae10db22a3933356a7d196642fcb9a9)"
level=info ts=2020-02-06T15:41:17.782Z caller=main.go:213 msg="Build context" (gogo1.13.4,userroot@64f600555645,date20191111-16:27:24)=(MISSING)
panic: runtime error: index out of range [1536] with length 1536 [recovered]
	panic: runtime error: index out of range [1536] with length 1536

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc00007fb98)
	/app/vendor/gopkg.in/yaml.v3/yaml.go:276 +0x9a
panic(0xa80ee0, 0xc000022920)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
gopkg.in/yaml%2ev3.yaml_parser_update_buffer(0xc00004b880, 0x601, 0x501)
	/app/vendor/gopkg.in/yaml.v3/readerc.go:417 +0xb51
gopkg.in/yaml%2ev3.yaml_parser_scan_foot_comment(0xc00004b880, 0x18b, 0xb, 0x1b, 0xc00007f101)
	/app/vendor/gopkg.in/yaml.v3/scannerc.go:2846 +0x8fa
gopkg.in/yaml%2ev3.yaml_parser_fetch_next_token.func1(0xc00007f200, 0xc00004b880, 0x18b, 0xb, 0x1b)
	/app/vendor/gopkg.in/yaml.v3/scannerc.go:758 +0x8e
gopkg.in/yaml%2ev3.yaml_parser_fetch_next_token(0xc00004b880, 0xc0001d2701)
	/app/vendor/gopkg.in/yaml.v3/scannerc.go:875 +0x5bf
gopkg.in/yaml%2ev3.yaml_parser_fetch_more_tokens(0xc00004b880, 0xc00011c360)
	/app/vendor/gopkg.in/yaml.v3/scannerc.go:680 +0x55
gopkg.in/yaml%2ev3.peek_token(0xc00004b880, 0xc00011c360)
	/app/vendor/gopkg.in/yaml.v3/parserc.go:69 +0xa0
gopkg.in/yaml%2ev3.yaml_parser_parse_block_mapping_value(0xc00004b880, 0xc00004baf0, 0x6)
	/app/vendor/gopkg.in/yaml.v3/parserc.go:832 +0xd2
gopkg.in/yaml%2ev3.yaml_parser_state_machine(0xc00004b880, 0xc00004baf0, 0x13)
	/app/vendor/gopkg.in/yaml.v3/parserc.go:190 +0x2ad
gopkg.in/yaml%2ev3.yaml_parser_parse(0xc00004b880, 0xc00004baf0, 0xc0001517c0)
	/app/vendor/gopkg.in/yaml.v3/parserc.go:125 +0x91
gopkg.in/yaml%2ev3.(*parser).peek(0xc00004b880, 0xc0001517c0)
	/app/vendor/gopkg.in/yaml.v3/decode.go:102 +0x42
gopkg.in/yaml%2ev3.(*parser).parse(0xc00004b880, 0xc0001517c0)
	/app/vendor/gopkg.in/yaml.v3/decode.go:141 +0x3c
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc00004b880, 0xc000150820, 0xc0001517c0)
	/app/vendor/gopkg.in/yaml.v3/decode.go:184 +0x2f
gopkg.in/yaml%2ev3.(*parser).mapping(0xc00004b880, 0xc00000cf09)
	/app/vendor/gopkg.in/yaml.v3/decode.go:266 +0x128
gopkg.in/yaml%2ev3.(*parser).parse(0xc00004b880, 0xc00005c640)
	/app/vendor/gopkg.in/yaml.v3/decode.go:147 +0x185
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc00004b880, 0xc0001505a0, 0xc000150780)
	/app/vendor/gopkg.in/yaml.v3/decode.go:184 +0x2f
gopkg.in/yaml%2ev3.(*parser).mapping(0xc00004b880, 0xc00000e009)
	/app/vendor/gopkg.in/yaml.v3/decode.go:266 +0x128
gopkg.in/yaml%2ev3.(*parser).parse(0xc00004b880, 0x0)
	/app/vendor/gopkg.in/yaml.v3/decode.go:147 +0x185
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc00004b880, 0xc000150460, 0xc000150500)
	/app/vendor/gopkg.in/yaml.v3/decode.go:184 +0x2f
gopkg.in/yaml%2ev3.(*parser).mapping(0xc00004b880, 0xc00000e009)
	/app/vendor/gopkg.in/yaml.v3/decode.go:266 +0x128
gopkg.in/yaml%2ev3.(*parser).parse(0xc00004b880, 0x0)
	/app/vendor/gopkg.in/yaml.v3/decode.go:147 +0x185
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc00004b880, 0xc000150320, 0xc0001503c0)
	/app/vendor/gopkg.in/yaml.v3/decode.go:184 +0x2f
gopkg.in/yaml%2ev3.(*parser).mapping(0xc00004b880, 0xc00007fa09)
	/app/vendor/gopkg.in/yaml.v3/decode.go:266 +0x128
gopkg.in/yaml%2ev3.(*parser).parse(0xc00004b880, 0x0)
	/app/vendor/gopkg.in/yaml.v3/decode.go:147 +0x185
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc00004b880, 0xc000150280, 0x0)
	/app/vendor/gopkg.in/yaml.v3/decode.go:184 +0x2f
gopkg.in/yaml%2ev3.(*parser).document(0xc00004b880, 0x3)
	/app/vendor/gopkg.in/yaml.v3/decode.go:193 +0x94
gopkg.in/yaml%2ev3.(*parser).parse(0xc00004b880, 0xc00011e320)
	/app/vendor/gopkg.in/yaml.v3/decode.go:151 +0x140
gopkg.in/yaml%2ev3.(*Decoder).Decode(0xc00007fc60, 0xa0cce0, 0xc00000e088, 0x0, 0x0)
	/app/vendor/gopkg.in/yaml.v3/yaml.go:123 +0x118
github.com/prometheus/blackbox_exporter/config.(*SafeConfig).ReloadConfig(0xfe1da0, 0x7ffcdadfff51, 0x21, 0x0, 0x0)
	/app/config/config.go:105 +0x33f
main.run(0xc000088058)
	/app/main.go:215 +0x5f4
main.main()
	/app/main.go:200 +0x22

```

It just looks like a bounds error. You can remove the last character of the config, the `?` question mark, and it will start up fine. Maybe the previous parser version ignored comments and this version ingests them?
