### ISSUE TITLE
Blackbox are not recognizing another modules than not is http_2xx

### ISSUE THREAD

**Issue by overraidy** [prometheus/blackbox_exporter#580]
Hello 
I have the following issue with blackbox exporter module
Currently the blackbox are not recognized another module that no is http_2xx
These are my config files

# prometheus.yml

```yaml
  - job_name: 'blackbox'
    metrics_path: /probe
    file_sd_configs:
      - files:
          - '/etc/prometheus/blackbox/targets/*.yml'
    relabel_configs:
      - source_labels: [__address__]
        separator: ;
        regex: (.*)
        target_label: __param_target
        replacement: $1
        action: replace
      - source_labels: [__param_target]
        separator: ;
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
      - target_label: __address__
        replacement: prometheus.edgelan:9115 # The blackbox exporter
        action: replace
```		
# Blackbox		
# config.yml
```yaml
   modules:
      https_2xx:
        prober: http
        timeout: 5s
        http:
          method: GET
          no_follow_redirects: false
          fail_if_ssl: false
          fail_if_not_ssl: true
          preferred_ip_protocol: "ipv4"
      http_2xx:
        prober: http
        timeout: 5s
        http:
          method: GET
          no_follow_redirects: false
          fail_if_ssl: true
          fail_if_not_ssl: false
          preferred_ip_protocol: "ipv4"
```
#Target config files
# http_2xx.yml
```yaml
- labels:
    module: http_2xx
  targets:
  - http://www.stealmylogin.com/
```

# https_2xx.yml
```yaml
- labels:
    module: https_2xx
  targets:
  - https://www.sethryder.com
  - https://www.modpackindex.com
```
On the logs of the probe only matches with module http_2xx  but no the module https_2xx or another modules present on the config file
When i delete all the modules and only set the module https_2xx  the probe logs show **Unknown module "http_2xx"** that means what I said before, blackbox is not recognize another modules that no is http_2xx

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by kmille** [comment]
Have you found a solution @overraidy? I have the same problem right now. Trying to reproduce https://www.sethryder.com/blackbox-exporter-accessing-multiple-modules-and-targets-with-a-single-job/

**Comment by kmille** [comment]
Found the solution: we bot forgot to relabel the module label
```yaml
    - source_labels:
      - module
      target_label: __param_modul
```
Relabeling for multi-target exporter is described here: https://prometheus.io/docs/guides/multi-target-exporter/
