### ISSUE TITLE
Is there a limit on the number of monitoring blackbox_exporter?

### ISSUE THREAD

**Issue by fsckzy** [prometheus/blackbox_exporter#592]
I encountered a problem, when the number of targets monitored by blackbox is too large, a false positive will occur. Constantly alarming targets monitored timeout，I'm sure the URL was normal at the time
I tested with only one target left, and no alert was issued。
Turn on debug and no useful information found

prometheus.yml:
```yaml
scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # 模块对应 blackbox.yml 
    static_configs:
      - targets:
        - http://baidu.com    # http
        .......
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115 
```

blackbox.yml Use default configuration。

rules.yml
```yaml
groups:
  - name: http
    rules:
    - alert: xxx域名解析失败
      expr: probe_success{instance="https://xx.com"} == 0
      for: 1m
      labels:
        severity: "error"
      annotations:
        summary: "xxx域名解析失败"
    - alert: xxx域名解析失败
      expr: probe_http_status_code{instance="https://xx.com"} != 200
      for: 5m
      labels:
        severity: "error"
      annotations:
        summary: "xxx域名解析失败"
```
