### ISSUE TITLE
fail_if_body_matches_regexp invalid

### ISSUE THREAD

**Issue by cycwll** [prometheus/blackbox_exporter#598]
### blackbox_exporter version: output of `blackbox_exporter -version`

/ # blackbox_exporter --version
blackbox_exporter, version 0.16.0 (branch: master, revision: 37cda62aa5642120b96911dcb01911cfb015e47b)
  build user:       root@03aa892dd56f
  build date:       20200329-14:14:40
  go version:       go1.13.9

### What is the blackbox.yml module config.
```
modules:
  http_api:
    prober: http
    timeout: 10s
    http:
      preferred_ip_protocol: "ip4"
      method: GET
      tls_config:
        insecure_skip_verify: true
      fail_if_body_matches_regexp:
        - "12345"
```
### What is the prometheus.yml scrape config.
```
  - job_name: 'blackbox_http'
    scrape_interval: 60s
    scrape_timeout: 30s
    metrics_path: /probe
    params:
      module: [http_api]
    static_configs:
        - targets:
          - http://liktix0atc04:8080/springboot/getUserByGet?userName=12345
          labels:
            group: 'API monitoring'
    relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 127.0.0.1:9115 
```
### What did you expect to see?
curl http://liktix0atc04:8080/springboot/getUserByGet?userName=12345
the http response body：12345

because http response body is "12345", so I want to see alert.

### What did you see instead?
1. no any alert in Prometheus
2. state of endpoint is UP in Prometheus
