### ISSUE TITLE
Blackbox exporter resolve IPv6 when IPv4 prefer is specified.

### ISSUE THREAD

**Issue by riuvshyn** [prometheus/blackbox_exporter#602]
runtime: official docker image.
version: **master**

module:
```
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          no_follow_redirects: false
          preferred_ip_protocol: "ip4"
```
logs:
```
ts=2020-04-21T12:26:33.369Z caller=main.go:169 module=http_2xx target=https://database.clamav.net level=debug msg="Beginning probe" probe=http timeout_seconds=4.5
ts=2020-04-21T12:26:33.369Z caller=main.go:169 module=http_2xx target=https://database.clamav.net level=debug msg="Resolving target address" ip_protocol=ip4
ts=2020-04-21T12:26:33.371Z caller=main.go:169 module=http_2xx target=https://database.clamav.net level=debug msg="Resolved target address" ip=2606:4700::6810:da54
ts=2020-04-21T12:26:33.371Z caller=main.go:169 module=http_2xx target=https://database.clamav.net level=debug msg="Making HTTP request" url=https://[2606:4700::6810:da54] host=database.clamav.net
ts=2020-04-21T12:26:33.371Z caller=main.go:169 module=http_2xx target=https://database.clamav.net level=debug msg="Error for HTTP request" err="Get https://[2606:4700::6810:da54]: dial tcp [2606:4700::6810:da54]:443: connect: cannot assign requested address"
```

this is a floating thing that happens to 30% of probes. This happens also to many other targets so this is no target specific issue.
