### ISSUE TITLE
pass server_name as query parameter

### ISSUE THREAD

**Issue by sepich** [prometheus/blackbox_exporter#624]
### blackbox_exporter version: output of `blackbox_exporter -version`
0.16.0

We have to monitor many certificates installed on groups of hosts and being managed separately.
For example multiple backends behind single Load Balancer, answering by the same name.
Another use-case is monitoring HTTPS port on nodes behind Load Balancer, where certificate does not have specific node names, but only main VIP name.

Right now we have to manage both `blackbox-exporter` and `prometheus` configs like this:

### What is the blackbox.yml module config.
```yaml
# many sections like
  elk:
    prober: tcp
    timeout: 5s
    tcp:
      preferred_ip_protocol: ipv4
      tls: true
      tls_config:
        server_name: es.domain.local
# basically only differ in server_name
```

### What is the prometheus.yml scrape config.
```yaml
- job_name: blackbox
  metrics_path: /probe
  static_configs:
# many groups like this
    - labels:
        service: elk
        __params_module: [elk]
      targets: # es.domain.local
        - es-logs-node1.domain.local:443
        - es-logs-node2.domain.local:443
        - es-logs-node3.domain.local:443
        - es-logs-node1.domain.local:9300
        - es-logs-node2.domain.local:9300
        - es-logs-node3.domain.local:9300
        - es-logs-warm-node1.domain.local:9300
# only differ in hosts and module name
  relabel_configs:
  ...
```

### What did you expect to see?
Having ability to pass `server_name` via query parameter (like `module`) would greatly simplify things. So, we could manage config only on `prometheus` side.
