### ISSUE TITLE
probe_ssl_earliest_cert_expiry inconsistent or wrong

### ISSUE THREAD

**Issue by judos** [prometheus/blackbox_exporter#637]
With the blackbox exporter we get the information that the certificate is expired. The browser also told that the root certificate expired (on 30.May 2020), but now it has been refreshed and the blackbox_exporter still thinks it's expired.

### Host operating system: output of `uname -a`
Linux d0bac12bc1bf 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
runs inside a docker-container on the following system:
Linux s3 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
Docker version 18.06.1-ce, build e68fc7a

### blackbox_exporter version: output of `blackbox_exporter -version`
/ # blackbox_exporter --version
blackbox_exporter, version 0.16.0 (branch: HEAD, revision: 991f89846ae10db22a3933356a7d196642fcb9a9)
  build user:       root@64f600555645
  build date:       20191111-16:27:24
  go version:       go1.13.4

### What is the blackbox.yml module config.
```
modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4" # defaults to "ip6"
  http_post_2xx:
    prober: http
    http:
      method: POST
      preferred_ip_protocol: "ip4" # defaults to "ip6"
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp
```

### What is the prometheus.yml scrape config.
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://devedis.ch

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115 # Blackbox exporter.
```

### What logging output did you get from adding `&debug=true` to the probe URL?
```
Logs for the probe:
ts=2020-06-12T12:10:59.664339652Z caller=main.go:304 module=http_2xx target=https://devedis.ch level=info msg="Beginning probe" probe=http timeout_seconds=119.5
ts=2020-06-12T12:10:59.664748293Z caller=http.go:318 module=http_2xx target=https://devedis.ch level=info msg="Resolving target address" ip_protocol=ip4
ts=2020-06-12T12:10:59.665794232Z caller=http.go:318 module=http_2xx target=https://devedis.ch level=info msg="Resolved target address" ip=78.46.241.150
ts=2020-06-12T12:10:59.665945041Z caller=client.go:250 module=http_2xx target=https://devedis.ch level=info msg="Making HTTP request" url=https://78.46.241.150 host=devedis.ch
ts=2020-06-12T12:10:59.698091628Z caller=main.go:119 module=http_2xx target=https://devedis.ch level=info msg="Received HTTP response" status_code=200
ts=2020-06-12T12:10:59.703821353Z caller=main.go:119 module=http_2xx target=https://devedis.ch level=info msg="Response timings for roundtrip" roundtrip=0 start=2020-06-12T12:10:59.666171643Z dnsDone=2020-06-12T12:10:59.666171643Z connectDone=2020-06-12T12:10:59.674469756Z gotConn=2020-06-12T12:10:59.692290428Z responseStart=2020-06-12T12:10:59.698025722Z end=2020-06-12T12:10:59.703796685Z
ts=2020-06-12T12:10:59.704060616Z caller=main.go:304 module=http_2xx target=https://devedis.ch level=info msg="Probe succeeded" duration_seconds=0.039582196
```

### What did you do that produced an error?
Nothing except that the root certificate expired and was renewed

### What did you expect to see?
Blackbox_exporter notices that the root certificate in our chain has been refreshed

### What did you see instead?
Grafana alerting (via blackbox_exporter) tells us the certificate is still expired even so it's renewed.
![grafik](https://user-images.githubusercontent.com/5525810/84501945-b7bf9480-acb7-11ea-9db2-e5e0d6b9ba56.png)

The exact metric is:
```
# HELP probe_ssl_earliest_cert_expiry Returns earliest SSL cert expiry in unixtime
# TYPE probe_ssl_earliest_cert_expiry gauge
probe_ssl_earliest_cert_expiry 1.590835718e+09
```
Converting this unixtime gives me:
```
Your time zone: Samstag, 30. Mai 2020 12:48:38 GMT+02:00 DST
```
This was roughly 13days ago and *was* correct before the root cert was renewed.

Browser tells me our page has these certs in chain:
devedis.ch
25.2.2020, 01:00:00 (Mitteleuropäische Sommerzeit)
23.3.2022, 00:59:59 (Mitteleuropäische Sommerzeit)
Sectigo RSA Extended Validation Secure Server CA
2.11.2018, 01:00:00 (Mitteleuropäische Sommerzeit)
1.1.2031, 00:59:59 (Mitteleuropäische Sommerzeit)
USERTrust RSA Certification Authority
1.2.2010, 01:00:00 (Mitteleuropäische Sommerzeit)
19.1.2038, 00:59:59 (Mitteleuropäische Sommerzeit)

The ROOT Cert (USERTrust) expired on 30.May 2020 and was renewed to be valid till 19.1.2038 as you see.

Thanks for your help!

**Comment by brian-brazil** [comment]
Are you sure that your server still isn't sending along the old root cert? You'll likely need to check this with the openssl CLI tool.

**Comment by judos** [comment]
Hmm unsure. I'm not familiar with openssl cli tool. How would I check this?

**Comment by brian-brazil** [comment]
You need to look at all the certs, see https://serverfault.com/questions/661978/displaying-a-remote-ssl-certificate-details-using-cli-tools

If any cert being returned has expired, then this is not a bug.

**Comment by judos** [comment]
Ok so I tried this as well and I still don't see any invalid certificate. However I'm still unsure because it doesn't show certs of the chain with validity.

> echo | openssl s_client -showcerts -servername devedis.ch -connect devedis.ch:443 2>/dev/null
| openssl x509 -inform pem -noout -text

See output here:
https://pastebin.com/qsn8678j

I want to find out what we are doing wrong if our cert is actually expired, but right now I don't see anything. And if all major browsers show it as valid I think something else might be wrong.

My take on this now is that probably something goes wrong depending on the used protocol?
i.e. our Blackbox exporter has configured (config.yml):
```
modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4" # defaults to "ip6"
  http_post_2xx:
    prober: http
    http:
      method: POST
      preferred_ip_protocol: "ip4" # defaults to "ip6"
  tcp_connect:
    prober: tcp
[...]
```
And probably every browser uses ip6 instead?
