### ISSUE TITLE
"Invalid HTTP version number" messages after updating from 0.16.0 to 0.17.0 

### ISSUE THREAD

**Issue by dbluxo** [prometheus/blackbox_exporter#651]
### Host operating system: output of `uname -a`

`Linux blackbox-exporter-65dcf74f6-jmpvh 3.10.0-1127.10.1.el7.x86_64 #1 SMP Tue May 26 15:05:43 EDT 2020 x86_64 GNU/Linux`

### blackbox_exporter version: output of `blackbox_exporter -version`
```
blackbox_exporter, version 0.17.0 (branch: HEAD, revision: 1bc768014cf6815f7e9d694e0292e77dd10f3235)
  build user:       root@626fb3899f41
  build date:       20200619-11:54:41
  go version:       go1.14.4
```

### What is the blackbox.yml module config.

```
modules:
  http_2xx:
    http:
      fail_if_not_ssl: false
      fail_if_ssl: false
      method: GET
      no_follow_redirects: false
      preferred_ip_protocol: ip4
      tls_config:
        insecure_skip_verify: true
      valid_http_versions:
      - HTTP/2
      - HTTP/1.1
    prober: http
    timeout: 15s
```

### What is the prometheus.yml scrape config.

```
- job_name: blackbox-exporter
  honor_timestamps: true
  params:
    module:
    - http_2xx
  scrape_interval: 30s
  scrape_timeout: 15s
  metrics_path: /probe
  scheme: http
  static_configs:
  - targets:
    - https://anonymized.de/-/health
  relabel_configs:
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    target_label: __param_target
    replacement: $1
    action: replace
  - source_labels: [__param_target]
    separator: ;
    regex: (.*)
    target_label: instance
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: __address__
    replacement: blackbox-exporter:9115
    action: replace
```

### What logging output did you get from adding `&debug=true` to the probe URL?

```
ts=2020-06-24T09:19:49.883Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Beginning probe" probe=http timeout_seconds=14.5
ts=2020-06-24T09:19:49.883Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Resolving target address" ip_protocol=ip4
ts=2020-06-24T09:19:49.889Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Resolved target address" ip=1.2.3.4
ts=2020-06-24T09:19:49.889Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Making HTTP request" url=https://1.2.3.4/-/health  host=anonymized.de
ts=2020-06-24T09:19:49.962Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Received HTTP response" status_code=200
ts=2020-06-24T09:19:49.962Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Invalid HTTP version number" version=2
ts=2020-06-24T09:19:49.962Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Response timings for roundtrip" roundtrip=0 start=2020-06-24T09:19:49.890046003Z dnsDone=2020-06-24T09:19:49.890046003Z connectDone=2020-06-24T09:19:49.891731393Z gotConn=2020-06-24T09:19:49.958483533Z responseStart=2020-06-24T09:19:49.962196258Z end=2020-06-24T09:19:49.96242622Z
ts=2020-06-24T09:19:49.962Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Probe failed" duration_seconds=0.079005369
```

### What did you do that produced an error?

I left the configuration unchanged and only updated the Docker image tag from v0.16.0 to v0.17.0.

### What did you expect to see?

Log messages with the v0.16.0 image:
```
ts=2020-06-24T09:16:19.877Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Beginning probe" probe=http timeout_seconds=14.5
ts=2020-06-24T09:16:19.877Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Resolving target address" ip_protocol=ip4
ts=2020-06-24T09:16:19.927Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Resolved target address" ip=1.2.3.4
ts=2020-06-24T09:16:19.927Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Making HTTP request" url=https://1.2.3.4/-/health  host=anonymized.de
ts=2020-06-24T09:16:19.937Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Received HTTP response" status_code=200
ts=2020-06-24T09:16:19.937Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Response timings for roundtrip" roundtrip=0 start=2020-06-24T09:16:19.927476311Z dnsDone=2020-06-24T09:16:19.927476311Z connectDone=2020-06-24T09:16:19.929481616Z gotConn=2020-06-24T09:16:19.9338308Z responseStart=2020-06-24T09:16:19.937501176Z end=2020-06-24T09:16:19.937645025Z
ts=2020-06-24T09:16:19.937Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Probe succeeded" duration_seconds=0.060410506
```

### What did you see instead?

```
ts=2020-06-24T09:19:49.883Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Beginning probe" probe=http timeout_seconds=14.5
ts=2020-06-24T09:19:49.883Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Resolving target address" ip_protocol=ip4
ts=2020-06-24T09:19:49.889Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Resolved target address" ip=1.2.3.4
ts=2020-06-24T09:19:49.889Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Making HTTP request" url=https://1.2.3.4/-/health  host=anonymized.de
ts=2020-06-24T09:19:49.962Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Received HTTP response" status_code=200
ts=2020-06-24T09:19:49.962Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Invalid HTTP version number" version=2
ts=2020-06-24T09:19:49.962Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Response timings for roundtrip" roundtrip=0 start=2020-06-24T09:19:49.890046003Z dnsDone=2020-06-24T09:19:49.890046003Z connectDone=2020-06-24T09:19:49.891731393Z gotConn=2020-06-24T09:19:49.958483533Z responseStart=2020-06-24T09:19:49.962196258Z end=2020-06-24T09:19:49.96242622Z
ts=2020-06-24T09:19:49.962Z caller=main.go:169 module=http_2xx target=https://anonymized.de/-/health  level=debug msg="Probe failed" duration_seconds=0.079005369
```
