### ISSUE TITLE
Serious bug: Detect wrong url, status is still up

### ISSUE THREAD

**Issue by smarterallen** [prometheus/blackbox_exporter#661]
cat prometheus.yml :
```
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
         - http://www.ttttttestbaidu.com
    #file_sd_configs:
     # - files:
     #   - 'sd_configs/http.yml'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
```

Serious bug: Detect wrong url, prometheus targets dashboard status is still up!
Do you know what the problem is？
