### ISSUE TITLE
How to add multiple hosts?

### ISSUE THREAD

**Issue by offlinejke** [prometheus/blackbox_exporter#666]
Hello!
I'm interested in ssl monitoring on big amount of sites.

```
modules:
  http_2xx_example:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      headers:
      Host: 
        https://vhost1.example.com
        https://vhost2.example.com
```
My question is am i write hosts correctly or how should i do it?
