### ISSUE TITLE
Update to 0.17.0 causes certain checks to fail on probe_success

### ISSUE THREAD

**Issue by stewartshea** [prometheus/blackbox_exporter#672]
### Host operating system: output of `uname -a`
```
Linux blackbox-exporter-65f96db868-d7nwg 3.10.0-1127.8.2.el7.x86_64 #1 SMP Thu May 7 19:30:37 EDT 2020 x86_64 GNU/Linux
```

### blackbox_exporter version: output of `blackbox_exporter -version`

```
blackbox_exporter, version 0.17.0 (branch: HEAD, revision: 1bc768014cf6815f7e9d694e0292e77dd10f3235)
  build user:       root@626fb3899f41
  build date:       20200619-11:54:41
  go version:       go1.14.4
```

### What is the blackbox.yml module config.

```
modules:
    http_2xx:
      prober: http
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2"]
        valid_status_codes: []  # Defaults to 2xx
        method: GET
        preferred_ip_protocol: "ip4" # defaults to "ip6"
        ip_protocol_fallback: false  # no fallback to "ip6"
    http_2xx__no_tls_verify:
      prober: http
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2"]
        valid_status_codes: []  # Defaults to 2xx
        method: GET
        preferred_ip_protocol: "ip4" # defaults to "ip6"
        ip_protocol_fallback: false  # no fallback to "ip6"
        tls_config:
          insecure_skip_verify: true
    http_ocp_status_green:
      prober: http
      timeout: 5s
      http:
        method: GET
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        fail_if_body_not_matches_regexp:
          - '.*"status":"green".*'
    http_post_2xx:
      prober: http
      http:
        method: POST
    tcp_connect:
      prober: tcp
    pop3s_banner:
      prober: tcp
      tcp:
        query_response:
        - expect: "^+OK"
        tls: true
        tls_config:
          insecure_skip_verify: true
```

### What logging output did you get from adding `&debug=true` to the probe URL?
Added debug to the full deployment and compared 0.17.0 to 0.16.0
**0.17.0**
```
ts=2020-08-11T20:27:33.088Z caller=main.go:169 module=http_2xx target=https://console.pathfinder.gov.bc.ca:8443/healthz  level=debug msg="Beginning probe" probe=http timeout_seconds=9.5
ts=2020-08-11T20:27:33.088Z caller=main.go:169 module=http_2xx target=https://console.pathfinder.gov.bc.ca:8443/healthz  level=debug msg="Resolving target address" ip_protocol=ip4
ts=2020-08-11T20:27:33.160Z caller=main.go:169 module=http_2xx target=https://console.pathfinder.gov.bc.ca:8443/healthz  level=debug msg="Resolved target address" ip=142.34.208.210
ts=2020-08-11T20:27:33.160Z caller=main.go:169 module=http_2xx target=https://console.pathfinder.gov.bc.ca:8443/healthz  level=debug msg="Making HTTP request" url=https://142.34.208.210:8443/healthz  host=console.pathfinder.gov.bc.ca:8443
ts=2020-08-11T20:27:33.173Z caller=main.go:169 module=http_2xx target=https://console.pathfinder.gov.bc.ca:8443/healthz  level=debug msg="Received HTTP response" status_code=200
ts=2020-08-11T20:27:33.173Z caller=main.go:169 module=http_2xx target=https://console.pathfinder.gov.bc.ca:8443/healthz  level=debug msg="Invalid HTTP version number" version=2
ts=2020-08-11T20:27:33.173Z caller=main.go:169 module=http_2xx target=https://console.pathfinder.gov.bc.ca:8443/healthz  level=debug msg="Response timings for roundtrip" roundtrip=0 start=2020-08-11T20:27:33.160438547Z dnsDone=2020-08-11T20:27:33.160438547Z connectDone=2020-08-11T20:27:33.162966073Z gotConn=2020-08-11T20:27:33.170289611Z responseStart=2020-08-11T20:27:33.172981602Z end=2020-08-11T20:27:33.173223556Z
ts=2020-08-11T20:27:33.173Z caller=main.go:169 module=http_2xx target=https://console.pathfinder.gov.bc.ca:8443/healthz  level=debug msg="Probe failed" duration_seconds=0.085291818
```

**0.16.0**
```
ts=2020-08-11T20:29:33.098Z caller=main.go:169 module=http_2xx target=https://console.pathfinder.gov.bc.ca:8443/healthz  level=debug msg="Resolved target address" ip=142.34.208.210
ts=2020-08-11T20:29:33.098Z caller=main.go:169 module=http_2xx target=https://console.pathfinder.gov.bc.ca:8443/healthz  level=debug msg="Making HTTP request" url=https://142.34.208.210:8443/healthz  host=console.pathfinder.gov.bc.ca:8443
ts=2020-08-11T20:29:33.109Z caller=main.go:169 module=http_2xx target=https://console.pathfinder.gov.bc.ca:8443/healthz  level=debug msg="Received HTTP response" status_code=200
ts=2020-08-11T20:29:33.109Z caller=main.go:169 module=http_2xx target=https://console.pathfinder.gov.bc.ca:8443/healthz  level=debug msg="Response timings for roundtrip" roundtrip=0 start=2020-08-11T20:29:33.098757386Z dnsDone=2020-08-11T20:29:33.098757386Z connectDone=2020-08-11T20:29:33.101929802Z gotConn=2020-08-11T20:29:33.107347699Z responseStart=2020-08-11T20:29:33.109190658Z end=2020-08-11T20:29:33.10929082Z
ts=2020-08-11T20:29:33.109Z caller=main.go:169 module=http_2xx target=https://console.pathfinder.gov.bc.ca:8443/healthz  level=debug msg="Probe succeeded" duration_seconds=0.021902981
```

### What did you do that produced an error?
Update to the 0.17.0 container image. 

### What did you expect to see?
Successful probes for all functional URLs. 

### What did you see instead?
Many probes returning a 0 rather than a 1. Downgrading to 0.16.0 returns a 1.
