### ISSUE TITLE
multiple hosts

### ISSUE THREAD

**Issue by LeoSkyeer** [prometheus/blackbox_exporter#679]
### Host operating system: output of `uname -a`
`Linux 3.10.0-957.5.1.el7.x86_64 `

### blackbox_exporter version: output of `blackbox_exporter -version`
`version=0.17.0`

### What is the blackbox.yml module config.
```
modules:
  http_2xx:
    prober: http
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp
```

### What is the prometheus.yml scrape config.
```
scrape_configs:
   - job_name: 'mobile_api'
    params:
      module:
        - http_2xx
    metrics_path: /probe
    static_configs:
      - targets:
          - http://test.test1.ru:8080/health
          - http://test.test2.ru:8080/health
          - http://test.test3.ru:8080/health
          - http://test.test4.ru:8080/health
    relabel_configs:
      - source_labels: [__address__]
        separator: ;
        regex: (.*):\d.+
        target_label: __param_target
        replacement: ${1}
        action: replace
      - source_labels: [__param_target]
        separator: ;
        regex:         ^([a-zA-Z0-9]*)_.+
        target_label:  instance
        replacement: ${1}
        action: replace
      - separator: ;
        regex: (.*)
        target_label: __address__
        replacement: 10.0.3.161:9115
        action: replace
```

Configuration succeed, but i have a problem. When i try to collect any metrics from multiple host i have only 1 hosts to choose.

### What did you expect to see?
Something like that 
![Screenshot_20200819_172314](https://user-images.githubusercontent.com/20158873/90604817-c6d73b80-e240-11ea-9bf1-c5bdfa0bc041.png)

### What did you see instead?
![Screenshot_20200819_171704](https://user-images.githubusercontent.com/20158873/90604279-f46fb500-e23f-11ea-8990-59e774ef34dd.png)

How can i change my config files, to see different hosts?
Tnank you!
