### ISSUE TITLE
Regression in 0.17.0 when handling HTTP/2 responses

### ISSUE THREAD

**Issue by chancez** [prometheus/blackbox_exporter#691]
### blackbox_exporter version: output of `blackbox_exporter -version`
v0.17.0

### What is the blackbox.yml module config.

```
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      no_follow_redirects: false
      preferred_ip_protocol: "ip4"
```

### Error

When https://github.com/prometheus/blackbox_exporter/pull/622 was added it also added HTTP2 support which caused the above config to fail due the issue mentioned in https://github.com/prometheus/blackbox_exporter/pull/633.

When we updated blackbox exporter from 0.16.0 to 0.17.0 a few of our HTTP probes started failing because our config used `HTTP/2` instead of `HTTP/2.0`. 

### Expected Behavior

Blackbox exporter should handle `HTTP/2` as `HTTP/2.0`, or the underlying HTTP2 library should be fixed to return the correct response.

### Suggestion

Simply treat `HTTP/2` as `HTTP/2.0` in https://github.com/prometheus/blackbox_exporter/blob/master/prober/http.go#L517.
