### ISSUE TITLE
icmp ping functionality like tcp

### ISSUE THREAD

**Issue by yabetsu93** [prometheus/blackbox_exporter#693]
### What is the blackbox.yml module config.
currently icmp has no ping functionality like tcp if user wants to use ping functionality with icmp probe, do they have to use tcp?
currently:
```
icmp module:
icmp_test:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: ip4

tcp:
irc_banner:
    prober: tcp
    timeout: 5s
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
```

feature request:
```
icmp_test:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: ip4
      query_response:
       - send: "NICK prober"
       - send: "USER prober prober prober :prober"
       - expect: "PING :([^ ]+)"
         send: "PONG ${1}"
       - expect: "^:[^ ]+ 001"
```
Is it possible to have this in icmp?
