### ISSUE TITLE
preferred_ip_protocol: "ip4" not honoured

### ISSUE THREAD

**Issue by docapotamus** [prometheus/blackbox_exporter#698]
### Host operating system:
Linux REDACTED 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux

### blackbox_exporter version:
blackbox_exporter, version 0.17.0 (branch: HEAD, revision: 1bc768014cf6815f7e9d694e0292e77dd10f3235)
  build user:       root@626fb3899f41
  build date:       20200619-11:54:41
  go version:       go1.14.4

### What is the blackbox.yml module config.
```yaml
modules:
  http_2xx:
    prober: http
    timeout: 3s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      method: GET
      fail_if_no_ssl: true
      preferred_ip_protocol: "ip4"
      tls_config:
        insecure_skip_verify: false
```

### What is the prometheus.yml scrape config.
```yaml
- job_name: blackbox
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
    - targets:
      - https://REDACTED
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [_param_target]
      target_label: instance
    - target_label: __address__
      replacement: prometheus-blackbox-exporter:9115
```

### What logging output did you get from adding `&debug=true` to the probe URL?
```
Logs for the probe:
ts=2020-10-11T21:57:17.801594715Z caller=main.go:304 module=http_2xx target=https://google.com level=info msg="Beginning probe" probe=http timeout_seconds=119.5
ts=2020-10-11T21:57:17.801736005Z caller=http.go:323 module=http_2xx target=https://google.com level=info msg="Resolving target address" ip_protocol=ip6
ts=2020-10-11T21:57:17.80417955Z caller=http.go:323 module=http_2xx target=https://google.com level=info msg="Resolved target address" ip=2a00:1450:400e:809::200e
ts=2020-10-11T21:57:17.804261453Z caller=client.go:252 module=http_2xx target=https://google.com level=info msg="Making HTTP request" url=https://[2a00:1450:400e:809::200e] host=google.com
ts=2020-10-11T21:57:17.804412938Z caller=main.go:119 module=http_2xx target=https://google.com level=error msg="Error for HTTP request" err="Get \"https://[2a00:1450:400e:809::200e]\": dial tcp [2a00:1450:400e:809::200e]:443: connect: cannot assign requested address"
ts=2020-10-11T21:57:17.804445178Z caller=main.go:119 module=http_2xx target=https://google.com level=info msg="Response timings for roundtrip" roundtrip=0 start=2020-10-11T21:57:17.804344061Z dnsDone=2020-10-11T21:57:17.804344061Z connectDone=2020-10-11T21:57:17.804399739Z gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z end=0001-01-01T00:00:00Z
ts=2020-10-11T21:57:17.804464797Z caller=main.go:304 module=http_2xx target=https://google.com level=error msg="Probe failed" duration_seconds=0.002815239



Metrics that would have been returned:
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.00246734
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.002815239
# HELP probe_failed_due_to_regex Indicates if probe failed due to regex
# TYPE probe_failed_due_to_regex gauge
probe_failed_due_to_regex 0
# HELP probe_http_content_length Length of http content response
# TYPE probe_http_content_length gauge
probe_http_content_length 0
# HELP probe_http_duration_seconds Duration of http request by phase, summed over all redirects
# TYPE probe_http_duration_seconds gauge
probe_http_duration_seconds{phase="connect"} 0
probe_http_duration_seconds{phase="processing"} 0
probe_http_duration_seconds{phase="resolve"} 0.00246734
probe_http_duration_seconds{phase="tls"} 0
probe_http_duration_seconds{phase="transfer"} 0
# HELP probe_http_redirects The number of redirects
# TYPE probe_http_redirects gauge
probe_http_redirects 0
# HELP probe_http_ssl Indicates if SSL was used for the final redirect
# TYPE probe_http_ssl gauge
probe_http_ssl 0
# HELP probe_http_status_code Response HTTP status code
# TYPE probe_http_status_code gauge
probe_http_status_code 0
# HELP probe_http_uncompressed_body_length Length of uncompressed response body
# TYPE probe_http_uncompressed_body_length gauge
probe_http_uncompressed_body_length 0
# HELP probe_http_version Returns the version of HTTP of the probe response
# TYPE probe_http_version gauge
probe_http_version 0
# HELP probe_ip_addr_hash Specifies the hash of IP address. It's useful to detect if the IP address changes.
# TYPE probe_ip_addr_hash gauge
probe_ip_addr_hash 6.25164632e+08
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 6
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0



Module configuration:
prober: http
http:
    ip_protocol_fallback: true
tcp:
    ip_protocol_fallback: true
icmp:
    ip_protocol_fallback: true
dns:
    ip_protocol_fallback: true
```

### What did you do that produced an error?
```
/probe?module=http_2xx&target=https%3A%2F%2Fgoogle.com&debug=true
```

### What did you expect to see?
Blackbox exporter resolve an IPv4 address.

### What did you see instead?
It failed because it couldn't communicate over IPv6

### Additional information
I do not have IPv6 enabled inside Docker, but I did expect for "ip4" setting to work in this case.

Happy to provide any more information as needed.

Thanks
