### ISSUE TITLE
ICMP reports up=1 although host is down

### ISSUE THREAD

**Issue by simonszu** [prometheus/blackbox_exporter#70]
Hi,

i have a problem that the ICMP probe reports up=1 although the host is down. 
This is the snippet of my blackbox.yml:

```
modules:
  ping:
    prober: icmp
    timeout: 5s
    icmp:
      protocol: "icmp"
      preferred_ip_protocol: "ip4"
```

This is the according snippet of my prometheus.yml:

```
  - job_name: 'ping'
    metrics_path: /probe
    params: 
      module: [ping]
    static_configs:
      - targets:
        - cram
    relabel_configs:
      # Set the target's address as the target-GET-parameter for the blackbox exporter
      - source_labels: [__address__]
        regex: (.*)
        target_label: __param_target
        replacement: ${1}
      # Set the target's address as the instance name
      - source_labels: [__address__]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      # Set the scrape address to the blackbox exporter
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 127.0.0.1:9115
```

The `relabel_configs` are almost directly copy&pasted from the github README. 

So the host `cram` did exist in the network, but is currently down, but the exporter reports it as up. 

This is the output of the ping command: 

```
$ ping cram
PING cram.home.simonszu.de (192.168.1.15) 56(84) bytes of data.
From tirn.home.simonszu.de (192.168.1.9) icmp_seq=1 Destination Host Unreachable
From tirn.home.simonszu.de (192.168.1.9) icmp_seq=2 Destination Host Unreachable
From tirn.home.simonszu.de (192.168.1.9) icmp_seq=3 Destination Host Unreachable
^C
--- cram.home.simonszu.de ping statistics ---
5 packets transmitted, 0 received, +3 errors, 100% packet loss, time 4005ms
```

Please note that the host `tirn` is my dedicated monitoring server, running prometheus and the blackbox exporter. 

So i think this is a bug, or at least not the intended behaviour. I am no ICMP expert, but i think it has something to do with the fact that the `ping` command returns at least _something_. 

I am using latest prometheus and blackbox_exporter on armv7.
