### ISSUE TITLE
Support HTTP probes through PROXY protocol v1/v2

### ISSUE THREAD

**Issue by bgagnon** [prometheus/blackbox_exporter#701]
The [PROXY protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) is commonly used on load balancers for preserving the client IP address and encapsulating this in a "header" at the start of the TCP conversation.

Per the specification, this header _must_ be sent by clients or the connection is dropped. To probe services behind a PROXY protocol, blackbox_exporter must thus include this simple header.

Now, one could argue the TCP probe module is sufficient, but this significantly reduces the flexibility and richness of metrics emitted by blackbox_exporter.

Suggested config:

```yaml
prober: http
http:
  proxy_protocol_header: <bool>
  proxy_protocol_version: <v1|v2>
```

When `true` with `v1`, a probe might send this data over the socket:

```
    PROXY TCP4 192.168.0.1 192.168.0.11 56324 443\r\n
    GET / HTTP/1.1\r\n
    Host: 192.168.0.11\r\n
    \r\n
```

Or for any generic TCP probe:

```yaml
prober: tcp
tcp:
  proxy_protocol_header: <bool>
  proxy_protocol_version: <v1|v2>
``` 

Potential Golang implementation candidates:
* [pires/go-proxyproto](https://github.com/pires/go-proxyproto)
* [armon/go-proxyproto](https://github.com/armon/go-proxyproto)

**Comment by brian-brazil** [comment]
> Now, one could argue the TCP probe module is sufficient, but this significantly reduces the flexibility and richness of metrics emitted by blackbox_exporter.

What is it exactly you're trying to test here? It's the proxy that you're talking to, and thus that's what you're really testing. If you wanted richer metrics about what's behind it I'd expect you'd be better probing the backends directly.

**Comment by bgagnon** [comment]
Here's the current workaround using tcp probe and a fake/bogus `PROXY` header:

```yaml
modules:
    proxy_http:
        prober: tcp
        tcp:
            preferred_ip_protocol: ip4
            query_response:
              - send: "PROXY TCP4 169.254.0.1 169.254.0.1 54321 80\r"
              - send: "GET / HTTP/1.1\r"
              - send: "Host: host.domain.com\r"
              - send: "User-Agent: blackbox_exporter/v0.17.0\r"
              - send: "\r"
              - expect: HTTP/1.1 200 OK
```

> What is it exactly you're trying to test here? It's the proxy that you're talking to, and thus that's what you're really testing.

In true "blackbox" philosophy, this is testing that the load balancer is:

* responding
* performing its duties
* without knowing the internals

Since the goal of a load balancer is to balance requests to backend destination, end-to-end testing requires that the probe reaches one of these destinations. Otherwise, the probe can't conclude that the LB is indeed doing its intended job.

To be clear, I am _also_ probing the multiple backend destinations (with k8s liveness probes and not blackbox_exporter, but that's beside the point).
