### ISSUE TITLE
blackbox_exporter can be supply ip and port 

### ISSUE THREAD

**Issue by FunkyYang** [prometheus/blackbox_exporter#704]
OS:ubuntu20.04
blackbox version:0.18.1
sample blackbox.yml.
```
- job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]  
    static_configs:
      - targets:
        - http://192.168.2.xxxx:xxx/ad/service/status 
        - http://192.168.2.xxxx:xxxx/conf/service/status
        - http://192.168.2.xxxx:xxxxx/api/v1/site 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115
```
black_exporter is working for me .and I want to get ip and port variable in metrics.but I did not find them
.
