### ISSUE TITLE
ICMP probe fails to recover after 1hr outage, recovers immediately on exporter restart

### ISSUE THREAD

**Issue by danpoltawski** [prometheus/blackbox_exporter#705]
We have been getting a reoccurring problem where icmp probes fail to recover after an outage of an hour or so, when we restart the exporter the probe immediately recovers. In the meantime other icmp probes (and other blackbox probes (tcp/http)) continue to work fine and recover fine so it seems to be a peculiarity of icmp.

I have been trying to establish a simple reproducible testcase for this by firewalling off icmp on a simple probe for an hour and things recover as expected. I've also repeating the same number of probes as we have in production and this works fine. So I think this is some peculiarity of our setup is triggering this bug. 

**Of note:** The nodes we are probing where i've noticed this problem are at the other end of VPN and when they fail the intermediary router would fail - so I wonder if it's something icmp'y from the intermediary router which is causing this problem.

### Host operating system: 
Linux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

### blackbox_exporter version: 
```
blackbox_exporter, version 0.17.0 (branch: HEAD, revision: 1bc768014cf6815f7e9d694e0292e77dd10f3235)
  build user:       root@626fb3899f41
  build date:       20200619-11:54:41
  go version:       go1.14.4
```

### What is the blackbox.yml module config.
```
---
modules:
  icmp4:
    prober: icmp
    icmp:
      preferred_ip_protocol: ip4
```
### What is the prometheus.yml scrape config.
```
- job_name: icmp4
  scrape_interval: 30s
  metrics_path: /probe
  params:
    module:
      - icmp4
  file_sd_configs:
    - files:
      - /etc/prometheus-hosts/internal/blackbox-icmp4.yaml
      - /etc/prometheus-hosts/external/blackbox-icmp4.yaml
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
```
### What logging output did you get from adding `&debug=true` to the probe URL?

I'm afraid I don't have this output, but I will strive to get it next time I encounter this failure

### What did you do that produced an error?

No error - incorrect `probe_success` value

### What did you expect to see?

probe_success = 1
### What did you see instead?
probe_success = 0
