### ISSUE TITLE
Validating config should try to compile regexes

### ISSUE THREAD

**Issue by roidelapluie** [prometheus/blackbox_exporter#717]
### blackbox_exporter version:

10b04fc9fd220343938233c5586556f7e84a2f45

### What is the blackbox.yml module config.

```
modules:
  http_proxy_sna_monitor:
    prober: http
    http:
      fail_if_body_not_matches_regexp: ['{"status":"ok","components":[']
```

### logs

```
ts=2020-12-02T09:22:07.826147753Z caller=http.go:456 module=http_proxy_sna_monitor target=https://X/status/monitor level=error msg="Could not compile regular expression" regexp="{\"status\":\"ok\",\"components\":[" err="error parsing regexp: missing closing ]: `[`"
```

I think we could compile regexes when reloading config to make this more obvious to users.

### What did you do that produced an error?

I wrote a bad config file with a wring regex, and got an error at runtime

### What did you expect to see?

An error while reloading config, not runtime.

### What did you see instead?

Error at probe time.
