### ISSUE TITLE
option to ignore certificate

### ISSUE THREAD

**Issue by EvertMDC** [prometheus/blackbox_exporter#73]
When starting the blackbox exporter with the insecure_skip_verify, it fails on the certificate.
According to issue  #41 this options was to allow self-signed certificates I imagine so this is to be expected.

Would it be possible to add an option to ignore the certificate alltogether?

In the below usecase I probe for machine.example.com instead of www.example.com to bypass DNS geo load balancing. Adding the domain to the certificate will make the domain known to everyone who checks the certificate so not a solution.

The curl equivalent would be
`curl -k machine.example.com
`
wget would do it as follows
`wget --no-check-certificate machine.example.com
`
> time="2016-11-04T12:41:19Z" level=warning msg="Error for HTTP request to https://machine.example.com: Get https://machine.example.com: x509: certificate is valid for www.example.com, not machine.example.com" source="http.go:97"

**Comment by brian-brazil** [comment]
insecure_skip_verify should work here.

**Comment by brian-brazil** [comment]
I cannot reproduce this issue using https://wrong.host.badssl.com/, insecure_skip_verify is working as expected and ignoring all ssl related errors.

**Comment by EvertMDC** [comment]
Ok my bad I accidentally added the https:// to the target while copy-pasting.
Thank you for checking.

**Comment by Priyotosh008** [comment]
Can you please tell me where to add "insecure_skip_verify" ?
I have added it in blackbox.yml and it still throws SSL errors in logs.

Blackbox configuration:

************************
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      preferred_ip_protocol: "ip4"
      http_config:
        insecure_skip_verify: true
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: false
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp

***********************
Error in logs:
**time="2017-09-13T18:16:26Z" level=error msg="Error for HTTP request to https://171.76.45.17:2243/sst/status.html: Get https://171.76.45.17:2243/sst/status.html: x509: certificate is valid for 171.17.29.43, 82.10.23.1, not 171.76.45.16" source="http.go:178"**

NOTE: I always see a 0 value for probe_http_status_code in prometheus even if the URL i am monitoring is up and running.

**Comment by thz** [comment]
@Priyotosh008, `insecure_skip_verify` is below `tls_config` which is a sibling of `method` and below `http`. 
Have a look at line 19 of the example.yml: https://github.com/prometheus/blackbox_exporter/blob/master/example.yml#L19

**Comment by yrro** [comment]
> @Priyotosh008, `insecure_skip_verify` is below `tls_config` which is a sibling of `method` and below `http`.
> Have a look at line 19 of the example.yml: https://github.com/prometheus/blackbox_exporter/blob/master/example.yml#L19

Updated link: https://github.com/prometheus/blackbox_exporter/blob/bf70c7d9969a11cea7e5d5ea2f4beb3042eaf432/example.yml#L28

**Comment by vleyong** [comment]
> [@Priyotosh008](https://github.com/Priyotosh008), `insecure_skip_verify` is below `tls_config` which is a sibling of `method` and below `http`. Have a look at line 19 of the example.yml: https://github.com/prometheus/blackbox_exporter/blob/master/example.yml#L19

Hi：
I wanna skip the certificates valid,so I add insecure_skip_verify: true in the blackbox.yml，but it's still get reponse code 0 rather than 200,I try to curl  -I http://10.1.1.161:9115/probe?module=http_2xx&target=https://10.101.1.112:8850,log tips me that I got unknown or invalid certificate,so I use  curl   -k http://10.1.1.161:9115/probe?module=http_2xx&target=https://10.101.1.112:8850,it can access the target web page,so I have no idea what the promblem is.
blackbox.yml:
```
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      method: GET
      preferred_ip_protocol: "ip4"
      ip_protocol_fallback: false
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
         nsecure_skip_verify: true
```
Prometheus.yml:
```
static_configs:
      - targets:
          - https://tableau.myservice.com:8850
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        # Blackbox Exporter
        replacement: 10.1.1.161:9115
      - source_labels: [__param_target]
        target_label: service
        replacement: 'service management'  # https://10.101.1.112:8850
        regex: '.*tableau\.myservice\.com:8850.*'
```
