### ISSUE TITLE
 msg="Error loading config" err="error parsing config file: yaml: unmarshal errors:\n  line 6: field vaild_http_versions not found in type config.plain\n  line 7: field vaild_status_codes not found in type config.plain"

### ISSUE THREAD

**Issue by ylmcr7** [prometheus/blackbox_exporter#747]
this is my deployment.yaml

```yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: blackbox-exporter
  namespace: kube-system
  labels:
    app: blackbox-exporter
  annotations:
    deployment.kubernetes.io/revision: 1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      volumes:
      - name: config
        configMap:
          name: blackbox-exporter
          defaultMode: 420
      containers:
      - name: blackbox-exporter
        image: harbor.od.com/public/blackbox-exporter:v0.15.1
        imagePullPolicy: IfNotPresent
        args:
        - --config.file=/etc/blackbox-exporter/blackbox.yml
        - --log.level=info
        - --web.listen-address=:9115
        ports:
        - name: blackbox-port
          containerPort: 9115
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - name: config
          mountPath: /etc/blackbox_exporter
        readinessProbe:
          tcpSocket:
            port: 9115
          initialDelaySeconds: 5
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
```
this is status CrashLoopBackOff
```bash
[root@hdss7-21 ~]# kubectl get pod -n kube-system
NAME                                    READY   STATUS             RESTARTS   AGE
blackbox-exporter-79d6977f8d-q25cs      0/1     CrashLoopBackOff   1          10s
```

this is my log
```bash
[root@hdss7-21 ~]# kubectl logs -f blackbox-exporter-79d6977f8d-q25cs -n kube-system
level=info ts=2021-02-12T02:35:45.352Z caller=main.go:212 msg="Starting blackbox_exporter" version="(version=0.15.1, branch=HEAD, revision=7dd86a593b5a2270e738be1654d9c112509e46ce)"
level=info ts=2021-02-12T02:35:45.353Z caller=main.go:213 msg="Build context" (gogo1.13,userroot@626ba8fd110c,date20190917-12:31:25)=(MISSING)
level=error ts=2021-02-12T02:35:45.354Z caller=main.go:216 msg="Error loading config" err="error parsing config file: yaml: unmarshal errors:\n  line 6: field vaild_http_versions not found in type config.plain\n  line 7: field vaild_status_codes not found in type config.plain"
[root@hdss7-21 ~]#
```
