### ISSUE TITLE
TLS/StartTLS didn't work in docker image: prom/blackbox-exporter

### ISSUE THREAD

**Issue by andreaskeutner** [prometheus/blackbox_exporter#760]
### Host operating system: 
docker image:     prom/blackbox-exporter
"Image": "sha256:9b47925773f0ff78f7f2124c4c18fe1ac39b9037c8e28d0a3bd64cbddbc1d7e4",

### blackbox_exporter version: 
```
blackbox_exporter, version 0.18.0 (branch: HEAD, revision: 60c86e6ce5a1111f7958b06ae7a08222bb6ec839)
  build user:       root@53d72328d93f
  build date:       20201012-09:53:27
  go version:       go1.15.2
```

### What is the blackbox.yml module config.
```
  tcp_cert:
    prober: tcp
    tcp:
      tls: true
      query_response:
        - starttls: true
      tls_config:
        insecure_skip_verify: false
```
### What is the prometheus.yml scrape config.
``` 
 - job_name: 'blackbox_tcp_cert'
    metrics_path: /probe
    params:
      module: [tcp_cert]  # Look for a tcp_connect response.
    static_configs:
      - targets:
        - imap.xxx.biz:143   
        - imap.xxx.biz:993  
        - smtp.xxx.biz:25  
        - smtp.xxx.biz:587  
        - 192.168.0.32:9090  
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prom_blackbox:9115  # The blackbox exporter's real hostname:port.
```
### What logging output did you get from adding `&debug=true` to the probe URL?

```
Logs for the probe:
ts=2021-03-15T08:33:00.257219606Z caller=main.go:304 module=tcp_cert target=imap.xxx.biz:143 level=info msg="Beginning probe" probe=tcp timeout_seconds=9.5
ts=2021-03-15T08:33:00.257962779Z caller=tcp.go:41 module=tcp_cert target=imap.xxx.biz:143 level=info msg="Resolving target address" ip_protocol=ip6
ts=2021-03-15T08:33:00.263285199Z caller=tcp.go:41 module=tcp_cert target=imap.xxx.biz:143 level=info msg="Resolved target address" ip=49.xxx.xxx.xxx
ts=2021-03-15T08:33:00.263514313Z caller=tcp.go:122 module=tcp_cert target=imap.xxx.biz:143 level=info msg="Dialing TCP with TLS"
ts=2021-03-15T08:33:00.330560992Z caller=main.go:119 module=tcp_cert target=imap.xxx.biz:143 level=error **msg="Error dialing TCP" err="tls: first record does not look like a TLS handshake"**
ts=2021-03-15T08:33:00.330811512Z caller=main.go:304 module=tcp_cert target=imap.xxx.biz:143 level=error **msg="Probe failed"** duration_seconds=0.073332949
```

Metrics that would have been returned:
```
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.005388045
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.073332949
# HELP probe_failed_due_to_regex Indicates if probe failed due to regex
# TYPE probe_failed_due_to_regex gauge
probe_failed_due_to_regex 0
# HELP probe_ip_addr_hash Specifies the hash of IP address. It's useful to detect if the IP address changes.
# TYPE probe_ip_addr_hash gauge
probe_ip_addr_hash 9.39208e+08
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0
```

Module configuration:
```
prober: tcp
http:
    ip_protocol_fallback: true
tcp:
    ip_protocol_fallback: true
    tls: true
icmp:
    ip_protocol_fallback: true
dns:
    ip_protocol_fallback: true
```
### What did you do that produced an error?
I enabled TLS/StartTLS for tcp 
### What did you expect to see?
A TLS Handshake
### What did you see instead?
tls: first record does not look like a TLS handshake
