### ISSUE TITLE
How to ignore 401 errors 

### ISSUE THREAD

**Issue by ndubbala** [prometheus/blackbox_exporter#802]
### Host operating system: output of `uname -a`

3.10.0-1160.25.1.el7.x86_64

### blackbox_exporter version: output of `blackbox_exporter --version`

blackbox_exporter, version 0.19.0
### What is the blackbox.yml module config.
modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [200,401,404] #default to 2xx
      method: GET
      no_follow_redirects: false

### What is the prometheus.yml scrape config.
- job_name: 'UAT Apps healthchecks'
    scrape_interval: 120s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
     - targets:
     relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: blackbox:9115 # The blackbox exporter.

**Comment by roidelapluie** [comment]
Thanks for your report. It looks as if this is actually a question about usage and not development.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) or our [forums](https://discuss.prometheus.io) rather than in a GitHub issue. In our [community channels](https://prometheus.io/community), more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by contrun** [comment]
I had the same problem. I am now using the following configuration.

```
modules:
  http_3xx:
    http:
      follow_redirects: false
      valid_status_codes:
        - 301
        - 302
        - 303
        - 304
        - 307
        - 308
    prober: http
    timeout: 5s
  http_404:
    http:
      valid_status_codes:
        - 404
    prober: http
    timeout: 5s
```

I don't know if there is something I missed in the public documentation. It is only after I searched status code through the source code that I found out the above way to configure this.

If I was not missing something, then this issue is rightly filed here. We'd better improve the documentation. If I indeed missed something, please comment here lest other people spend time on the source code.
