### ISSUE TITLE
TCP prober is always returning success no matter witch port you use.

### ISSUE THREAD

**Issue by LuisMLGDev** [prometheus/blackbox_exporter#810]
Hi guys,
I've configured a TCP check like this:

```
  modules:
      tcp_connect:
          prober: tcp
          timeout: 5s
```

Basically tthe issue is I always getting a sussccess no matter which port uses or if the service is really up or not...
`module=tcp_connect target=testing.miservice.link:28666 level=debug msg="Successfully dialed"`
`module=tcp_connect target=testing.miservice.link:28555 level=debug msg="Successfully dialed"`

Obviously, you need the proper port to get a successful connection. When I try with telnet ... telnet connect or not depends if the port is the proper one.

The issue was tested in 0.18 and 0.19 versions and BlackBox exporter was deployed in an EKS cluster.
The same blackbox contains a configuration for HTTP_2xx and all these endpoints (http prober) are working fine.

Scrape config:
```
    - job_name: 'blackbox_tcp'
      metrics_path: /probe
      params:
        module: [tcp_connect]
      static_configs:
        - targets:
          - testing.miservice.link:28555
          - testing.miservice.link:28666
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: monitoring-prometheus-blackbox-exporter:9115
```
I really spent much time doing many tests and with no luck.
Any suggestions or ideas?

thanks in advance!
