### ISSUE TITLE
ICMP Probe returns reachable until blackbox restart

### ISSUE THREAD

**Issue by realSchoki** [prometheus/blackbox_exporter#811]
### Host operating system: output of `uname -a`

`Linux XXX 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### blackbox_exporter version: output of `blackbox_exporter --version`
Docker Image:  prom/blackbox-exporter:master    4188369fc1cd    4 days ago

```
blackbox_exporter, version 0.19.0 (branch: master, revision: b919f38669f4c8b87f84d9f36336a26bf2cf7b7d)
  build user:       root@fd0a8b053956
  build date:       20210708-20:40:27
  go version:       go1.16.5
  platform:         linux/amd64
```

### What is the blackbox.yml module config.

```
modules:
  http_2xx_ipv4:
    prober: http
    http:
      preferred_ip_protocol: ip4
  http_2xx:
    prober: http
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
      - send: "SSH-2.0-blackbox-ssh-check"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp
  icmp_ipv4:
    prober: icmp
    timeout: 2s
    icmp:
      preferred_ip_protocol: ip4
```

### What is the prometheus.yml scrape config.

```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [icmp_ipv4]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - 192.168.0.10
        - 192.168.0.11
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.0.1:9115  # The blackbox exporter's real hostname:port.
```

### What logging output did you get from adding `&debug=true` to the probe URL?

```
Logs for the probe:
ts=2021-07-13T14:09:55.395854367Z caller=main.go:320 module=icmp_ipv4 target=192.168.0.11 level=info msg="Beginning probe" probe=icmp timeout_seconds=2
ts=2021-07-13T14:09:55.396038594Z caller=icmp.go:91 module=icmp_ipv4 target=192.168.0.11 level=info msg="Resolving target address" ip_protocol=ip4
ts=2021-07-13T14:09:55.396098656Z caller=icmp.go:91 module=icmp_ipv4 target=192.168.0.11 level=info msg="Resolved target address" ip=192.168.0.11
ts=2021-07-13T14:09:55.396118117Z caller=main.go:130 module=icmp_ipv4 target=192.168.0.11 level=info msg="Creating socket"
ts=2021-07-13T14:09:55.396192709Z caller=main.go:130 module=icmp_ipv4 target=192.168.0.11 level=debug msg="Unable to do unprivileged listen on socket, will attempt privileged" err="socket: permission denied"
ts=2021-07-13T14:09:55.396294884Z caller=main.go:130 module=icmp_ipv4 target=192.168.0.11 level=info msg="Creating ICMP packet" seq=58675 id=25319
ts=2021-07-13T14:09:55.396343146Z caller=main.go:130 module=icmp_ipv4 target=192.168.0.11 level=info msg="Writing out packet"
ts=2021-07-13T14:09:55.396523243Z caller=main.go:130 module=icmp_ipv4 target=192.168.0.11 level=info msg="Waiting for reply packets"
ts=2021-07-13T14:09:55.421466295Z caller=main.go:130 module=icmp_ipv4 target=192.168.0.11 level=info msg="Found matching reply packet"
ts=2021-07-13T14:09:55.421548488Z caller=main.go:320 module=icmp_ipv4 target=192.168.0.11 level=info msg="Probe succeeded" duration_seconds=0.025596288



Metrics that would have been returned:
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 7.8163e-05
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.025596288
# HELP probe_icmp_duration_seconds Duration of icmp request by phase
# TYPE probe_icmp_duration_seconds gauge
probe_icmp_duration_seconds{phase="resolve"} 7.8163e-05
probe_icmp_duration_seconds{phase="rtt"} 0.025069787
probe_icmp_duration_seconds{phase="setup"} 0.000210518
# HELP probe_icmp_reply_hop_limit Replied packet hop limit (TTL for ipv4)
# TYPE probe_icmp_reply_hop_limit gauge
probe_icmp_reply_hop_limit 54
# HELP probe_ip_addr_hash Specifies the hash of IP address. It's useful to detect if the IP address changes.
# TYPE probe_ip_addr_hash gauge
probe_ip_addr_hash 1.999576545e+09
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 1



Module configuration:
prober: icmp
timeout: 2s
http:
    ip_protocol_fallback: true
    follow_redirects: true
tcp:
    ip_protocol_fallback: true
icmp:
    preferred_ip_protocol: ip4
    ip_protocol_fallback: true
dns:
    ip_protocol_fallback: true
```

### What did you do that produced an error?

I use the ICMP Module to probe different IPs if they are reachable. In my router i can set up if a ping is processed or ignored. If it set to pass then the response is probe_success 1. If i drop the ping it still says probe_success 1. If i then restart blackbox it shows the correct state: probe_success 0. 

To check if its no a fault of the router i used ping out of the bash from the same device blackbox is running on. It behaves like it should. `Block Ping from WAN` disabled, ping works, `Block Ping from WAN` active, ping does not work.

### What did you expect to see?

probe_success 0 should be shown if a ping can't be processed.

### What did you see instead?

probe_success 1
