### ISSUE TITLE
Can't bind to localhost or 127.0.0.1, service is always visible to the outside

### ISSUE THREAD

**Issue by Mindtoeye** [prometheus/blackbox_exporter#817]
### Host operating system: output of `uname -a`

Linux <hostname> 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter --version`

blackbox_exporter, version 0.19.0 (branch: HEAD, revision: 5d575b88eb12c65720862e8ad2c5890ba33d1ed0)
  build user:       root@2b0258d5a55a
  build date:       20210510-12:56:44
  go version:       go1.16.4
  platform:         linux/amd64

### What is the blackbox.yml module config.

```
modules:
  http_prometheus:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      method: GET
      fail_if_ssl: false
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: true

```
### What logging output did you get from adding `&debug=true` to the probe URL?

From /var/log/syslog:

Aug 10 14:15:05 infra-01 blackbox_exporter[41318]: level=info ts=2021-08-10T18:15:05.701Z caller=main.go:385 msg="Listening on address" address=:9115

### What did you do that produced an error?

I configured my service config file (/lib/systemd/system/blackbox.service) with:

```
Description=Blackbox Exporter Service
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=blackbox
Group=blackbox
ExecStart=/usr/local/bin/blackbox_exporter --config.file=/etc/blackbox/blackbox.yml --web.listen-address="127.0.0.1:9115"

Restart=always

[Install]
```

Point a browser to our public web address of the server running blackbox_exporter

### What did you expect to see?

I was expecting to see nothing, as in: a connection could not be established

### What did you see instead?

I could pull up the /metrics page and the /config page
