### ISSUE TITLE
random 'Address does not match first address'

### ISSUE THREAD

**Issue by izenk** [prometheus/blackbox_exporter#830]
### Host operating system: output of `uname -a`
Linux 039132dea8e9 5.4.0-1039-azure #41~18.04.1-Ubuntu SMP Mon Jan 18 14:00:01 UTC 2021 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter --version`
blackbox_exporter, version 0.19.0 (branch: HEAD, revision: 5d575b88eb12c65720862e8ad2c5890ba33d1ed0)

### What is the blackbox.yml module config.
```
modules:
  http_ap_gen:
    prober: http
    http:
      preferred_ip_protocol: ip4
      ip_protocol_fallback: false
```
### What is the prometheus.yml scrape config.
```
  - job_name: blackbox_http
    honor_labels: true
    scrape_interval: 3m
    scrape_timeout: 2m
    metrics_path: /probe
    file_sd_configs:
    - files:
      - jobs/blackbox_http/*.yml
      refresh_interval: 1m
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [module]
      target_label: __param_module
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: vm-001.internal.cloudapp.net:9115

```

```
- labels:
    module: http_ap_gen
  targets:
  - https://<my_host>/sign_in
```
### What did you expect to see?
My endpoint is up and reachable, but blackbox exporter randomly reports:
```
ts=2021-09-29T09:54:26.163014536Z caller=client.go:251 module=http_ap_gen target=https://<my_host> level=info msg="Address does not match first address, not sending TLS ServerName" first=<my_ip> address=<my_host>
ts=2021-09-29T09:56:25.451775515Z caller=main.go:130 module=http_ap_gen target=https://<my_host> level=error msg="Error for HTTP request" err="Get \"https://<my_host>/sign_in\": context deadline exceeded"
```

Nothing is changed from endpoint side. On the same host I have telegraf which also monitors the same endpoint - everything is ok. Only blackbox exporter randomly (3-4 time per day) shows error.
