### ISSUE TITLE
Error dialing TCP 

### ISSUE THREAD

**Issue by yedajiang44** [prometheus/blackbox_exporter#832]
### Host operating system: output of `uname -a`

```
Linux blackbox 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 GNU/Linux
```

### blackbox_exporter version: output of `blackbox_exporter --version`

```
blackbox_exporter, version 0.19.0 (branch: HEAD, revision: 5d575b88eb12c65720862e8ad2c5890ba33d1ed0)
build user: root@2b0258d5a55a
build date: 20210510-12:56:44
go version: go1.16.4
platform: linux/amd64
```

### What is the blackbox.yml module config.

```
modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
  http_post_2xx:
    prober: http
    http:
      method: POST
      preferred_ip_protocol: "ip4"
  tcp_connect:
    prober: tcp
    timeout: 5s
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
        - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
        - expect: "^SSH-2.0-"
        - send: "SSH-2.0-blackbox-ssh-check"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
        - send: "NICK prober"
        - send: "USER prober prober prober :prober"
        - expect: "PING :([^ ]+)"
          send: "PONG ${1}"
        - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp
```

### What is the prometheus.yml scrape config.

```
  - job_name: 端口存活状态
    metrics_path: /probe
    scrape_interval: 1m
    params:
      module: [tcp_connect]
    static_configs:
      - labels:
          group: tcp
          internalIp: 192.168.0.9
        targets:
          - xxx.xxx.xxx.xxx:7878
```

### What logging output did you get from adding `&debug=true` to the probe URL?

```
ts=2021-10-11T08:19:23.527Z caller=main.go:180 module=tcp_connect target=xxx.xxx.xxx.xxx:7878 level=debug msg="Beginning probe" probe=tcp timeout_seconds=9.5
ts=2021-10-11T08:19:23.527Z caller=main.go:180 module=tcp_connect target=xxx.xxx.xxx.xxx:7878 level=debug msg="Resolving target address" ip_protocol=ip6
ts=2021-10-11T08:19:23.527Z caller=main.go:180 module=tcp_connect target=xxx.xxx.xxx.xxx:7878 level=debug msg="Resolving target address" ip_protocol=ip4
ts=2021-10-11T08:19:23.527Z caller=main.go:180 module=tcp_connect target=xxx.xxx.xxx.xxx:7878 level=debug msg="Resolved target address" ip=218.2.24.54
ts=2021-10-11T08:19:23.527Z caller=main.go:180 module=tcp_connect target=xxx.xxx.xxx.xxx:7878 level=debug msg="Dialing TCP without TLS"
ts=2021-10-11T08:19:33.031Z caller=main.go:180 module=tcp_connect target=xxx.xxx.xxx.xxx:7878 level=debug msg="Error dialing TCP" err="dial tcp4 xxx.xxx.xxx.xxx:7878: i/o timeout"
ts=2021-10-11T08:19:33.031Z caller=main.go:180 module=tcp_connect target=xxx.xxx.xxx.xxx:7878 level=debug msg="Probe failed" duration_seconds=9.504733596
ts=2021-10-11T08:20:23.527Z caller=main.go:180 module=tcp_connect target=xxx.xxx.xxx.xxx:7878 level=debug msg="Beginning probe" probe=tcp timeout_seconds=9.5
ts=2021-10-11T08:20:23.527Z caller=main.go:180 module=tcp_connect target=xxx.xxx.xxx.xxx:7878 level=debug msg="Resolving target address" ip_protocol=ip6
ts=2021-10-11T08:20:23.527Z caller=main.go:180 module=tcp_connect target=xxx.xxx.xxx.xxx:7878 level=debug msg="Resolving target address" ip_protocol=ip4
ts=2021-10-11T08:20:23.527Z caller=main.go:180 module=tcp_connect target=xxx.xxx.xxx.xxx:7878 level=debug msg="Resolved target address" ip=218.2.24.54
ts=2021-10-11T08:20:23.527Z caller=main.go:180 module=tcp_connect target=xxx.xxx.xxx.xxx:7878 level=debug msg="Dialing TCP without TLS"
ts=2021-10-11T08:20:33.031Z caller=main.go:180 module=tcp_connect target=xxx.xxx.xxx.xxx:7878 level=debug msg="Error dialing TCP" err="dial tcp4 xxx.xxx.xxx.xxx:7878: i/o timeout"
```

### What did you expect to see?

port detection success

### What did you see instead?

port detection failed

## Extra Information

> since ip and port are production environments it is not convenient to announce，all xxx xxx xxx xxx represents the same ip

### Environment

blackbox in docker

### Detect Other Servers

trick all the tcp ports of other servers

### netcat test

> try the host and docker, output result is consistent

exec netcat`nc -zv xxx.xxx.xxx.xxx port` print like

```
xxx.xxx.xxx.xxx open
```
