### ISSUE TITLE
Metrics are randomly disappearing

### ISSUE THREAD

**Issue by tischenko** [prometheus/blackbox_exporter#84]
blackbox_exporter 0.3.0 / prometheus 1.4.1

I've faced the issue when blackbox_exporter starts returning _probe_success 0_ for random hosts after several hours/days of correct functioning.

Prometheus' configuration:
```
global:
  scrape_interval: 60s
  scrape_timeout: 20s
  external_labels:
    monitor: 'tvdashboard'

scrape_configs:
  - job_name: 'blackbox_devmetrics'
    metrics_path: /probe
    params:
      module: [http_devmetrics]
    static_configs:
      - targets:
        - devmetrics.hostname.com
    relabel_configs: &relabel
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 127.0.0.1:9115  # blackbox_exporter
  - job_name: 'blackbox_rally'
    metrics_path: /probe
    params:
      module: [http_rally]
    static_configs:
      - targets:
        - rally1.rallydev.com/slm/login.op
    relabel_configs: *relabel
  - job_name: 'blackbox_jira'
    metrics_path: /probe
    params:
      module: [http_jira]
    static_configs:
      - targets:
        - jira.hostname.com/login.jsp?os_destination=%2Fsecure%2FDashboard.jspa
    relabel_configs: *relabel
  - job_name: 'blackbox_confluence'
    metrics_path: /probe
    params:
      module: [http_confluence]
    static_configs:
      - targets:
        - confluence.hostname.com/login.action
    relabel_configs: *relabel
```

blackbox_exporter's configuration
```
modules:
  http_devmetrics:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: []
      method: GET
      headers: &headers
        Accept-Language: en-US
        User-Agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      fail_if_not_matches_regexp:
        - "username"
      tls_config: &tls_config
        insecure_skip_verify: true
      protocol: "tcp"
      preferred_ip_protocol: "ip4"
  http_rally:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: []
      method: GET
      headers: *headers
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      fail_if_not_matches_regexp:
        - "Sign in"
      tls_config: *tls_config
      protocol: "tcp"
      preferred_ip_protocol: "ip4"
  http_jira:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: []
      method: GET
      headers: *headers
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      fail_if_not_matches_regexp:
        - "login-form-username"
      tls_config: *tls_config
      protocol: "tcp"
      preferred_ip_protocol: "ip4"
  http_confluence:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: []
      method: GET
      headers: *headers
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      fail_if_not_matches_regexp:
        - "Username"
      tls_config: *tls_config
      protocol: "tcp"
      preferred_ip_protocol: "ip4"
```

I've tried using Prometheus' web UI and CLI to debug. I've noticed that all the targets are active ("up") in Prometheus, but at the same time when I want to get a value of _probe_http_status_code_ metric, I see it only for several (randomly selected) targets, but not for all (this is my expected behavior).

When I'm using CLI, I got the same result for the hosts that aren't displaying in Prometheus UI:
```
$ curl "http://127.0.0.1:9115/probe?module=http_devmetrics&target=devmetrics.hostname.com"
probe_duration_seconds 0.001795
probe_success 0
```
So seems like the problem is in blackbox_exporter but not in Prometheus itself.

On the other hand, if using just curl, I see that my service is up and running:
```
$ curl -L -k "http://devmetrics.hostname.com" | grep -o username
username
```

I'm doing _curl_ on the same machine where blackbox_exporter is running to eliminate any network issues.

This problem occurs periodically and in most cases is solved by blackbox_exporter restarting.
