### ISSUE TITLE
When reloading config within a docker container, yaml error is raised

### ISSUE THREAD

**Issue by prigio** [prometheus/blackbox_exporter#846]
When running in docker on osx and shortening the configuration file from my laptop, then asking the exporter to reload the config, an error is raised:

    failed to reload config: error parsing config file: yaml: control characters are not allowed

### Host operating system: output of `uname -a`
**Darwin** 20.6.0 Darwin Kernel Version 20.6.0 root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
**Docker** version 20.10.8, build 3967b7d
**Docker image** prom/blackbox-exporter 2dbed8e0d742

### blackbox_exporter version: output of `blackbox_exporter --version`
```
blackbox_exporter, version 0.19.0 (branch: master, revision: 6fcd1424e2e7943927b046dc4b1123ce69f32864)
 build user:       root@25994afe8286
  build date:       20211111-00:36:27
  go version:       go1.16.10
  platform:         linux/amd64
```

### What is the blackbox.yml module config.
```
# prometheus blackbox exporter configuration file
# https://github.com/prometheus/blackbox_exporter
# https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md
modules:
  http_2xx:
    prober: http
    http:
      # within docker, not working on the default ip6
      preferred_ip_protocol: ip4
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
    tcp:
      preferred_ip_protocol: ip4
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
      - send: "SSH-2.0-blackbox-ssh-check"
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: ip4
      source_ip_address: "127.0.0.1"
```

After "shortening", the config file is: 

```
# prometheus blackbox exporter configuration file
# https://github.com/prometheus/blackbox_exporter
# https://github.com/prometheus/blackbox_exporter/blob/master/CONFIGURATION.md
modules:
  http_2xx:
    prober: http
    http:
      # within docker, not working on the default ip6
      preferred_ip_protocol: ip4
```

### What is the prometheus.yml scrape config.
```
scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io    # Target to probe with http.
        - https://prometheus.io   # Target to probe with https.
        - https://www.google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: p8s_blackbox:9115  # The blackbox exporter's real hostname:port.
```
### What logging output did you get from adding `&debug=true` to the probe URL?
Not relevant

### What did you do that produced an error?
Started the exported within a docker container on Mac as:

    docker run -d --rm ... -v=/path/to/blackbox.yml:/config/blackbox.yml prom/blackbox-exporter --config.file=/config/blackbox.yml

Test scraping is fine via cUrl. 
Shorten the configuration file  (on my mac, via code editor, see section on config file) and ask the exporter to reload it via:

    curl http://localhost:9115/-/reload -d ""

### What did you expect to see?
The "reload" command should not provide any output on a successful config reload.

### What did you see instead?
The following error:

    failed to reload config: error parsing config file: yaml: control characters are not allowed

### Additional notes
The config is successfully reloaded if I append a long comment (like thousand chars long) at the end of the configuration file and rerun the "reload" function.

If I stop the container, ensure it is removed and restart it, the "short" version of the config file is perfectly fine.

My guess on this is that mounting the file via docker volume will leave some null characters at the end of the file within the container when it gets shortened. The Yaml parser fails when reading those.
