### ISSUE TITLE
Error for HTTP request local error: tls: unexpected 

### ISSUE THREAD

**Issue by y0zg** [prometheus/blackbox_exporter#847]
### Host operating system: output of `uname -a`
Ubuntu
### blackbox_exporter version: output of `blackbox_exporter --version`
5.3.1

### What is the blackbox.yml module config.
```yaml
  modules:
      http_2xx:
        http:
          follow_redirects: true
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
        prober: http
        timeout: 5s
      http_2xx_m:
        http:
          method: GET
          tls_config:
            insecure_skip_verify: true
          follow_redirects: true
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/2.0
          headers:
            Accept: "application/vnd.api.v1+json"
            Authorization: "Basic xxx"
        prober: http
        timeout: 10s
```
### What is the prometheus.yml scrape config.
```yaml
     - job_name: blackbox-m
        metrics_path: /probe
        params:
          module: [http_2xx_m]
        static_configs:
        - targets:
          - https://example.com/info&debug=true
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: prometheus-blackbox-exporter:9115
```

### What logging output did you get from adding `&debug=true` to the probe URL?
```
Logs for the probe:
ts=2021-11-14T17:08:26.222345029Z caller=main.go:320 module=http_2xx_m target="https://example.com/info&debug=true" level=info msg="Beginning probe" probe=http timeout_seconds=9.5
ts=2021-11-14T17:08:26.222654443Z caller=http.go:335 module=http_2xx_m target="https://example.com/info&debug=true" level=info msg="Resolving target address" ip_protocol=ip4
ts=2021-11-14T17:08:26.236955408Z caller=http.go:335 module=http_2xx_m target="https://example.com/info&debug=true" level=info msg="Resolved target address" ip=111.111.111.111
ts=2021-11-14T17:08:26.23709508Z caller=client.go:251 module=http_2xx_m target="https://example.com/info&debug=true" level=info msg="Making HTTP request" url="https://111.111.111.111/info&debug=true" host=example.com
ts=2021-11-14T17:08:26.42345006Z caller=main.go:130 module=http_2xx_m target="https://example.com/info&debug=true" level=error msg="Error for HTTP request" err="Get \"https://111.111.111.111/info&debug=true\": local error: tls: unexpected message"
ts=2021-11-14T17:08:26.42350984Z caller=main.go:130 module=http_2xx_m target="https://example.com/info&debug=true" level=info msg="Response timings for roundtrip" roundtrip=0 start=2021-11-14T17:08:26.237199321Z dnsDone=2021-11-14T17:08:26.237199321Z connectDone=2021-11-14T17:08:26.298822759Z gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z tlsStart=2021-11-14T17:08:26.298866219Z tlsDone=2021-11-14T17:08:26.423392749Z end=0001-01-01T00:00:00Z
ts=2021-11-14T17:08:26.423545301Z caller=main.go:320 module=http_2xx_m target="https://example.com/info&debug=true" level=error msg="Probe failed" duration_seconds=0.201147221
```
### What did you do that produced an error?
If I run resolved IP - it also doesn't work, calls work only with DNS names

 `curl -ikL https://111.111.111.111/info` - 405 HTTP error

 `curl -ikL https://eample.com/info` - 200 HTTP

In blackbox exporter I see logs are resolved into IP before making a call, probably this somehow related to above curl behavior

### What did you expect to see?
200 response

### What did you see instead?
`Error for HTTP request" err="Get \"https://111.111.111.111/info&debug=true\": local error: tls: unexpected message`
