### ISSUE TITLE
Bug: basic_auth directive in config works but equivalent Authorization header doesn't works

### ISSUE THREAD

**Issue by bbkgh** [prometheus/blackbox_exporter#861]
Hi. Connecting to a website that has basic auth with `Authorization` header returns 401 but equivalent probe with basic_auth directive is successful.
Is this behavior intentional?

blackbox_exporter --version: version 0.17.0

### What is the blackbox.yml module config.
with basic auth:
```
auto_3494_BC6A47:
            prober: http
            http:
                preferred_ip_protocol: "ip4"
                method: GET
                basic_auth:
                  username: admin
                  password: admin

```
with equivalent authorization header:
```
auto_3494_BC6A47:
            prober: http
            http:
                preferred_ip_protocol: "ip4"
                method: GET
                headers:
                        Authorization: "Basic YWRtaW46YWRtaW4K"

```
### What did you expect to see?
Same behavior in both cases.
