### ISSUE TITLE
Blackbox Exporter adding ip to url instead dns name

### ISSUE THREAD

**Issue by scbay** [prometheus/blackbox_exporter#886]
### Host operating system: output of `uname -a`
Running blackbox exporter in a k8s cluster

### blackbox_exporter version: output of `blackbox_exporter --version`
0.19.0

### What is the blackbox.yml module config.
```
   modules:
      http_2xx:
        http:
          follow_redirects: true
          preferred_ip_protocol: ip4
          valid_http_versions:
          - HTTP/1.1
          - HTTP/2.0
        prober: http
        timeout: 5s
      tcp_connect:
        prober: tcp
      icmp:
        prober: icmp
        icmp:
          preferred_ip_protocol: "ip4"
```

### What is the prometheus.yml scrape config.
```
  - interval: 5m
    metricRelabelings:
    - sourceLabels:
      - __address__
      targetLabel: __param_target
    - replacement: prometheus-blackbox-exporter:9115
      sourceLabels:
      - __param_target
      targetLabel: instance
    relabelings:
    - sourceLabels: [job]
      regex: (.*)
      targetLabel: job
      replacement: "my.super.host"
      action: replace
    params:
      module:
      - http_2xx
      target:
      - my.super.host
    path: /probe
    port: http
    scheme: http
    scrapeTimeout: 30s
```

### What logging output did you get from adding `&debug=true` to the probe URL?
X

### What did you do that produced an error?
I have added a new scrape target to the configuration which uses the http_2xx module to do http checks.

### What did you expect to see?
ts=2022-02-28T13:27:12.202701182Z caller=client.go:251 module=http_2xx target=https://my.super.host/ level=info msg="Making HTTP request" url=https://my.super.host/ host=my.super.host

### What did you see instead?
ts=2022-02-28T13:27:12.202701182Z caller=client.go:251 module=http_2xx target=https://my.super.host/ level=info msg="Making HTTP request" url=https://IP-ADRESS/ host=my.super.host

I was wondering if there is something I can do to bring blackbox exporter to call the host name from target instead using the ip address.
