### ISSUE TITLE
Checking proxy availability

### ISSUE THREAD

**Issue by postwarbreakout** [prometheus/blackbox_exporter#891]
Hello,

our current monitoring is Icinga/Nagios which has a plugin to test a proxy by specifying a target URL that will be accessed through the given proxy.
We're in process of moving to Prometheus and I'm quite sure that blackbox can be used to replace this plugin, but I struggle to get the configuration right. I tried to figure it out from related threads, but the probe is failing.

blackbox.yml:
```
  proxy_http:
    prober: http
    http:
      valid_status_codes: []
      method: GET
      no_follow_redirects: false
      proxy_url: url:8080
      tls_config:
        insecure_skip_verify: true
      fail_if_ssl: false
      fail_if_not_ssl: false

```

prometheus.yml:
```
  - job_name: 'blackbox_proxy_http'
    metrics_path: /probe
    scrape_interval: 60s
    params:
     module: [proxy_http]
    static_configs:
    - targets:
      - http://url.to.test
```

Any help is appreciated.
