### ISSUE TITLE
probe_http_uncompressed_body_length is wrong in case of redirect

### ISSUE THREAD

**Issue by Falseclock** [prometheus/blackbox_exporter#896]
### Host operating system: output of `uname -a`
```Linux prometheus-blackbox-exporter-5b55bd69f7-tg94g 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 GNU/Linux```

### blackbox_exporter version: output of `blackbox_exporter --version`

```
blackbox_exporter, version 0.19.0 (branch: HEAD, revision: 5d575b88eb12c65720862e8ad2c5890ba33d1ed0)
  build user:       root@2b0258d5a55a
  build date:       20210510-12:56:44
  go version:       go1.16.4
  platform:         linux/amd64

```

### What is the blackbox.yml module config.
```
    http_categories:
      prober: http
      timeout: 5s
      http:
        proxy_url: http://10.204.11.146:3128
        valid_http_versions: [ "HTTP/1.1", "HTTP/2.0" ]
        follow_redirects: true
        preferred_ip_protocol: "ip4"
        headers:
          Host: m.halykmarket.com
          Origin: m.halykmarket.com
```

### What is the prometheus.yml scrape config.
```
      - job_name: 'blackbox-categories'
        metrics_path: /probe
        params:
          module: [ http_categories ]
        static_configs:
          - targets:
              - https://m.halykmarket.kz/nur-sultan/c/categories
              - https://m.halykmarket.kz/almaty/c/categories
              - https://m.halykmarket.kz/karaganda/c/categories
            labels:
              task: categories
        relabel_configs:
          - source_labels: [ __address__ ]
            action: replace
            target_label: city
            regex: http.*?\/\/.*?\/(.*?)\/.*
            replacement: $1
          - source_labels: [ __address__ ]
            target_label: __param_target
          - source_labels: [ __param_target ]
            target_label: instance
          - target_label: __address__
            replacement: prometheus-blackbox-exporter:9115
```

### What logging output did you get from adding `&debug=true` to the probe URL?
```
Logs for the probe:
ts=2022-03-27T09:14:06.234891937Z caller=main.go:320 module=http_categories target=https://m.halykmarket.kz/nur-sultan/c/categories level=info msg="Beginning probe" probe=http timeout_seconds=5
ts=2022-03-27T09:14:06.23501733Z caller=http.go:335 module=http_categories target=https://m.halykmarket.kz/nur-sultan/c/categories level=info msg="Resolving target address" ip_protocol=ip4
ts=2022-03-27T09:14:06.236557262Z caller=http.go:335 module=http_categories target=https://m.halykmarket.kz/nur-sultan/c/categories level=info msg="Resolved target address" ip=10.204.11.10
ts=2022-03-27T09:14:06.236651953Z caller=client.go:251 module=http_categories target=https://m.halykmarket.kz/nur-sultan/c/categories level=info msg="Making HTTP request" url=https://10.204.11.10/nur-sultan/c/categories host=m.halykmarket.com
ts=2022-03-27T09:14:06.282613287Z caller=client.go:492 module=http_categories target=https://m.halykmarket.kz/nur-sultan/c/categories level=info msg="Received redirect" location=https://m.halykmarket.com/c/categories
ts=2022-03-27T09:14:06.282666388Z caller=client.go:251 module=http_categories target=https://m.halykmarket.kz/nur-sultan/c/categories level=info msg="Making HTTP request" url=https://m.halykmarket.com/c/categories host=
ts=2022-03-27T09:14:06.282680719Z caller=client.go:251 module=http_categories target=https://m.halykmarket.kz/nur-sultan/c/categories level=info msg="Address does not match first address, not sending TLS ServerName" first=10.204.11.10 address=m.halykmarket.com
ts=2022-03-27T09:14:06.330163364Z caller=main.go:130 module=http_categories target=https://m.halykmarket.kz/nur-sultan/c/categories level=info msg="Received HTTP response" status_code=200
ts=2022-03-27T09:14:06.330217282Z caller=main.go:130 module=http_categories target=https://m.halykmarket.kz/nur-sultan/c/categories level=info msg="Response timings for roundtrip" roundtrip=0 start=2022-03-27T09:14:06.236731357Z dnsDone=2022-03-27T09:14:06.236731357Z connectDone=2022-03-27T09:14:06.237013295Z gotConn=2022-03-27T09:14:06.275009041Z responseStart=2022-03-27T09:14:06.282455231Z tlsStart=2022-03-27T09:14:06.269164183Z tlsDone=2022-03-27T09:14:06.274931607Z end=0001-01-01T00:00:00Z
ts=2022-03-27T09:14:06.33024516Z caller=main.go:130 module=http_categories target=https://m.halykmarket.kz/nur-sultan/c/categories level=info msg="Response timings for roundtrip" roundtrip=1 start=2022-03-27T09:14:06.282763661Z dnsDone=2022-03-27T09:14:06.282763661Z connectDone=2022-03-27T09:14:06.283123739Z gotConn=2022-03-27T09:14:06.300864995Z responseStart=2022-03-27T09:14:06.329990244Z tlsStart=2022-03-27T09:14:06.294689204Z tlsDone=2022-03-27T09:14:06.300729658Z end=2022-03-27T09:14:06.330208759Z
ts=2022-03-27T09:14:06.330310125Z caller=main.go:320 module=http_categories target=https://m.halykmarket.kz/nur-sultan/c/categories level=info msg="Probe succeeded" duration_seconds=0.09537664



Metrics that would have been returned:
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.001577966
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.09537664
# HELP probe_failed_due_to_regex Indicates if probe failed due to regex
# TYPE probe_failed_due_to_regex gauge
probe_failed_due_to_regex 0
# HELP probe_http_content_length Length of http content response
# TYPE probe_http_content_length gauge
probe_http_content_length -1
# HELP probe_http_duration_seconds Duration of http request by phase, summed over all redirects
# TYPE probe_http_duration_seconds gauge
probe_http_duration_seconds{phase="connect"} 0.0006421269999999999
probe_http_duration_seconds{phase="processing"} 0.036571475
probe_http_duration_seconds{phase="resolve"} 0.001577966
probe_http_duration_seconds{phase="tls"} 0.011807871000000001
probe_http_duration_seconds{phase="transfer"} 0.000218447
# HELP probe_http_redirects The number of redirects
# TYPE probe_http_redirects gauge
probe_http_redirects 1
# HELP probe_http_ssl Indicates if SSL was used for the final redirect
# TYPE probe_http_ssl gauge
probe_http_ssl 1
# HELP probe_http_status_code Response HTTP status code
# TYPE probe_http_status_code gauge
probe_http_status_code 200
# HELP probe_http_uncompressed_body_length Length of uncompressed response body
# TYPE probe_http_uncompressed_body_length gauge
probe_http_uncompressed_body_length 4467
# HELP probe_http_version Returns the version of HTTP of the probe response
# TYPE probe_http_version gauge
probe_http_version 2
# HELP probe_ip_addr_hash Specifies the hash of IP address. It's useful to detect if the IP address changes.
# TYPE probe_ip_addr_hash gauge
probe_ip_addr_hash 9.2661398e+07
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_ssl_earliest_cert_expiry Returns earliest SSL cert expiry in unixtime
# TYPE probe_ssl_earliest_cert_expiry gauge
probe_ssl_earliest_cert_expiry 1.660262399e+09
# HELP probe_ssl_last_chain_expiry_timestamp_seconds Returns last SSL chain expiry in timestamp seconds
# TYPE probe_ssl_last_chain_expiry_timestamp_seconds gauge
probe_ssl_last_chain_expiry_timestamp_seconds 1.660262399e+09
# HELP probe_ssl_last_chain_info Contains SSL leaf certificate information
# TYPE probe_ssl_last_chain_info gauge
probe_ssl_last_chain_info{fingerprint_sha256="86c65481f9b3962065fc0a4b4ffbf83391cd0451f60e33903276b257acfe4128"} 1
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 1
# HELP probe_tls_version_info Contains the TLS version used
# TYPE probe_tls_version_info gauge
probe_tls_version_info{version="TLS 1.2"} 1



Module configuration:
prober: http
timeout: 5s
http:
    valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
    preferred_ip_protocol: ip4
    ip_protocol_fallback: true
    headers:
        Host: m.halykmarket.com
        Origin: m.halykmarket.com
    proxy_url: http://10.204.11.146:3128
    follow_redirects: true
tcp:
    ip_protocol_fallback: true
icmp:
    ip_protocol_fallback: true
dns:
    ip_protocol_fallback: true
```

### What did you do that produced an error?
Some of URLs have redirects

### What did you expect to see?
Expect to see body_length of final page, not redirect HTTP answer

### What did you see instead?

I see body_length of redirect answer

```
# HELP probe_http_uncompressed_body_length Length of uncompressed response body
# TYPE probe_http_uncompressed_body_length gauge
probe_http_uncompressed_body_length 4467
```
