### ISSUE TITLE
cannot set proper header for 30. requests

### ISSUE THREAD

**Issue by Savemech** [prometheus/blackbox_exporter#90]
```
+----------+     +-----------+
|          +---->|           |
|prometheus|     |bb-exporter|
|          |     |           |
+----------+     +----+------+
                      |
                      |
                      |
                      v
         +-----------------+
         |                 |
         |       nginx     |
         |                 |
         +-----------------+

```
I have multiple targets configured in prometheus.yml for blackbox_exporter, and when BB got request to go and scrape, BB sometimes does not use configured attributes:
```
modules:
  http_2xx:
    prober: http
    timeout: 30s
    http:
      valid_status_codes: [200,301,302]
      method: GET
      headers:
        User-Agent: bb-prober
      fail_if_not_ssl: true
      tls_config:
        insecure_skip_verify: false
      protocol: "tcp4"
      preffered_ip_protocol: "ip4"
```
how does this look like from web server log:
```
10.0.0.1 somefancyhost.com - [23/Dec/2016:12:27:57] "GET /home HTTP/1.1" *301* 178 "-" "bb-prober" "-" - 0.000 -
10.0.0.1 somefancyhost.com - [23/Dec/2016:12:27:57] "GET /home HTTP/1.1" *301* 178 "-" "bb-prober" "-" - 0.000 -
10.0.0.1 somefancyhost.com - [23/Dec/2016:12:27:57] "GET /home HTTP/1.1" *301* 178 "-" "bb-prober" "-" - 0.000 -
10.0.0.1 somefancyhost.com - [23/Dec/2016:12:27:57] "GET /home HTTP/1.1" *301* 178 "-" "bb-prober" "-" - 0.000 -
10.0.0.1 somefancyhost.com - [23/Dec/2016:12:27:57] "GET /home HTTP/1.1" *301* 178 "-" "bb-prober" "-" - 0.000 -
10.0.0.1 somefancyhost.com - [23/Dec/2016:12:27:57] "GET /home HTTP/1.1" *301* 178 "-" "bb-prober" "-" - 0.000 -
10.0.0.1 somefancyhost.com - [23/Dec/2016:12:27:57] "GET /home/ HTTP/1.1" *200* 509 "https://somefancyhost.com/home" "Go-http-client/1.1" "2.71" - 0.000 -
10.0.0.1 somefancyhost.com - [23/Dec/2016:12:27:57] "GET /home/ HTTP/1.1" *200* 509 "https://somefancyhost.com/home" "Go-http-client/1.1" "2.71" - 0.000 -
10.0.0.1 somefancyhost.com - [23/Dec/2016:12:27:57] "GET /home/ HTTP/1.1" *200* 509 "https://somefancyhost.com/home" "Go-http-client/1.1" "2.71" - 0.000 -

```
Assuming my observations, when response code is not 200, header is not set.

**Comment by brian-brazil** [comment]
That's not the blackbox exporter, it's some other Go application that appears to be following a link.

**Comment by Savemech** [comment]
there is literally no other Go applications on this host (10.0.0.1)

**Comment by eliecharra** [comment]
Same issue with following BB config

```yml
modules:
  http:
    prober: http
    timeout: 5s
    http:
      headers:
        Accept: text/html
    protocol: "tcp4"
```

My application is returning HTTP 500 when no acceptable Accept header math in request, I got these headers on my Sentry :

![selection_005](https://cloud.githubusercontent.com/assets/6154987/21523497/31f177be-cd0f-11e6-96ef-c82f278e7804.jpg)

`protocol: "tcp4"` does not seems to be apllied too, il my logs I have following errors

```
time="2016-12-28T15:06:51+01:00" level=warning msg="Error for HTTP request to http://xxxx.com: Get http://xxxx.com: dial tcp6 [2400:cb00:2048:1::xxxx:xxxx]:80: connect: network is unreachable" source="http.go:159"
