### ISSUE TITLE
Use PKCS12 certificate instead of cert and key

### ISSUE THREAD

**Issue by redsigma** [prometheus/blackbox_exporter#910]
### Host operating system: output of `uname -a`
`Linux ba95b0da68b3 5.4.0-1066-aws #69~18.04.1-Ubuntu SMP Wed Feb 9 15:36:54 UTC 2022 x86_64 GNU/Linux`

### blackbox_exporter version: output of `blackbox_exporter --version`
```
blackbox_exporter, version 0.19.0 (branch: HEAD, revision: 5d575b88eb12c65720862e8ad2c5890ba33d1ed0)
  build user:       root@2b0258d5a55a
  build date:       20210510-12:56:44
  go version:       go1.16.4
  platform:         linux/amd64
```

### What is the blackbox.yml module config.
<details><summary>Click to see yaml</summary>

```
modules:
  https_2xx:
    http:
      follow_redirects: true
      preferred_ip_protocol: ip4
      valid_status_codes: []
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      fail_if_not_ssl: true
      ip_protocol_fallback: false
    prober: http
    timeout: 5s
    tcp:
      ip_protocol_fallback: false
    icmp:
      ip_protocol_fallback: false

  https_pki_2xx:
    http:
      follow_redirects: true
      preferred_ip_protocol: ip4
      valid_status_codes: []
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      fail_if_not_ssl: false
      ip_protocol_fallback: false
      tls_config:
        cert_file: /etc/blackbox/certfile.p12
        key_file: /etc/blackbox/certfile.p12
        insecure_skip_verify: true
    prober: http
    timeout: 5s
    tcp:
      ip_protocol_fallback: false
    icmp:
      ip_protocol_fallback: false
```
</details>

### What logging output did you get from adding `&debug=true` to the probe URL?
<details><summary>Click for logs</summary>

```
Logs for the probe:
ts=2022-05-16T14:42:00.732219788Z caller=main.go:320 module=http_2xx target=https://url1.com/ level=info msg="Beginning probe" probe=http timeout_seconds=5
ts=2022-05-16T14:42:00.732337939Z caller=http.go:335 module=http_2xx target=https://url1.com/ level=info msg="Resolving target address" ip_protocol=ip4
ts=2022-05-16T14:42:00.733791115Z caller=http.go:335 module=http_2xx target=https://url1.com/ level=info msg="Resolved target address" ip=80.158.25.206
ts=2022-05-16T14:42:00.733875936Z caller=main.go:130 module=http_2xx target=https://url1.com/ level=error msg="Error generating HTTP client" err="unable to use specified client cert (/etc/blackbox/certfile.p12) & key (/etc/blackbox/certfile.p12): tls: failed to find any PEM data in certificate input"
ts=2022-05-16T14:42:00.733898766Z caller=main.go:320 module=http_2xx target=https://url1.com/ level=error msg="Probe failed" duration_seconds=0.001637997



Metrics that would have been returned:
# HELP probe_dns_lookup_time_seconds Returns the time taken for probe dns lookup in seconds
# TYPE probe_dns_lookup_time_seconds gauge
probe_dns_lookup_time_seconds 0.001482216
# HELP probe_duration_seconds Returns how long the probe took to complete in seconds
# TYPE probe_duration_seconds gauge
probe_duration_seconds 0.001637997
# HELP probe_failed_due_to_regex Indicates if probe failed due to regex
# TYPE probe_failed_due_to_regex gauge
probe_failed_due_to_regex 0
# HELP probe_http_content_length Length of http content response
# TYPE probe_http_content_length gauge
probe_http_content_length 0
# HELP probe_http_duration_seconds Duration of http request by phase, summed over all redirects
# TYPE probe_http_duration_seconds gauge
probe_http_duration_seconds{phase="connect"} 0
probe_http_duration_seconds{phase="processing"} 0
probe_http_duration_seconds{phase="resolve"} 0.001482216
probe_http_duration_seconds{phase="tls"} 0
probe_http_duration_seconds{phase="transfer"} 0
# HELP probe_http_redirects The number of redirects
# TYPE probe_http_redirects gauge
probe_http_redirects 0
# HELP probe_http_ssl Indicates if SSL was used for the final redirect
# TYPE probe_http_ssl gauge
probe_http_ssl 0
# HELP probe_http_status_code Response HTTP status code
# TYPE probe_http_status_code gauge
probe_http_status_code 0
# HELP probe_http_uncompressed_body_length Length of uncompressed response body
# TYPE probe_http_uncompressed_body_length gauge
probe_http_uncompressed_body_length 0
# HELP probe_http_version Returns the version of HTTP of the probe response
# TYPE probe_http_version gauge
probe_http_version 0
# HELP probe_ip_addr_hash Specifies the hash of IP address. It's useful to detect if the IP address changes.
# TYPE probe_ip_addr_hash gauge
probe_ip_addr_hash 1.777859232e+09
# HELP probe_ip_protocol Specifies whether probe ip protocol is IP4 or IP6
# TYPE probe_ip_protocol gauge
probe_ip_protocol 4
# HELP probe_success Displays whether or not the probe was a success
# TYPE probe_success gauge
probe_success 0



Module configuration:
prober: http
timeout: 5s
http:
    valid_http_versions:
        - HTTP/1.1
        - HTTP/2.0
    preferred_ip_protocol: ip4
    tls_config:
        cert_file: /etc/blackbox/certfile.p12
        key_file: /etc/blackbox/certfile.p12
        insecure_skip_verify: true
    follow_redirects: true
dns:
    ip_protocol_fallback: true
    
```
</details>

### What did you do that produced an error?
I wanted to access the url using the pki certificate

### What did you expect to see?
A Successful result

### What did you see instead?
A Failure result
