### ISSUE TITLE
ICMP ping packet size

### ISSUE THREAD

**Issue by uquerx** [prometheus/blackbox_exporter#920]
Hello everybody,

From my prometheus server I'm not able to ping the device I wish to monitor with the default icmp packet size (64 bytes) but ok if I force with a ping 32 byte.
### Exemple
```
# ping 10.X.X.200
PING 10.X.X.200 (10.X.X.200) 56(84) bytes of data.
--- 10.X.X.200 ping statistics ---
7 packets transmitted, 0 received, 100% packet loss, time 9ms

```
but like this
```
# ping -s 32 10.X.X.200
PING 10.X.X.200 (10.X.X.200) 32(60) bytes of data.
40 bytes from 10.X.X.200: icmp_seq=1 ttl=63 time=1.97 ms
40 bytes from 10.X.X.200: icmp_seq=2 ttl=63 time=1.92 ms
40 bytes from 10.X.X.200: icmp_seq=3 ttl=63 time=1.86 ms
--- 10.X.X.200 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 3ms
```
Do you know if with blackbox_exporter there is a chance to configure an ICMP ping probe with a 32 Byte packet instead of 64 Bytes???

### Host operating system:
Linux 5.4.106-1-pve #1 SMP PVE 5.4.106-1 (Fri, 19 Mar 2021 11:08:47 +0100) x86_64 GNU/Linux

This is my `prometheus.yml` file:
```
- job_name: blackbox-ping
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets:
        - 10.XX.XX.200   # <== Put here your targets
    relabel_configs:    # <== This comes from the blackbox exporter README
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115  # Blackbox exporter
```
