### ISSUE TITLE
Ping to Starlink CGN-Gateway (100.64.0.1) returns 0ms via blackbox

### ISSUE THREAD

**Issue by Somebodyisnobody** [prometheus/blackbox_exporter#934]
### Host operating system: output of `uname -a`
`Linux starlink 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux`

### blackbox_exporter version: output of `blackbox_exporter --version`
```
blackbox_exporter, version 0.19.0 (branch: HEAD, revision: 5d575b88eb12c65720862e8ad2c5890ba33d1ed0)
  build user:       root@2b0258d5a55a
  build date:       20210510-12:59:14
  go version:       go1.16.4
  platform:         linux/arm
```

### What is the blackbox.yml module config.
```
modules:
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: ip4
  icmp_ipv4:
    prober: icmp
    icmp:
      preferred_ip_protocol: ip4
```

### What is the prometheus.yml scrape config.
```
  - job_name: 'blackbox'
    scrape_interval: 3s
    scrape_timeout: 3s
    metrics_path: /probe
    params:
      module: [icmp_ipv4]
    static_configs:
      - targets: [ '192.168.100.1' ]
        labels:
          name: 'Antenne'
      - targets: [ '100.64.0.1' ]
        labels:
          name: 'Backbone-CGN-Gateway'
      - targets: [ 'quicksight.eu-central-1.amazonaws.com' ]
        labels:
          name: 'Amazon Web Services Frankfurt'
      - targets: [ 'google.de' ]
        labels:
          name: 'google.de'
      - targets: [ 'de.wikipedia.org' ]
        labels:
          name: 'Wikipedia DE'
      - targets: [ '8.8.8.8' ]
        labels:
          name: 'google_a DNS'
      - targets: [ '8.8.4.4' ]
        labels:
          name: 'google_b DNS'
      - targets: [ '1.1.1.1' ]
        labels:
          name: 'cloudflare DNS'
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
```

### What logging output did you get from adding `&debug=true` to the probe URL?
I cannot do this as I cannot kill the existing process on port 9115 because docker quits my container-shell.

### What did you do that produced an error?
Configured blackbox to ping `100.64.0.1` via ICMPv4.

### What did you expect to see?
A real ping about 60ms that I see when I execute `ping 100.64.0.1` from my SSH-console

### What did you see instead?
The output is a ping of 0ms. This is not realistic.
