### ISSUE TITLE
Blackbox Exporter seems to ignore Host Header for HTTP probe

### ISSUE THREAD

**Issue by stewartn782** [prometheus/blackbox_exporter#936]
## Host operating system: output of uname -a
Running Blackbox Exporter container on ECS

`Linux ip-XXX-XXX-XXX-XXX.eu-west-1.compute.internal 4.14.209-160.339.amzn2.x86_64 #1 SMP Wed Dec 16 22:44:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

## blackbox_exporter version: output of blackbox_exporter --version
```
blackbox_exporter, version 0.21.1 (branch: master, revision: d26fcc665935e962ba9ce331d3dc82babe0627c4)
  build user:       root@1e0b3966ba2f
  build date:       20220618-12:55:36
  go version:       go1.18.3
  platform:         linux/amd64
```
## What is the blackbox.yml module config.
```
modules:
  http_2xx:
    prober: http
    timeout: 15s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: []  # Defaults to 2xx
      method: GET
      headers:
        Host: my.super.host
      follow_redirects: true
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4" # defaults to "ip6"
      ip_protocol_fallback: false  # no fallback to "ip6"
```
## What is the prometheus.yml scrape config.
```
  - job_name: 'blackbox-https'
    scrape_timeout: 15s
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
     - targets:
         - https://my.super.host/actuator/health
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: blackbox.ecs.super.host:9115
```
## What logging output did you get from adding &debug=true to the probe URL?
```
ts=2022-06-22T09:51:51.454000732Z caller=main.go:352 module=http_2xx target=https://my.super.host/actuator/health level=info msg="Beginning probe" probe=http timeout_seconds=15
ts=2022-06-22T09:51:51.454213407Z caller=http.go:336 module=http_2xx target=https://my.super.host/actuator/health level=info msg="Resolving target address" target=my.super.host ip_protocol=ip4
ts=2022-06-22T09:51:51.597195547Z caller=http.go:336 module=http_2xx target=https://my.super.host/actuator/health level=info msg="Resolved target address" target=my.super.host ip=IP_ADDR
ts=2022-06-22T09:51:51.597315207Z caller=client.go:252 module=http_2xx target=https://my.super.host/actuator/health level=info msg="Making HTTP request" url=https://IP_ADDR/actuator/health host=my.super.host
ts=2022-06-22T09:51:51.608998705Z caller=main.go:144 module=http_2xx target=https://my.super.host/actuator/health level=info msg="Received HTTP response" status_code=403
ts=2022-06-22T09:51:51.609091806Z caller=main.go:144 module=http_2xx target=https://my.super.host/actuator/health level=info msg="Response timings for roundtrip" roundtrip=0 start=2022-06-22T09:51:51.59739594Z dnsDone=2022-06-22T09:51:51.59739594Z connectDone=2022-06-22T09:51:51.598781347Z gotConn=2022-06-22T09:51:51.605693494Z responseStart=2022-06-22T09:51:51.608930359Z tlsStart=2022-06-22T09:51:51.598839261Z tlsDone=2022-06-22T09:51:51.605605554Z end=2022-06-22T09:51:51.609079507Z
ts=2022-06-22T09:51:51.609170723Z caller=main.go:352 module=http_2xx target=https://my.super.host/actuator/health level=info msg="Probe succeeded" duration_seconds=0.155050196
```
## What did you do that produced an error?
I have added a new scrape target to the configuration which uses the http_2xx module to do http checks.

## What did you expect to see?
I expected the hostname rather than the IP to be used in the url:

`ts=2022-06-22T09:51:51.597315207Z caller=client.go:252 module=http_2xx target=https://my.super.host/actuator/health level=info msg="Making HTTP request" url=https://my.super.host/actuator/health host=my.super.host`

## What did you see instead?
The IP is used in the url rather than the hostname even though it has been specified in the "headers" section of the Blackbox Exporter config. The request seems to be failing with a 403 because the host header isn't being passed through to the service when it makes the call using the IP:
```
ts=2022-06-22T09:51:51.597315207Z caller=client.go:252 module=http_2xx target=https://my.super.host/actuator/health level=info msg="Making HTTP request" url=https://IP_ADDR/actuator/health host=my.super.host
ts=2022-06-22T09:51:51.608998705Z caller=main.go:144 module=http_2xx target=https://my.super.host/actuator/health level=info msg="Received HTTP response" status_code=403
```
Using curl works as expected:
```
[root@hostname ec2-user]# curl -X GET -k -H "Host: my.super.host" https://IP_ADDR/actuator/health
{"status":"UP"}
```
Removing the host header replicates the issue which Blackbox Exporter is encountering:
```
[root@hostname ec2-user]# curl -X GET -k https://IP_ADDR/actuator/health
{"message":"Forbidden"}
```
