### ISSUE TITLE
Http probe fails when container is inside docker network

### ISSUE THREAD

**Issue by petarnikolov** [prometheus/blackbox_exporter#945]
### Host operating system: output of `uname -a`
Linux LEX-BG007-Ubuntu 5.15.0-39-generic #42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
### blackbox_exporter version: output of `blackbox_exporter --version`
v0.21.0

### docker-compose.yml
```
---
version: '2'
services:

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.19.0
    restart: always
    ports:
    - "9115:9115"
    volumes:
    - "./config:/blackbox_exporter"
    command: --config.file=/blackbox_exporter/config.yml --log.level=debug
    networks:
    - monitoring
networks:
  monitoring:
    internal: true

```

### What is the blackbox.yml module config.
```
modules:
  http_2xx:
    prober: http
    timeout: 20s
    http:
      follow_redirects: true      
      valid_status_codes: [200, 301, 302]        
      preferred_ip_protocol: "ip4"      
  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      method: POST
      follow_redirects: true        
      basic_auth:
        username: "username"
        password: "mysecret"
  tcp_connect:
    prober: tcp
    timeout: 5s
  icmp_test:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: ip4
```

### What is the prometheus.yml scrape config.

```
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_prometheus]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io    # Target to probe with http.
        - https://prometheus.io   # Target to probe with https.
        - https://innobb.pnk.cc # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
```

### What logging output did you get from adding `&debug=true` to the probe URL?

```
Logs for the probe:
ts=2022-07-13T09:35:05.358158878Z caller=main.go:320 module=http_2xx target=https://www.prometheus.io level=info msg="Beginning probe" probe=http timeout_seconds=20
ts=2022-07-13T09:35:05.358258072Z caller=http.go:335 module=http_2xx target=https://www.prometheus.io level=info msg="Resolving target address" ip_protocol=ip4
ts=2022-07-13T09:35:05.411535075Z caller=http.go:335 module=http_2xx target=https://www.prometheus.io level=info msg="Resolved target address" ip=172.67.201.240
ts=2022-07-13T09:35:05.411648779Z caller=client.go:251 module=http_2xx target=https://www.prometheus.io level=info msg="Making HTTP request" url=https://172.67.201.240 host=www.prometheus.io
ts=2022-07-13T09:35:25.375559162Z caller=main.go:130 module=http_2xx target=https://www.prometheus.io level=error msg="Error for HTTP request" err="Get \"https://172.67.201.240\": context deadline exceeded"
ts=2022-07-13T09:35:25.375671432Z caller=main.go:130 module=http_2xx target=https://www.prometheus.io level=info msg="Response timings for roundtrip" roundtrip=0 start=2022-07-13T09:35:05.411738379Z dnsDone=2022-07-13T09:35:05.411738379Z connectDone=0001-01-01T00:00:00Z gotConn=0001-01-01T00:00:00Z responseStart=0001-01-01T00:00:00Z tlsStart=0001-01-01T00:00:00Z tlsDone=0001-01-01T00:00:00Z end=0001-01-01T00:00:00Z
ts=2022-07-13T09:35:25.375924687Z caller=main.go:320 module=http_2xx target=https://www.prometheus.io level=error msg="Probe failed" duration_seconds=20.017727352

```
### What did you do that produced an error?

Deployed blackbox_exporter in docker inside a docker network and tried running `http://172.24.0.2:9115/probe?module=http_2xx&target=https://www.prometheus.io&debug=true`  which returns the log above. Removing the blackbox container from the docker network fixes the issue

### What did you expect to see?
Successful probe
### What did you see instead?
"Error for HTTP request" err="Get \"https://172.67.201.240\": context deadline exceeded"
