### ISSUE TITLE
metrics disapprear after "same timestamp" error

### ISSUE THREAD

**Issue by aparcar** [prometheus/blackbox_exporter#95]
blackbox_exporter 0.3.0 / prometheus 1.4.1

prometheus log:

`level=warning msg="Error on ingesting samples with different value but same timestamp" numDropped=2 source="scrape.go:471"`

scraping ~10 sites with `http_2xx` module

entries in prometheus webinterface disappearing  as if they had a time to live running out.

**Comment by brian-brazil** [comment]
Are your target labels unique for these targets?

**Comment by aparcar** [comment]
Yes, label target and label instance are the site url, unique per target

I am using the standard blackbox relabel config.


Am 09.01.2017 um 11:04 schrieb Brian Brazil:

**Comment by brian-brazil** [comment]
Can you share your scrape_config?

**Comment by aparcar** [comment]
```
  - job_name: 'blackbox'
    scrape_interval: 10m 
    scrape_timeout: 30s 
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
    - files:
      - "/etc/prometheus/targets/sites.yml"
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: 127.0.0.1:9115  # Blackbox exporter.
```
