### ISSUE TITLE
Is it possible to set filter with "fail_if_header_matches" directive?

### ISSUE THREAD

**Issue by yd47** [prometheus/blackbox_exporter#950]
### Host operating system: output of `uname -a`
Linux 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter --version`

prom/blackbox-exporter:v0.19.0

### What is the blackbox.yml module config.
```
...
http_2xx_insecure:
  prober: http
  http:
    method: GET
    valid_status_codes: [200, 302, 303]
    fail_if_header_matches:
      - header: X_Language
        regexp: '.*ru\-RU.*'
        allow_missing: true
    tls_config:
      insecure_skip_verify: true
...
```
### What is the prometheus.yml scrape config.
```
...
prom_scrape_configs:
- job_name: blackbox-http-intro
  metrics_path: /probe
  params:
    module: [http_2xx_insecure]
    static_configs:
    - targets:
      - https://192.168.221.25/
      labels:
        host_group: wmware-intro
        name: ilo-integrators-1
...
  relabel_configs:
   - source_labels: [__address__]
     target_label: __param_target
   - source_labels: [__param_target]
     target_label: instance
   - target_label: __address__
     replacement: blackboxexporter:9115 # The blackbox exporter.
...
```
### What logging output did you get from adding `&debug=true` to the probe URL?
Nothing to relate here

### What did you do that produced an error?
Probably it's not an error

### What did you expect to see?
I am checking some server with http probe. This server returns 404 error for requesting URL: 
https://192.168.221.25/locale/locale_ru.json

Here are the response headers:
```
HTTP/1.1 404 Not Found
Strict-Transport-Security: max-age=63072000
X_Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Vary: Accept-Encoding
Keep-Alive: timeout=60, max=195
X-Frame-Options: SAMEORIGIN
Content-Type: text/html
Date: Tue, 26 Jul 2022 22:17:42 GMT
Cache-Control: no-cache
Content-Length: 223
Connection: Keep-Alive
Accept-Ranges: bytes
```

I want to create a filter due to which blackbox would not be triggered if we get http header 'X_Language' with 'ru-RU'". Is it possible with "fail_if_header_matches" or should it be done in another way?

### What did you see instead?
it doesn't work and i get error anyway.
