### ISSUE TITLE
Probe failure

### ISSUE THREAD

**Issue by heymukesh** [prometheus/blackbox_exporter#964]
Hi Team,

We are getting probe failed for some of VIPs that we are monitoring.

The error says [certificat](x509: certificate signed by unknown authority")

ts=2022-09-05T12:33:58.904357154Z caller=main.go:130 module=http_2xx target=https://abc.example.com level=error msg="Error for HTTP request" err="Get \"https://xxx.yyy.zz.ww\": x509: certificate signed by unknown authority"

When we checked the ssl certs for the VIPs, we have the same issuer for all the VIPs. Mysterious thing is that it works for some and doesn't work for some with the above error msg.

Can you please help me in resolving the issue.

Regards,
Mukesh

**Comment by candlerb** [comment]
(Aside: questions about how to *use* prometheus components would be best asked on the prometheus-users group)

As the error says, the certificate is signed by an unknown authority.  To fix, as per [this example](https://github.com/prometheus/blackbox_exporter/blob/master/example.yml) and [here](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#tls_config):

```
  http_2xx_example:
    prober: http
    timeout: 5s
    http:
      ...
      tls_config:
        ca_file: "/certs/my_cert.crt"
```

where `/certs/my_cert.crt` is the CA certificate for the CA that signed the target's certificate.

If the host returns a different certificate identity than the hostname you were connecting to, then you may need to use the `server_name` directive as well:

```
  http_2xx_example:
    prober: http
    timeout: 5s
    http:
      ...
      tls_config:
        server_name: abc.example.com
        ca_file: "/certs/my_cert.crt"
```
