### ISSUE TITLE
Method: HEAD - response size is the same as GET

### ISSUE THREAD

**Issue by KlemenDanfoss** [prometheus/blackbox_exporter#966]
### blackbox_exporter version: output of `blackbox_exporter --version`

0.22.0

### What is the blackbox.yml module config.
```
modules:
  http_2xx:
    http:
      enable_http2: true
      fail_if_not_ssl: true
      follow_redirects: true
      method: HEAD
      preferred_ip_protocol: ip4
      valid_http_versions:
      - HTTP/2.0
    prober: http
    timeout: 5s
```
### What did you expect to see?
Response size should get smaller
```
# HELP probe_http_content_length Length of http content response
# TYPE probe_http_content_length gauge
probe_http_content_length 1204
```
### What did you see instead?
Response size is the same
```
# HELP probe_http_content_length Length of http content response
# TYPE probe_http_content_length gauge
probe_http_content_length 1204
```

On the 'other side' we have Azure Application Gateway.
