### ISSUE TITLE
ICMP probe always perform DNS resolution?

### ISSUE THREAD

**Issue by paolobyte** [prometheus/blackbox_exporter#978]
Hi, I am doing icmp probe every second for both domain name and IP addresses. The issue that I see is that whether I put IP or DNS name, the server always performs DNS query to our DNS server. So if im pinging 100 hosts every second, it also performs 100 dns query every second. 

I checked my machine and DNS caching seems ok. As I ping other dns name, then ping it again after few seconds or so, it doesn't do dns query any more on the succeeding pings. I am monitoring this through tcpdump at dns server.

What's weird is that even if the host is an IP address, it performs DNS query for that!

Is it normal that if your scrape_timeout in prometheus is 1s, then icmp module timeout for blackbox is 1s, it doesn't follow it? What I see is 0.5s timeout on the actual logs. 

### Host operating system: output of `uname -a`

Linux grafana 5.4.0-128-generic #144-Ubuntu SMP Tue Sep 20 11:00:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### blackbox_exporter version: output of `blackbox_exporter --version`

blackbox_exporter, version 0.21.1 (branch: HEAD, revision: e0d5e4453c54b6e508531a761131d7f21007783c)
  build user:       root@6e3666c7d63f
  build date:       20220617-12:22:49
  go version:       go1.18.3
  platform:         linux/amd64

### What is the blackbox.yml module config.

modules:
  http_2xx:
    prober: http
  http_post_2xx:
    prober: http
    http:
      method: POST
  tcp_connect:
    prober: tcp
  pop3s_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^+OK"
      tls: true
      tls_config:
        insecure_skip_verify: false
  grpc:
    prober: grpc
    grpc:
      tls: true
      preferred_ip_protocol: "ip4"
  grpc_plain:
    prober: grpc
    grpc:
      tls: false
      service: "service1"
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
      - send: "SSH-2.0-blackbox-ssh-check"
  irc_banner:
    prober: tcp
    tcp:
      query_response:
      - send: "NICK prober"
      - send: "USER prober prober prober :prober"
      - expect: "PING :([^ ]+)"
        send: "PONG ${1}"
      - expect: "^:[^ ]+ 001"
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
            preferred_ip_protocol: "ip4"
            source_ip_address: "10.4.1.48"
            #    dns:
            #ip_protocol_fallback: false
            #recursion_desired: false
    http:
            ip_protocol_fallback: false
            follow_redirects: false
            enable_http2: false

**Comment by gforster** [comment]
I'm having a similar problem where the ICMP probe is not respecting the DNS caching, causing heavy DNS traffic when probing thousands of servers every 15 seconds.

**Comment by dgl** [comment]
blackbox_exporter doesn't have any built-in DNS cache, it's not its place to do that. The standard Unix way to do this is to have some caching done out of process, e.g. via daemons like nscd or systemd-resolved, which you could consider installing/enabling on systems where you see this as a problem.

However Prometheus itself can also do service discovery, so your service discovery can potentially provide an IP address rather than a hostname.

If you're using static configs rather than another service discovery mechanism a potential answer is to use DNS service discovery, so prometheus periodically resolves the hostnames as part of service discovery, then passes an IP address to blackbox_exporter. (Obviously this changes where the DNS resolution happens, so if your blackbox_exporter is not using the same recursive DNS service as your prometheus instance you may see different behaviour, hence why you have to configure this yourself depending on your infrastructure, and potentially combine with a dns probe.)

An example of using DNS service discovery for ICMP probes could look a bit like this:

```yaml
scrape_configs:
  - job_name: blackbox-icmp
    metrics_path: /probe
    params:
      module: [icmp]
    dns_sd_configs:
      - names:
        - www.example.com
        type: A
        port: 1  # unused for icmp
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
        # drop the unused port
        regex: '(.*):1'
      - source_labels: [__meta_dns_name]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
```

This will then query DNS for the hostname every 30s (but you can configure it via the `refresh_interval` parameter to dns_sd_configs).

Leaving this open as we probably should at least document this somewhere, but I'm not sure where best to put those docs.
