### ISSUE TITLE
[Feature]probe support params of module 

### ISSUE THREAD

**Issue by nkuacac** [prometheus/blackbox_exporter#986]
### Host operating system: output of `uname -a`
any
### blackbox_exporter version: output of `blackbox_exporter --version`

```
blackbox_exporter, version 0.22.0 (branch: HEAD, revision: 0bbd65d1264722f7afb87a72ec4128b9214e5840)
  build user:       root@4d81de342d10
  build date:       20220802-13:56:00
  go version:       go1.18.5
  platform:         linux/amd64
```
### What is the blackbox.yml module config.
```
modules:
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
  http:
    prober: http
    timeout: 5s
    http:
      method: GET
  proxy:
    prober: http
    timeout: 5s
    http:
      method: GET
      proxy_url: "http://172.29.155.255:9115"
      skip_resolve_phase_with_proxy: true
```
### What logging output did you get from adding `&debug=true` to the probe URL?
```
curl 'http://10.249.137.146:80/probe?module=proxy&target=192.168.218.13&debug=true'

probe_success 1



Module configuration:
prober: http
timeout: 5s
http:
    ip_protocol_fallback: true
    skip_resolve_phase_with_proxy: true
    method: GET
    proxy_url: http://172.29.155.255:9115
    follow_redirects: true
    enable_http2: true
tcp:
    ip_protocol_fallback: true
icmp:
    ip_protocol_fallback: true
    ttl: 64
dns:
    ip_protocol_fallback: true
    recursion_desired: true
```

```
curl 'http://10.249.137.146:80/probe?module=http&target=192.168.218.13&proxy_url=http://172.29.155.255:9115&debug=true'

probe_success 0



Module configuration:
prober: http
timeout: 5s
http:
    ip_protocol_fallback: true
    method: GET
    follow_redirects: true
    enable_http2: true
tcp:
    ip_protocol_fallback: true
icmp:
    ip_protocol_fallback: true
    ttl: 64
dns:
    ip_protocol_fallback: true
    recursion_desired: true
```
### What did you do that produced an error?
|   case          |  httpclient   |                   cluster 1                  |                                       cluster 2|
|--|--|--|--|
| case1      |       curl              |   --lb---->blackbox   ---->      |     blackbox 1(as proxy)----> clusterIP|
| case2     |         curl       |   --lb---->blackbox   ---->      |          blackbox 2(as proxy)----> clusterIP|

with dynamic proxy_url  check in cluster network

### What did you expect to see?
```
both
curl 'http://10.249.137.146:80/probe?module=http&target=192.168.218.13&proxy_url=http://172.29.155.255:9115&debug=true'
curl 'http://10.249.137.146:80/probe?module=proxy&target=192.168.218.13&debug=true'
probe success
```
