### ISSUE TITLE
merge ssh_banner

### ISSUE THREAD

**Issue by seaurching** [prometheus/blackbox_exporter#999]
How to merge ssh_banner with different version sshd. 
```
    ssh_banner:
        prober: tcp
        tcp:
            ip_protocol_fallback: true
            query_response:
                - expect: ^SSH-2.0-
                - send: SSH-2.0-blackbox-ssh-check
    ssh_one_banner:
        prober: tcp
        tcp:
            ip_protocol_fallback: true
            query_response:
                - expect: ^SSH-1.9
                - send: SSH-1.9-blackbox-ssh-check
```
